# 取り組んだ軌跡：https://github.com/NatsukiH/apply_prediction

こちらに精度比較を載せています．ぜひご覧ください．

最終の精度: 0.5999766265357284

# 前処理

In [2]:
import numpy as np
import pandas as pd
import sklearn

In [3]:
# 読み込み
application = pd.read_csv("train_x.csv")
application.head()

C:\Users\natsu\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (114) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,職場の様子,（紹介予定）入社後の雇用形態,勤務地 最寄駅3（駅名）,勤務地固定,休日休暇(月曜日),応募先 名称,（派遣先）配属先部署 男女比 男,勤務地 最寄駅3（沿線名）,（派遣先）勤務先写真コメント,勤務地 最寄駅3（分）,...,未使用.13,（紹介予定）待遇・福利厚生,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,応募拠点,給与/交通費 備考,残業なし,これまでの採用者例,期間･時間 備考,（派遣先）概要 勤務先名（フリガナ）
0,3,NaN,NaN,1,0,NaN,6.0,NaN,NaN,NaN,...,NaN,NaN,北千住,NaN,NaN,【月収例】19万5300円＋残業代（21日勤務の場合）,1,NaN,◆開始日はご相談可能です！詳しくはお問い合わせください！,NaN
1,3,1.0,NaN,1,0,NaN,2.0,NaN,NaN,NaN,...,NaN,完備,新御茶ノ水,5.0,NaN,【月収例】26万4600円＋残業代（21日勤務の場合）,1,NaN,NaN,NaN
2,3,1.0,NaN,1,0,NaN,2.0,NaN,NaN,NaN,...,NaN,完備,新御茶ノ水,5.0,NaN,【月収例】26万4600円＋残業代（21日勤務の場合）,1,NaN,NaN,NaN
3,2,1.0,NaN,1,0,NaN,8.0,NaN,NaN,NaN,...,NaN,完備,八丁堀,6.0,NaN,【月収例】25万9875円＋残業代（21日勤務の場合）,0,NaN,◆開始日はご相談可能です！詳しくはお問い合わせください！,NaN
4,2,1.0,NaN,1,0,NaN,8.0,NaN,NaN,NaN,...,NaN,完備,八丁堀,6.0,NaN,【月収例】25万9875円＋残業代（21日勤務の場合）,0,NaN,◆開始日はご相談可能です！詳しくはお問い合わせください！,NaN

In [4]:
application.describe()

,職場の様子,（紹介予定）入社後の雇用形態,勤務地 最寄駅3（駅名）,勤務地固定,休日休暇(月曜日),応募先 名称,（派遣先）配属先部署 男女比 男,勤務地 最寄駅3（沿線名）,（派遣先）勤務先写真コメント,勤務地 最寄駅3（分）,...,オフィスが禁煙・分煙,応募先 所在地 市区町村,仕事写真（下） 写真1 コメント,勤務地 市区町村コード,未使用.13,勤務地 最寄駅2（分）,応募拠点,残業なし,これまでの採用者例,（派遣先）概要 勤務先名（フリガナ）
count,15853.000000,2742.000000,0.0,15853.0,15853.000000,0.0,13801.000000,0.0,0.0,0.0,...,15853.000000,0.0,0.0,15853.000000,0.0,7359.000000,0.0,15853.000000,0.0,0.0
mean,2.946319,1.303793,NaN,1.0,0.006813,NaN,4.997464,NaN,NaN,NaN,...,0.991674,NaN,NaN,137.071848,NaN,7.621008,NaN,0.729578,NaN,NaN
std,0.306926,0.493645,NaN,0.0,0.082259,NaN,2.796697,NaN,NaN,NaN,...,0.090872,NaN,NaN,55.513015,NaN,4.577798,NaN,0.444192,NaN,NaN
min,2.000000,0.000000,NaN,1.0,0.000000,NaN,0.000000,NaN,NaN,NaN,...,0.000000,NaN,NaN,101.000000,NaN,1.000000,NaN,0.000000,NaN,NaN
25%,3.000000,1.000000,NaN,1.0,0.000000,NaN,3.000000,NaN,NaN,NaN,...,1.000000,NaN,NaN,103.000000,NaN,5.000000,NaN,0.000000,NaN,NaN
50%,3.000000,1.000000,NaN,1.0,0.000000,NaN,5.000000,NaN,NaN,NaN,...,1.000000,NaN,NaN,109.000000,NaN,7.000000,NaN,1.000000,NaN,NaN
75%,3.000000,2.000000,NaN,1.0,0.000000,NaN,7.000000,NaN,NaN,NaN,...,1.000000,NaN,NaN,201.000000,NaN,10.000000,NaN,1.000000,NaN,NaN
max,4.000000,2.000000,NaN,1.0,1.000000,NaN,10.000000,NaN,NaN,NaN,...,1.000000,NaN,NaN,631.000000,NaN,46.000000,NaN,1.000000,NaN,NaN

### 全てnanのcolumnを削除してみる

In [5]:
# 全てnanのcolumnを削除
a_1 = application.dropna(how='all', axis=1)
a_1.head()

,職場の様子,（紹介予定）入社後の雇用形態,勤務地固定,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,勤務地 最寄駅2（駅名）,大手企業,（紹介予定）雇用形態備考,週1日からOK,交通費別途支給,...,WEB登録OK,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,（紹介予定）待遇・福利厚生,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし,期間･時間 備考
0,3,NaN,1,0,6.0,NaN,0,NaN,0,0,...,1,1,121,当社スタッフ活躍中です！<BR>,NaN,北千住,NaN,【月収例】19万5300円＋残業代（21日勤務の場合）,1,◆開始日はご相談可能です！詳しくはお問い合わせください！
1,3,1.0,1,0,2.0,淡路町,1,正社員,0,0,...,1,1,101,ランチに嬉しい社員食堂完備の職場です！<BR>,完備,新御茶ノ水,5.0,【月収例】26万4600円＋残業代（21日勤務の場合）,1,NaN
2,3,1.0,1,0,2.0,淡路町,1,正社員,0,0,...,1,1,101,ランチに嬉しい社員食堂完備の職場です！<BR>,完備,新御茶ノ水,5.0,【月収例】26万4600円＋残業代（21日勤務の場合）,1,NaN
3,2,1.0,1,0,8.0,宝町,0,正社員,0,0,...,1,1,102,落ち着いた雰囲気の職場環境です！<BR>,完備,八丁堀,6.0,【月収例】25万9875円＋残業代（21日勤務の場合）,0,◆開始日はご相談可能です！詳しくはお問い合わせください！
4,2,1.0,1,0,8.0,宝町,0,正社員,0,0,...,1,1,102,落ち着いた雰囲気の職場環境です！<BR>,完備,八丁堀,6.0,【月収例】25万9875円＋残業代（21日勤務の場合）,0,◆開始日はご相談可能です！詳しくはお問い合わせください！

In [6]:
a_1.nunique(dropna=False)

職場の様子                  3
（紹介予定）入社後の雇用形態         4
勤務地固定                  1
休日休暇(月曜日)              2
（派遣先）配属先部署　男女比　男      12
                    ...
勤務地　最寄駅1（駅名）        1729
勤務地　最寄駅2（分）           33
給与/交通費　備考            556
残業なし                   2
期間･時間　備考               9
Length: 127, dtype: int64

### すべて同じ値の列は消去してみる

In [7]:
# 各行においてユニークな値のリスト
nunipue_count_list = list(a_1.nunique(dropna=False))
# 列名のリスト
a_1_columns_list = a_1.columns.values
# ユニークな値が1つだけの行を除外する
a_2 = a_1.copy()

for index in range(len(nunipue_count_list)):
#     ユニークな値が1つだけの時
    if nunipue_count_list[index] == 1:
        column_name = a_1_columns_list[index]
        a_2 = a_2.drop([column_name], axis=1)
        
a_2.nunique(dropna=False)

職場の様子                  3
（紹介予定）入社後の雇用形態         4
休日休暇(月曜日)              2
（派遣先）配属先部署　男女比　男      12
勤務地　最寄駅2（駅名）         840
                    ...
勤務地　最寄駅1（駅名）        1729
勤務地　最寄駅2（分）           33
給与/交通費　備考            556
残業なし                   2
期間･時間　備考               9
Length: 97, dtype: int64

In [8]:
a_2.head()

,職場の様子,（紹介予定）入社後の雇用形態,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,勤務地 最寄駅2（駅名）,大手企業,（紹介予定）雇用形態備考,交通費別途支給,（派遣先）配属先部署 人数,残業月20時間以上,...,給与/交通費 給与下限,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,（紹介予定）待遇・福利厚生,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし,期間･時間 備考
0,3,NaN,0,6.0,NaN,0,NaN,0,12.0,0,...,1550,1,121,当社スタッフ活躍中です！<BR>,NaN,北千住,NaN,【月収例】19万5300円＋残業代（21日勤務の場合）,1,◆開始日はご相談可能です！詳しくはお問い合わせください！
1,3,1.0,0,2.0,淡路町,1,正社員,0,33.0,0,...,1800,1,101,ランチに嬉しい社員食堂完備の職場です！<BR>,完備,新御茶ノ水,5.0,【月収例】26万4600円＋残業代（21日勤務の場合）,1,NaN
2,3,1.0,0,2.0,淡路町,1,正社員,0,33.0,0,...,1800,1,101,ランチに嬉しい社員食堂完備の職場です！<BR>,完備,新御茶ノ水,5.0,【月収例】26万4600円＋残業代（21日勤務の場合）,1,NaN
3,2,1.0,0,8.0,宝町,0,正社員,0,5.0,1,...,1650,1,102,落ち着いた雰囲気の職場環境です！<BR>,完備,八丁堀,6.0,【月収例】25万9875円＋残業代（21日勤務の場合）,0,◆開始日はご相談可能です！詳しくはお問い合わせください！
4,2,1.0,0,8.0,宝町,0,正社員,0,5.0,1,...,1650,1,102,落ち着いた雰囲気の職場環境です！<BR>,完備,八丁堀,6.0,【月収例】25万9875円＋残業代（21日勤務の場合）,0,◆開始日はご相談可能です！詳しくはお問い合わせください！

### NANが10000以上の指標を削除してみる

In [9]:
# nanのカウント
null_count = list(a_2.isnull().sum())
# 列名のリスト
a_2_columns_list = a_2.columns.values
# NANが10000以上の指標を削除してみる
a_3 = a_2.copy()

for index in range(len(null_count)):
#     NANが10000以上のとき
    if null_count[index] >= 10000:
        column_name = a_2_columns_list[index]
        a_3 = a_3.drop([column_name], axis=1)
        
a_3.isnull().sum()

職場の様子                  0
休日休暇(月曜日)              0
（派遣先）配属先部署　男女比　男    2052
勤務地　最寄駅2（駅名）        8367
大手企業                   0
                    ...
（派遣先）職場の雰囲気            4
勤務地　最寄駅1（駅名）           0
勤務地　最寄駅2（分）         8494
給与/交通費　備考           3556
残業なし                   0
Length: 86, dtype: int64

In [10]:
a_3.head()

,職場の様子,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,勤務地 最寄駅2（駅名）,大手企業,交通費別途支給,（派遣先）配属先部署 人数,残業月20時間以上,職種コード,1日7時間以下勤務OK,...,お仕事のポイント（仕事PR）,扶養控除内,給与/交通費 給与下限,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし
0,3,0,6.0,NaN,0,0,12.0,0,22010,1,...,◆駅からスグ！飲食店・コンビニが近く便利！職場環境ＧＯＯＤ◎！当社含む派遣スタッフ多数活躍中...,0,1550,1,121,当社スタッフ活躍中です！<BR>,北千住,NaN,【月収例】19万5300円＋残業代（21日勤務の場合）,1
1,3,0,2.0,淡路町,1,0,33.0,0,20020,1,...,◆開始日相談可能です♪複数路線が利用でき便利！休憩室完備の自社ビル！当社スタッフさん就業中！...,0,1800,1,101,ランチに嬉しい社員食堂完備の職場です！<BR>,新御茶ノ水,5.0,【月収例】26万4600円＋残業代（21日勤務の場合）,1
2,3,0,2.0,淡路町,1,0,33.0,0,20020,1,...,◆開始日相談可能です♪複数路線が利用でき便利！休憩室完備の自社ビル！当社スタッフさん就業中！...,0,1800,1,101,ランチに嬉しい社員食堂完備の職場です！<BR>,新御茶ノ水,5.0,【月収例】26万4600円＋残業代（21日勤務の場合）,1
3,2,0,8.0,宝町,0,0,5.0,1,20020,0,...,◆最寄駅から徒歩圏内！複数路線が利用可能！近くにコンビニ・カフェがあり便利！分煙されており快...,0,1650,1,102,落ち着いた雰囲気の職場環境です！<BR>,八丁堀,6.0,【月収例】25万9875円＋残業代（21日勤務の場合）,0
4,2,0,8.0,宝町,0,0,5.0,1,20020,0,...,◆最寄駅から徒歩圏内！複数路線が利用可能！近くにコンビニ・カフェがあり便利！分煙されており快...,0,1650,1,102,落ち着いた雰囲気の職場環境です！<BR>,八丁堀,6.0,【月収例】25万9875円＋残業代（21日勤務の場合）,0

### テストデータの読み込み

In [11]:
t_x = pd.read_csv("test_x.csv")
t_x.head()

,勤務地 最寄駅3（駅名）,ミドル（40〜）活躍中,オープニングスタッフ,未使用.20,英語力不要,経験者優遇,Wordのスキルを活かす,メモ,派遣スタッフ活躍中,勤務地 最寄駅1（駅からの交通手段）,...,産休育休取得事例あり,仕事写真（下） 写真3 ファイル名,掲載期間 開始日,勤務地 最寄駅3（駅からの交通手段）,未経験OK,ブロックコード1,未使用.19,応募資格,WEB関連のスキルを活かす,対象者設定 年齢下限
0,NaN,1,NaN,NaN,1,1,1,NaN,1,1.0,...,1,NaN,2019/10/24,NaN,1,NaN,NaN,◆未経験者歓迎！<BR>【使用するＯＡスキル】Ｅｘｃｅｌ（関数）・ＰｏｗｅｒＰｏｉｎｔ（文章...,NaN,0
1,NaN,1,NaN,NaN,1,1,1,NaN,1,1.0,...,1,NaN,2019/10/24,NaN,1,NaN,NaN,【短大・専門・高専以上】◆業界経験問いません、ある方歓迎！<BR>※人事事務の経験が必要です...,NaN,0
2,NaN,1,NaN,NaN,1,1,1,NaN,1,1.0,...,1,NaN,2019/10/24,NaN,0,NaN,NaN,【専門・高専卒以上】◆事務経験・簿記３級程度の知識がある方歓迎します。<BR>【使用するＯＡ...,NaN,0
3,NaN,1,NaN,NaN,1,1,1,NaN,0,1.0,...,1,NaN,2019/10/24,NaN,1,NaN,NaN,【大卒以上】◆未経験者歓迎！<BR>【使用するＯＡスキル】Ｅｘｃｅｌ（関数）<BR><BR>...,NaN,0
4,NaN,1,NaN,NaN,1,1,1,NaN,0,1.0,...,1,NaN,2019/10/24,NaN,1,NaN,NaN,＜高卒以上＞◆未経験者歓迎！<BR>※金融機関での就業経験がある方歓迎。<BR>【使用するＯ...,NaN,0

In [12]:
# a_3にカラムを合わせる
columns_list = list(a_3.columns.values)
t_x_1 = t_x[columns_list]
t_x_1.head()

,職場の様子,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,勤務地 最寄駅2（駅名）,大手企業,交通費別途支給,（派遣先）配属先部署 人数,残業月20時間以上,職種コード,1日7時間以下勤務OK,...,お仕事のポイント（仕事PR）,扶養控除内,給与/交通費 給与下限,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし
0,3,0,6.0,二子玉川,0,0,9.0,0,22010,1,...,◆同業務就業の方が在籍で安心！オシャレを楽しめるオフィカジＯＫ♪給湯設備・ホッと一息つける休...,0,1600,1,112,派遣スタッフ活躍中です！<BR>,成城学園前,15.0,【月収例】23万5200円＋残業代（21日勤務の場合）,1
1,3,0,5.0,水天宮前,0,0,11.0,0,22030,1,...,◆２つの駅からアクセス◎！飲食店・コンビニが近くお昼もラクチン！禁煙でクリーンな環境！オフィ...,0,1700,1,102,落ち着いた雰囲気の職場環境です！<BR>,人形町,1.0,【月収例】24万9900円＋残業代（21日勤務の場合）,0
2,3,0,2.0,淡路町,1,0,33.0,0,20020,1,...,◆開始日相談可能です♪複数路線が利用でき便利！休憩室完備の自社ビル！当社スタッフさん就業中！...,0,1800,1,101,ランチに嬉しい社員食堂完備の職場です！<BR>,新御茶ノ水,5.0,【月収例】26万4600円＋残業代（21日勤務の場合）,1
3,2,0,8.0,宝町,0,0,5.0,1,20020,0,...,◆最寄駅から徒歩圏内！複数路線が利用可能！近くにコンビニ・カフェがあり便利！分煙されており快...,0,1650,1,102,落ち着いた雰囲気の職場環境です！<BR>,八丁堀,6.0,【月収例】25万9875円＋残業代（21日勤務の場合）,0
4,2,0,6.0,日本橋,0,0,8.0,0,20020,1,...,◆駅からスグ！飲食店・コンビニが近く何かと便利！禁煙でクリーンな環境！カジュアル×デニムＯＫ...,0,1700,1,102,落ち着いた雰囲気のオフィスです！<BR>,茅場町,7.0,【月収例】24万9900円＋残業代（21日勤務の場合）,1

In [13]:
# object型のみ抽出
a_3_object = a_3.select_dtypes(include=object)
a_3_object.head()

,勤務地 最寄駅2（駅名）,掲載期間 開始日,勤務地 最寄駅2（沿線名）,休日休暇 備考,期間・時間 勤務時間,勤務地 備考,拠点番号,お仕事名,期間・時間 勤務開始日,（派遣先）配属先部署,仕事内容,勤務地 最寄駅1（沿線名）,応募資格,派遣会社のうれしい特典,掲載期間 終了日,お仕事のポイント（仕事PR）,（派遣先）職場の雰囲気,勤務地 最寄駅1（駅名）,給与/交通費 備考
0,NaN,2019/11/27,NaN,※土・日・祝がお休みです。※企業カレンダーあります。,9:30〜16:30 <BR>※残業はほとんどありません。<BR>※休憩は６０分です。,東京都足立区,206東京,ほぼ１６時半終業☆大学＊申請受付ｅｔｃ！未経験スタートＯＫ☆,2020/1/6,事務処理を行う部署,１月スタート！実働短め☆残業ほとんどなし×基本土日祝お休み！朝は少しゆっくりの９：３０出勤で...,東京メトロ千代田線,◆未経験者歓迎！<BR>【使用するＯＡスキル】Ｅｘｃｅｌ（ＶＬＯＯＫ関数）<BR><BR>▼...,"●当社は全国17,000件のお仕事を取り扱っており、毎日100名以上の方が就業を決めています...",2020/11/27,◆駅からスグ！飲食店・コンビニが近く便利！職場環境ＧＯＯＤ◎！当社含む派遣スタッフ多数活躍中...,当社スタッフ活躍中です！<BR>,北千住,【月収例】19万5300円＋残業代（21日勤務の場合）
1,淡路町,2019/11/27,東京メトロ丸ノ内線,※土・日・祝がお休みです。,9:00〜17:00 <BR>※残業はほとんどありません。<BR>※休憩は６０分です。,東京都千代田区,206東京,≪3ヶ月後正社員！≫大手損保会社でコツコツ事務＊社員食堂あり,2019/11/26,経理部,＜大手損保会社＞産休・育休取得実績ありの企業さんです♪ランチに嬉しい社員食堂完備の職場ですよ...,東京メトロ千代田線,【専門・高専卒以上】◆事務経験・簿記３級程度の知識がある方歓迎します。<BR>【使用するＯＡ...,"●当社は全国17,000件のお仕事を取り扱っており、毎日100名以上の方が就業を決めています...",2020/11/27,◆開始日相談可能です♪複数路線が利用でき便利！休憩室完備の自社ビル！当社スタッフさん就業中！...,ランチに嬉しい社員食堂完備の職場です！<BR>,新御茶ノ水,【月収例】26万4600円＋残業代（21日勤務の場合）
2,淡路町,2019/11/27,東京メトロ丸ノ内線,※土・日・祝がお休みです。,9:00〜17:00 <BR>※残業はほとんどありません。<BR>※休憩は６０分です。,東京都千代田区,206東京,≪3ヶ月後正社員！≫大手損保会社でコツコツ事務＊社員食堂あり,2019/11/26,経理部,＜大手損保会社＞産休・育休取得実績ありの企業さんです♪ランチに嬉しい社員食堂完備の職場ですよ...,東京メトロ千代田線,【専門・高専卒以上】◆事務経験・簿記３級程度の知識がある方歓迎します。<BR>【使用するＯＡ...,"●当社は全国17,000件のお仕事を取り扱っており、毎日100名以上の方が就業を決めています...",2020/11/27,◆開始日相談可能です♪複数路線が利用でき便利！休憩室完備の自社ビル！当社スタッフさん就業中！...,ランチに嬉しい社員食堂完備の職場です！<BR>,新御茶ノ水,【月収例】26万4600円＋残業代（21日勤務の場合）
3,宝町,2019/11/27,都営浅草線,※土・日・祝がお休みです。,9:00〜17:30 <BR>※休憩は６０分です。,東京都中央区,206東京,【未経験でも6ヶ月後社員】賞与年4.5ヶ月分＊非営利団体で事務,2019/11/26,企画調整部,安心安定の非営利団体！落ち着いた雰囲気の職場環境です！<BR>【ＯＡ事務】<BR>会議や委員...,東京メトロ日比谷線,【大卒以上】◆未経験者歓迎！<BR>【使用するＯＡスキル】Ｅｘｃｅｌ（関数）<BR><BR>...,"●当社は全国17,000件のお仕事を取り扱っており、毎日100名以上の方が就業を決めています...",2020/11/27,◆最寄駅から徒歩圏内！複数路線が利用可能！近くにコンビニ・カフェがあり便利！分煙されており快...,落ち着いた雰囲気の職場環境です！<BR>,八丁堀,【月収例】25万9875円＋残業代（21日勤務の場合）
4,宝町,2019/11/27,都営浅草線,※土・日・祝がお休みです。,9:00〜17:30 <BR>※休憩は６０分です。,東京都中央区,206東京,【未経験でも6ヶ月後社員】賞与年4.5ヶ月分＊非営利団体で事務,2019/11/26,企画調整部,安心安定の非営利団体！落ち着いた雰囲気の職場環境です！<BR>【ＯＡ事務】<BR>会議や委員...,東京メトロ日比谷線,【大卒以上】◆未経験者歓迎！<BR>【使用するＯＡスキル】Ｅｘｃｅｌ（関数）<BR><BR>...,"●当社は全国17,000件のお仕事を取り扱っており、毎日100名以上の方が就業を決めています...",2020/11/27,◆最寄駅から徒歩圏内！複数路線が利用可能！近くにコンビニ・カフェがあり便利！分煙されており快...,落ち着いた雰囲気の職場環境です！<BR>,八丁堀,【月収例】25万9875円＋残業代（21日勤務の場合）

In [14]:
df_info_a_3_object = pd.DataFrame({"unique count": list(a_3_object.nunique(dropna=False)), "null count": list(a_3_object.isnull().sum())}, index=list(a_3_object.columns.values))
df_info_a_3_object

                unique count  null count
勤務地　最寄駅2（駅名）             840        8367
掲載期間　開始日                   2           0
勤務地　最寄駅2（沿線名）            219        8367
休日休暇　備考                  752           0
期間・時間　勤務時間              3059           0
勤務地　備考                   736           0
拠点番号                      52           0
お仕事名                    9925           0
期間・時間　勤務開始日               94           0
（派遣先）配属先部署              3574           3
仕事内容                   11086           0
勤務地　最寄駅1（沿線名）            351           0
応募資格                    4385           0
派遣会社のうれしい特典               27           0
掲載期間　終了日                   2           0
お仕事のポイント（仕事PR）          9636           0
（派遣先）職場の雰囲気              866           4
勤務地　最寄駅1（駅名）            1729           0
給与/交通費　備考                556        3556

##### エンコーディングするカテゴリ変数の候補メモ

・~~勤務地　最寄駅2（駅名）~~　　→1があるからいらなそう

・~~掲載期間　開始日・終了日~~ 　→二値へ

・~~勤務地　最寄駅2（沿線名）~~  →駅名があるので、なくても良さげ

★休日休暇　備考

★~~期間・時間　勤務時間~~

★勤務地　備考

・~~拠点番号~~  →番号のみを抽出

・~~お仕事名~~  →ほぼ全部違うから無視
    
・~~期間・時間　勤務開始日~~

★~~（派遣先）配属先部署~~

・~~仕事内容~~  →お仕事名と同じく

・~~勤務地　最寄駅1（沿線名）~~　→駅名があるので、なくても良さげ

★~~応募資格~~

★派遣会社のうれしい特典

・~~お仕事のポイント（仕事PR）~~  →お仕事名と同じく

★（派遣先）職場の雰囲気

★勤務地　最寄駅1（駅名）

★給与/交通費　備考

submit_GBDT_Nan_encodingの時よりも少しエンコーディングする変数を減らす  
あまりにも種類が多いもの（ばらばらなもの）のカラムは消去していくことにする

In [15]:
# trainデータに対してNANをなくす
a_4 = a_3.copy()
a_4["休日休暇　備考"] = a_4["休日休暇　備考"].fillna("missing")
# a_4["期間・時間　勤務時間"] = a_4["期間・時間　勤務時間"].fillna("missing")
a_4["勤務地　備考"] = a_4["勤務地　備考"].fillna("missing")
# a_4["（派遣先）配属先部署"] = a_4["（派遣先）配属先部署"].fillna("missing")
# a_4["応募資格"] = a_4["応募資格"].fillna("missing")
a_4["派遣会社のうれしい特典"] = a_4["派遣会社のうれしい特典"].fillna("missing")
a_4["（派遣先）職場の雰囲気"] = a_4["（派遣先）職場の雰囲気"].fillna("missing")
a_4["勤務地　最寄駅1（駅名）"] = a_4["勤務地　最寄駅1（駅名）"].fillna("missing")
a_4["給与/交通費　備考"] = a_4["給与/交通費　備考"].fillna("missing")

In [16]:
# testデータに対してNANをなくす
t_x_2 = t_x_1.copy()
t_x_2["休日休暇　備考"] = t_x_2["休日休暇　備考"].fillna("missing")
# t_x_2["期間・時間　勤務時間"] = t_x_2["期間・時間　勤務時間"].fillna("missing")
t_x_2["勤務地　備考"] = t_x_2["勤務地　備考"].fillna("missing")
# t_x_2["（派遣先）配属先部署"] = t_x_2["（派遣先）配属先部署"].fillna("missing")
# t_x_2["応募資格"] = t_x_2["応募資格"].fillna("missing")
t_x_2["派遣会社のうれしい特典"] = t_x_2["派遣会社のうれしい特典"].fillna("missing")
t_x_2["（派遣先）職場の雰囲気"] = t_x_2["（派遣先）職場の雰囲気"].fillna("missing")
t_x_2["勤務地　最寄駅1（駅名）"] = t_x_2["勤務地　最寄駅1（駅名）"].fillna("missing")
t_x_2["給与/交通費　備考"] = t_x_2["給与/交通費　備考"].fillna("missing")

In [17]:
# "休日休暇　備考","期間・時間　勤務時間","勤務地　備考","（派遣先）配属先部署","応募資格","派遣会社のうれしい特典","（派遣先）職場の雰囲気","勤務地　最寄駅1（駅名）","給与/交通費　備考"
# ,,,,,,,

In [18]:
from sklearn.preprocessing import LabelEncoder

a_5 = a_4.copy()
t_x_3 = t_x_2.copy()
le1 = LabelEncoder()
# a_5とt_x_3においてラベル付け
le1.fit(pd.concat([a_5["休日休暇　備考"], t_x_3["休日休暇　備考"]], sort=True))
a_5["休日休暇　備考"] = le1.transform(a_5["休日休暇　備考"])
t_x_3["休日休暇　備考"] = le1.transform(t_x_3["休日休暇　備考"])

In [19]:
# le2 = LabelEncoder()
# le2.fit(pd.concat([a_5["期間・時間　勤務時間"], t_x_3["期間・時間　勤務時間"]], sort=True))
# a_5["期間・時間　勤務時間"] = le2.transform(a_5["期間・時間　勤務時間"])
# t_x_3["期間・時間　勤務時間"] = le2.transform(t_x_3["期間・時間　勤務時間"])

le3 = LabelEncoder()
le3.fit(pd.concat([a_5["勤務地　備考"], t_x_3["勤務地　備考"]], sort=True))
a_5["勤務地　備考"] = le3.transform(a_5["勤務地　備考"])
t_x_3["勤務地　備考"] = le3.transform(t_x_3["勤務地　備考"])

# le4 = LabelEncoder()
# le4.fit(pd.concat([a_5["（派遣先）配属先部署"], t_x_3["（派遣先）配属先部署"]], sort=True))
# a_5["（派遣先）配属先部署"] = le4.transform(a_5["（派遣先）配属先部署"])
# t_x_3["（派遣先）配属先部署"] = le4.transform(t_x_3["（派遣先）配属先部署"])

# le5 = LabelEncoder()
# le5.fit(pd.concat([a_5["応募資格"], t_x_3["応募資格"]], sort=True))
# a_5["応募資格"] = le5.transform(a_5["応募資格"])
# t_x_3["応募資格"] = le5.transform(t_x_3["応募資格"])

le6 = LabelEncoder()
le6.fit(pd.concat([a_5["派遣会社のうれしい特典"], t_x_3["派遣会社のうれしい特典"]], sort=True))
a_5["派遣会社のうれしい特典"] = le6.transform(a_5["派遣会社のうれしい特典"])
t_x_3["派遣会社のうれしい特典"] = le6.transform(t_x_3["派遣会社のうれしい特典"])

le7 = LabelEncoder()
le7.fit(pd.concat([a_5["（派遣先）職場の雰囲気"], t_x_3["（派遣先）職場の雰囲気"]], sort=True))
a_5["（派遣先）職場の雰囲気"] = le7.transform(a_5["（派遣先）職場の雰囲気"])
t_x_3["（派遣先）職場の雰囲気"] = le7.transform(t_x_3["（派遣先）職場の雰囲気"])

le8 = LabelEncoder()
le8.fit(pd.concat([a_5["勤務地　最寄駅1（駅名）"], t_x_3["勤務地　最寄駅1（駅名）"]], sort=True))
a_5["勤務地　最寄駅1（駅名）"] = le8.transform(a_5["勤務地　最寄駅1（駅名）"])
t_x_3["勤務地　最寄駅1（駅名）"] = le8.transform(t_x_3["勤務地　最寄駅1（駅名）"])

le9 = LabelEncoder()
le9.fit(pd.concat([a_5["給与/交通費　備考"], t_x_3["給与/交通費　備考"]], sort=True))
a_5["給与/交通費　備考"] = le9.transform(a_5["給与/交通費　備考"])
t_x_3["給与/交通費　備考"] = le9.transform(t_x_3["給与/交通費　備考"])

In [20]:
# trainデータに対して使わないカラムの削除
a_5 = a_5.drop(["勤務地　最寄駅2（駅名）", "勤務地　最寄駅2（沿線名）", "お仕事名", "期間・時間　勤務開始日", "仕事内容", "勤務地　最寄駅1（沿線名）", "お仕事のポイント（仕事PR）", "掲載期間　終了日", "期間・時間　勤務時間", "（派遣先）配属先部署", "応募資格"], axis=1)
a_5.head()

,職場の様子,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,大手企業,交通費別途支給,（派遣先）配属先部署 人数,残業月20時間以上,職種コード,1日7時間以下勤務OK,短時間勤務OK(1日4h以内),...,休日休暇(金曜日),扶養控除内,給与/交通費 給与下限,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし
0,3,0,6.0,0,0,12.0,0,22010,1,0,...,0,0,1550,1,121,477,325,NaN,186,1
1,3,0,2.0,1,0,33.0,0,20020,1,0,...,0,0,1800,1,101,185,832,5.0,424,1
2,3,0,2.0,1,0,33.0,0,20020,1,0,...,0,0,1800,1,101,185,832,5.0,424,1
3,2,0,8.0,0,0,5.0,1,20020,0,0,...,0,0,1650,1,102,777,261,6.0,411,0
4,2,0,8.0,0,0,5.0,1,20020,0,0,...,0,0,1650,1,102,777,261,6.0,411,0

In [21]:
# testデータに対して使わないカラムの削除
t_x_3 = t_x_3.drop(["勤務地　最寄駅2（駅名）", "勤務地　最寄駅2（沿線名）", "お仕事名", "期間・時間　勤務開始日", "仕事内容", "勤務地　最寄駅1（沿線名）", "お仕事のポイント（仕事PR）", "掲載期間　終了日", "期間・時間　勤務時間", "（派遣先）配属先部署", "応募資格"], axis=1)
t_x_3.head()

,職場の様子,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,大手企業,交通費別途支給,（派遣先）配属先部署 人数,残業月20時間以上,職種コード,1日7時間以下勤務OK,短時間勤務OK(1日4h以内),...,休日休暇(金曜日),扶養控除内,給与/交通費 給与下限,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし
0,3,0,6.0,0,0,9.0,0,22010,1,0,...,0,0,1600,1,112,608,773,15.0,325,1
1,3,0,5.0,0,0,11.0,0,22030,1,0,...,0,0,1700,1,102,777,205,1.0,373,0
2,3,0,2.0,1,0,33.0,0,20020,1,0,...,0,0,1800,1,101,185,832,5.0,424,1
3,2,0,8.0,0,0,5.0,1,20020,0,0,...,0,0,1650,1,102,777,261,6.0,411,0
4,2,0,6.0,0,0,8.0,0,20020,1,0,...,0,0,1700,1,102,773,1401,7.0,373,1

In [22]:
# 掲載開始日を０，１にエンコード
# trainデータ
day_mapping = {"2019/11/27": 0, "2019/9/25": 1}
a_5["掲載期間　開始日"] = a_5['掲載期間　開始日'].map(day_mapping)

In [23]:
# testデータ
t_x_3 = t_x_3.replace('2019/10/24', 3)
t_x_3.head()

,職場の様子,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,大手企業,交通費別途支給,（派遣先）配属先部署 人数,残業月20時間以上,職種コード,1日7時間以下勤務OK,短時間勤務OK(1日4h以内),...,休日休暇(金曜日),扶養控除内,給与/交通費 給与下限,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし
0,3,0,6.0,0,0,9.0,0,22010,1,0,...,0,0,1600,1,112,608,773,15.0,325,1
1,3,0,5.0,0,0,11.0,0,22030,1,0,...,0,0,1700,1,102,777,205,1.0,373,0
2,3,0,2.0,1,0,33.0,0,20020,1,0,...,0,0,1800,1,101,185,832,5.0,424,1
3,2,0,8.0,0,0,5.0,1,20020,0,0,...,0,0,1650,1,102,777,261,6.0,411,0
4,2,0,6.0,0,0,8.0,0,20020,1,0,...,0,0,1700,1,102,773,1401,7.0,373,1

In [24]:
# trainデータの拠点番号
func = lambda x: int(x[:3])
a_5["拠点番号"] = a_5["拠点番号"].map(func)
a_5.head()

,職場の様子,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,大手企業,交通費別途支給,（派遣先）配属先部署 人数,残業月20時間以上,職種コード,1日7時間以下勤務OK,短時間勤務OK(1日4h以内),...,休日休暇(金曜日),扶養控除内,給与/交通費 給与下限,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし
0,3,0,6.0,0,0,12.0,0,22010,1,0,...,0,0,1550,1,121,477,325,NaN,186,1
1,3,0,2.0,1,0,33.0,0,20020,1,0,...,0,0,1800,1,101,185,832,5.0,424,1
2,3,0,2.0,1,0,33.0,0,20020,1,0,...,0,0,1800,1,101,185,832,5.0,424,1
3,2,0,8.0,0,0,5.0,1,20020,0,0,...,0,0,1650,1,102,777,261,6.0,411,0
4,2,0,8.0,0,0,5.0,1,20020,0,0,...,0,0,1650,1,102,777,261,6.0,411,0

In [25]:
# testデータの拠点番号
# trainデータの拠点番号
func = lambda x: int(x[:3])
t_x_3["拠点番号"] = t_x_3["拠点番号"].map(func)
t_x_3.head()

,職場の様子,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,大手企業,交通費別途支給,（派遣先）配属先部署 人数,残業月20時間以上,職種コード,1日7時間以下勤務OK,短時間勤務OK(1日4h以内),...,休日休暇(金曜日),扶養控除内,給与/交通費 給与下限,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし
0,3,0,6.0,0,0,9.0,0,22010,1,0,...,0,0,1600,1,112,608,773,15.0,325,1
1,3,0,5.0,0,0,11.0,0,22030,1,0,...,0,0,1700,1,102,777,205,1.0,373,0
2,3,0,2.0,1,0,33.0,0,20020,1,0,...,0,0,1800,1,101,185,832,5.0,424,1
3,2,0,8.0,0,0,5.0,1,20020,0,0,...,0,0,1650,1,102,777,261,6.0,411,0
4,2,0,6.0,0,0,8.0,0,20020,1,0,...,0,0,1700,1,102,773,1401,7.0,373,1

In [26]:
# # NaNの数を特徴量に追加
# t_x_3['number_of_NAN'] = t_x_3.isna().sum(axis=1).astype(np.int8)

In [27]:
# 予測用データ
submit_x = t_x_3

In [28]:
work_number = submit_x["お仕事No."]
submit_x_test = np.array(submit_x.drop(["お仕事No."], axis=1))
submit_x_test.shape

(3391, 74)

In [29]:
pd.options.display.max_columns = None

In [30]:
a_5.head()

,職場の様子,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,大手企業,交通費別途支給,（派遣先）配属先部署 人数,残業月20時間以上,職種コード,1日7時間以下勤務OK,短時間勤務OK(1日4h以内),駅から徒歩5分以内,学校・公的機関（官公庁）,土日祝のみ勤務,掲載期間 開始日,Wordのスキルを活かす,勤務地 最寄駅1（分）,お仕事No.,派遣スタッフ活躍中,大量募集,Accessのスキルを活かす,休日休暇(火曜日),平日休みあり,勤務地 最寄駅2（駅からの交通手段）,休日休暇 備考,フラグオプション選択,期間・時間 勤務期間,派遣形態,週2・3日OK,勤務先公開,Excelのスキルを活かす,16時前退社OK,正社員登用あり,残業月20時間未満,勤務地 備考,英語力不要,拠点番号,休日休暇(日曜日),社員食堂あり,10時以降出社OK,英語以外の語学力を活かす,休日休暇(祝日),外資系企業,服装自由,PowerPointのスキルを活かす,（派遣先）配属先部署 男女比 女,休日休暇(土曜日),休日休暇(木曜日),（派遣先）配属先部署 平均年齢,英語力を活かす,会社概要 業界コード,勤務地 都道府県コード,PCスキル不要,車通勤OK,制服あり,休日休暇(水曜日),仕事の仕方,勤務地 最寄駅1（駅からの交通手段）,紹介予定派遣,シフト勤務,経験者優遇,週4日勤務,未経験OK,派遣会社のうれしい特典,土日祝休み,給与/交通費 交通費,休日休暇(金曜日),扶養控除内,給与/交通費 給与下限,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし
0,3,0,6.0,0,0,12.0,0,22010,1,0,1,1,0,0,1,3.0,2203566799,1,0,0,0,0,NaN,138,1,5,0,0,0,1,0,0,0,453,1,206,1,1,0,0,1,0,1,0,4.0,1,0,45.0,0,30000,13,0,0,0,0,2,1.0,0,0,1,0,1,0,1,3,0,0,1550,1,121,477,325,NaN,186,1
1,3,0,2.0,1,0,33.0,0,20020,1,0,1,0,0,0,1,1.0,2203546900,1,0,0,0,0,1.0,134,3,5,1,0,0,1,0,1,0,416,1,206,1,1,0,0,1,0,1,0,8.0,1,0,45.0,0,28000,13,0,0,0,0,1,1.0,1,0,1,0,0,0,1,3,0,0,1800,1,101,185,832,5.0,424,1
2,3,0,2.0,1,0,33.0,0,20020,1,0,1,0,0,0,1,1.0,2203546900,1,0,0,0,0,1.0,134,3,5,1,0,0,1,0,1,0,416,1,206,1,1,0,0,1,0,1,0,8.0,1,0,45.0,0,28000,13,0,0,0,0,1,1.0,1,0,1,0,0,0,1,3,0,0,1800,1,101,185,832,5.0,424,1
3,2,0,8.0,0,0,5.0,1,20020,0,0,0,1,0,0,1,6.0,2203545344,0,0,0,0,0,1.0,134,3,5,1,0,0,1,0,1,0,412,1,206,1,0,0,0,1,0,1,0,2.0,1,0,42.0,0,30000,13,0,0,0,0,1,1.0,1,0,1,0,1,0,1,3,0,0,1650,1,102,777,261,6.0,411,0
4,2,0,8.0,0,0,5.0,1,20020,0,0,0,1,0,0,1,6.0,2203545344,0,0,0,0,0,1.0,134,3,5,1,0,0,1,0,1,0,412,1,206,1,0,0,0,1,0,1,0,2.0,1,0,42.0,0,30000,13,0,0,0,0,1,1.0,1,0,1,0,1,0,1,3,0,0,1650,1,102,777,261,6.0,411,0

In [31]:
a_5.describe()

,職場の様子,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,大手企業,交通費別途支給,（派遣先）配属先部署 人数,残業月20時間以上,職種コード,1日7時間以下勤務OK,短時間勤務OK(1日4h以内),駅から徒歩5分以内,学校・公的機関（官公庁）,土日祝のみ勤務,掲載期間 開始日,Wordのスキルを活かす,勤務地 最寄駅1（分）,お仕事No.,派遣スタッフ活躍中,大量募集,Accessのスキルを活かす,休日休暇(火曜日),平日休みあり,勤務地 最寄駅2（駅からの交通手段）,休日休暇 備考,フラグオプション選択,期間・時間 勤務期間,派遣形態,週2・3日OK,勤務先公開,Excelのスキルを活かす,16時前退社OK,正社員登用あり,残業月20時間未満,勤務地 備考,英語力不要,拠点番号,休日休暇(日曜日),社員食堂あり,10時以降出社OK,英語以外の語学力を活かす,休日休暇(祝日),外資系企業,服装自由,PowerPointのスキルを活かす,（派遣先）配属先部署 男女比 女,休日休暇(土曜日),休日休暇(木曜日),（派遣先）配属先部署 平均年齢,英語力を活かす,会社概要 業界コード,勤務地 都道府県コード,PCスキル不要,車通勤OK,制服あり,休日休暇(水曜日),仕事の仕方,勤務地 最寄駅1（駅からの交通手段）,紹介予定派遣,シフト勤務,経験者優遇,週4日勤務,未経験OK,派遣会社のうれしい特典,土日祝休み,給与/交通費 交通費,休日休暇(金曜日),扶養控除内,給与/交通費 給与下限,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし
count,15853.000000,15853.000000,13801.000000,15853.000000,15853.000000,13814.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,14929.000000,1.585300e+04,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,7359.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,13801.000000,15853.000000,15853.000000,11133.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,14929.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,7359.000000,15853.000000,15853.000000
mean,2.946319,0.006813,4.997464,0.237242,0.218129,14.174461,0.064972,20637.698227,0.277802,0.010219,0.553018,0.093989,0.000252,0.503690,0.956980,6.568022,3.129635e+09,0.543872,0.002397,0.036965,0.043903,0.063016,1.126512,177.439097,1.098278,4.914464,0.172964,0.036965,0.043777,0.989907,0.070523,0.114868,0.205450,390.989213,0.923989,273.277550,0.954015,0.186715,0.132530,0.002019,0.936100,0.038037,0.787485,0.161294,5.002536,0.940074,0.035009,39.388215,0.074434,25923.500788,17.095187,0.009777,0.181732,0.173469,0.046553,2.650855,1.195793,0.172964,0.053302,0.990412,0.029458,0.877184,0.500221,0.936984,2.781871,0.009903,0.011670,1469.690279,0.991674,137.071848,434.118211,848.275027,7.621008,243.595282,0.729578
std,0.306926,0.082259,2.796697,0.425405,0.412989,23.165115,0.246484,2598.874377,0.447930,0.100574,0.497197,0.291822,0.015883,0.500002,0.202909,4.495272,1.486560e+09,0.498087,0.048902,0.188681,0.204887,0.243000,0.433263,144.796381,1.036030,0.404680,0.378228,0.188681,0.204605,0.099957,0.256034,0.318872,0.404043,156.520767,0.265024,133.752132,0.209459,0.389695,0.339077,0.044884,0.244582,0.191292,0.409100,0.367814,2.796697,0.237356,0.183809,5.629523,0.262484,3163.694945,8.647378,0.098399,0.385636,0.378664,0.210685,1.600303,0.568269,0.378228,0.224643,0.097451,0.169092,0.328236,2.772577,0.243000,0.412989,0.099025,0.107398,244.447800,0.090872,55.513015,234.841303,494.809165,4.577798,176.965509,0.444192
min,2.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,20020.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.103518e+09,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,101.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,21000.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,800.000000,0.000000,101.000000,0.000000,0.000000,1.000000,0.000000,0.000000
25%,3.000000,0.000000,3.000000,0.000000,0.000000,5.000000,0.000000,20020.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,3.000000,2.203538e+09,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,134.000000,0.000000,5.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,359.000000,1.000000,206.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,3.000000,1.000000,0.000000,35.000000,0.000000,22000.000000,13.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,3.000000,0.000000,0.000000,1300.000000,1.000000,103.000000,232.000000,430.000000,5.000000,72.000000,0.000000
50%,3.000000,0.000000,5.000000,0.000000,0.000000,8.000000,0.000000,20030.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,1.000000,5.000000,2.203569e+09,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,134.000000,1.000000,5.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,422.000000,1.000000,206.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,5.000000,1.000000,0.000000,40.000000,0.000000,27000.000000,13.000000,0.000000,0.000000,0.000000,0.000000,2.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,3.000000,0.000000,0.000000,1500.000000,1.000000,109.000000,404.000000,882.000000,7.000000,269.000000,1.000000
75%,3.000000,0.000000,7.000000,0.000000,0.000000,15.000000,0.000000,20710.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000,1.000000,9.000000,3.703541e+09,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,138.000000,1.000000,5.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,441.000000,1.000000,308.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,7.000000,1.000000,0.000000,43.000000,0.000000,29000.000000,22.000000,0.000000,0.000000,0.000000,0.000000,4.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,3.000000,0.000000,0.000000,1650.000000,1.000000,201.000000,665.000000,1228.000000,10.000000,409.000000,1.000000
max,4.000000,1.000000,10.000000,1.000000,1.000000,574.000000,1.000000,80310.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,40.000000,8.403569e+09,1.000000,1.000000,1.000000,1.000000,1.000000,3.000000,817.000000,5.000000,5.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,735.000000,1.000000,709.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,10.000000,1.000000,1.000000,73.000000,1.000000,30000.000000,47.000000,1.000000,1.000000,1.000000,1.000000,5.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,26.000000,1.000000,3.000000,1.000000,1.000000,2850.000000,1.000000,631.000000,936.000000,1748.000000,46.000000,575.000000,1.000000

In [32]:
df_info_a_5 = pd.DataFrame({"unique count": list(a_5.nunique(dropna=False))}, index=list(a_5.columns.values))
df_info_a_5.T

,職場の様子,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,大手企業,交通費別途支給,（派遣先）配属先部署 人数,残業月20時間以上,職種コード,1日7時間以下勤務OK,短時間勤務OK(1日4h以内),駅から徒歩5分以内,学校・公的機関（官公庁）,土日祝のみ勤務,掲載期間 開始日,Wordのスキルを活かす,勤務地 最寄駅1（分）,お仕事No.,派遣スタッフ活躍中,大量募集,Accessのスキルを活かす,休日休暇(火曜日),平日休みあり,勤務地 最寄駅2（駅からの交通手段）,休日休暇 備考,フラグオプション選択,期間・時間 勤務期間,派遣形態,週2・3日OK,勤務先公開,Excelのスキルを活かす,16時前退社OK,正社員登用あり,残業月20時間未満,勤務地 備考,英語力不要,拠点番号,休日休暇(日曜日),社員食堂あり,10時以降出社OK,英語以外の語学力を活かす,休日休暇(祝日),外資系企業,服装自由,PowerPointのスキルを活かす,（派遣先）配属先部署 男女比 女,休日休暇(土曜日),休日休暇(木曜日),（派遣先）配属先部署 平均年齢,英語力を活かす,会社概要 業界コード,勤務地 都道府県コード,PCスキル不要,車通勤OK,制服あり,休日休暇(水曜日),仕事の仕方,勤務地 最寄駅1（駅からの交通手段）,紹介予定派遣,シフト勤務,経験者優遇,週4日勤務,未経験OK,派遣会社のうれしい特典,土日祝休み,給与/交通費 交通費,休日休暇(金曜日),扶養控除内,給与/交通費 給与下限,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし
unique count,3,2,12,2,2,112,2,14,2,2,2,2,2,2,2,31,9671,2,2,2,2,2,4,752,5,2,2,2,2,2,2,2,2,736,2,51,2,2,2,2,2,2,2,2,12,2,2,51,2,13,47,2,2,2,2,5,4,2,2,2,2,2,27,2,2,2,2,136,2,151,866,1729,33,556,2

In [54]:
# ほとんど同じ値のカラムを抽出
big_top_value_cols = [col for col in a_5.columns if a_5[col].value_counts(dropna=False, normalize=True).values[0] > 0.9]
# ほとんど同じ値のカラムを削除
a_5.drop(big_top_value_cols, axis=1, inplace=True)
big_top_value_cols

['職場の様子',
 '休日休暇(月曜日)',
 '残業月20時間以上',
 '短時間勤務OK(1日4h以内)',
 '学校・公的機関（官公庁）',
 '土日祝のみ勤務',
 'Wordのスキルを活かす',
 '大量募集',
 'Accessのスキルを活かす',
 '休日休暇(火曜日)',
 '平日休みあり',
 '期間・時間\u3000勤務期間',
 '週2・3日OK',
 '勤務先公開',
 'Excelのスキルを活かす',
 '16時前退社OK',
 '英語力不要',
 '休日休暇(日曜日)',
 '英語以外の語学力を活かす',
 '休日休暇(祝日)',
 '外資系企業',
 '休日休暇(土曜日)',
 '休日休暇(木曜日)',
 '英語力を活かす',
 'PCスキル不要',
 '休日休暇(水曜日)',
 'シフト勤務',
 '経験者優遇',
 '週4日勤務',
 '派遣会社のうれしい特典',
 '土日祝休み',
 '休日休暇(金曜日)',
 '扶養控除内',
 'オフィスが禁煙・分煙']

In [55]:
# 前処理後データ
application_after = a_5
application_after.head()

,（派遣先）配属先部署 男女比 男,大手企業,交通費別途支給,（派遣先）配属先部署 人数,職種コード,1日7時間以下勤務OK,駅から徒歩5分以内,掲載期間 開始日,勤務地 最寄駅1（分）,お仕事No.,派遣スタッフ活躍中,勤務地 最寄駅2（駅からの交通手段）,休日休暇 備考,フラグオプション選択,派遣形態,正社員登用あり,残業月20時間未満,勤務地 備考,拠点番号,社員食堂あり,10時以降出社OK,服装自由,PowerPointのスキルを活かす,（派遣先）配属先部署 男女比 女,（派遣先）配属先部署 平均年齢,会社概要 業界コード,勤務地 都道府県コード,車通勤OK,制服あり,仕事の仕方,勤務地 最寄駅1（駅からの交通手段）,紹介予定派遣,未経験OK,給与/交通費 交通費,給与/交通費 給与下限,勤務地 市区町村コード,（派遣先）職場の雰囲気,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし
0,6.0,0,0,12.0,22010,1,1,0,3.0,2203566799,1,NaN,138,1,0,0,0,453,206,1,0,1,0,4.0,45.0,30000,13,0,0,2,1.0,0,1,3,1550,121,477,325,NaN,186,1
1,2.0,1,0,33.0,20020,1,1,0,1.0,2203546900,1,1.0,134,3,1,1,0,416,206,1,0,1,0,8.0,45.0,28000,13,0,0,1,1.0,1,0,3,1800,101,185,832,5.0,424,1
2,2.0,1,0,33.0,20020,1,1,0,1.0,2203546900,1,1.0,134,3,1,1,0,416,206,1,0,1,0,8.0,45.0,28000,13,0,0,1,1.0,1,0,3,1800,101,185,832,5.0,424,1
3,8.0,0,0,5.0,20020,0,0,0,6.0,2203545344,0,1.0,134,3,1,1,0,412,206,0,0,1,0,2.0,42.0,30000,13,0,0,1,1.0,1,1,3,1650,102,777,261,6.0,411,0
4,8.0,0,0,5.0,20020,0,0,0,6.0,2203545344,0,1.0,134,3,1,1,0,412,206,0,0,1,0,2.0,42.0,30000,13,0,0,1,1.0,1,1,3,1650,102,777,261,6.0,411,0

In [56]:
# 予測用データも同様に削除
t_x_3.drop(big_top_value_cols, axis=1, inplace=True)
submit_x = t_x_3

In [57]:
work_number = submit_x["お仕事No."]
submit_x_test = np.array(submit_x.drop(["お仕事No."], axis=1))
submit_x_test.shape

(3391, 40)

### yの読み込み

In [35]:
df_y = pd.read_csv("train_y.csv")
df_y.head()

       お仕事No.    応募数 合計
0  2203566799  1.945910
1  2203546900  3.951244
2  2203546900  3.295837
3  2203545344  3.970292
4  2203545344  3.784190

In [36]:
len(df_y)

15853

# 回帰問題

In [58]:
y = df_y["応募数 合計"]
X = application_after.drop(["お仕事No."], axis=1)

In [59]:
y_array = np.array(y)
X_array = np.array(X)

In [60]:
print("y_array: ", y_array.shape)
print("X_array: ", X_array.shape)

y_array:  (15853,)
X_array:  (15853, 40)

In [61]:
# train/testに分割する
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_array, y_array, test_size=0.4, random_state=0)

In [62]:
print("X_train: ", X_train.shape)
print("y_train: ", y_train.shape)
print("X_test: ", X_test.shape)
print("y_test: ", y_test.shape)

X_train:  (9511, 40)
y_train:  (9511,)
X_test:  (6342, 40)
y_test:  (6342,)

# GBDT

In [42]:
import xgboost as xgb
from sklearn.metrics import log_loss

In [63]:
# 特徴量と目的変数をxboostのデータ構造に変換する
dtrain = xgb.DMatrix(X_train, label=y_train)
dvalid = xgb.DMatrix(X_test, label=y_test)
dtest = xgb.DMatrix(submit_x_test)

In [66]:
# ハイパーパラメータの設定
param = {"object": "reg:squarederror", "silent": 1, "random_state": 71}
num_round = 58

In [67]:
# 学習の実行
# バリデーションデータもモデルに渡し、学習の進行とともにスコアがどう変わるかモニタリングする
# watchlistには学習データおよびバリデーションデータをセットする
watchlist = [(dtrain, "train"), (dvalid, "eval")]
model = xgb.train(param, dtrain, num_round, evals=watchlist)

[0]	train-rmse:0.738811	eval-rmse:0.719684
[1]	train-rmse:0.699004	eval-rmse:0.688735
[2]	train-rmse:0.676604	eval-rmse:0.673129
[3]	train-rmse:0.659333	eval-rmse:0.664088
[4]	train-rmse:0.642019	eval-rmse:0.654079
[5]	train-rmse:0.630257	eval-rmse:0.647592
[6]	train-rmse:0.619573	eval-rmse:0.643214
[7]	train-rmse:0.609011	eval-rmse:0.639267
[8]	train-rmse:0.598875	eval-rmse:0.635235
[9]	train-rmse:0.586398	eval-rmse:0.631955
[10]	train-rmse:0.580381	eval-rmse:0.630581
[11]	train-rmse:0.571328	eval-rmse:0.628265
[12]	train-rmse:0.562824	eval-rmse:0.626792
[13]	train-rmse:0.553927	eval-rmse:0.624617
[14]	train-rmse:0.5505	eval-rmse:0.624276
[15]	train-rmse:0.544637	eval-rmse:0.623211
[16]	train-rmse:0.540505	eval-rmse:0.623081
[17]	train-rmse:0.536484	eval-rmse:0.621628
[18]	train-rmse:0.531422	eval-rmse:0.619904
[19]	train-rmse:0.524292	eval-rmse:0.618527
[20]	train-rmse:0.522185	eval-rmse:0.618191
[21]	train-rmse:0.521506	eval-rmse:0.618135
[22]	train-rmse:0.517389	eval-rmse:0.617983
[23]	train-rmse:0.515663	eval-rmse:0.617868
[24]	train-rmse:0.513636	eval-rmse:0.617837
[25]	train-rmse:0.510923	eval-rmse:0.617577
[26]	train-rmse:0.508336	eval-rmse:0.617391
[27]	train-rmse:0.507134	eval-rmse:0.617401
[28]	train-rmse:0.505153	eval-rmse:0.616774
[29]	train-rmse:0.499282	eval-rmse:0.614742
[30]	train-rmse:0.495071	eval-rmse:0.613982
[31]	train-rmse:0.49324	eval-rmse:0.613753
[32]	train-rmse:0.491274	eval-rmse:0.613821
[33]	train-rmse:0.486256	eval-rmse:0.613708
[34]	train-rmse:0.483639	eval-rmse:0.613553
[35]	train-rmse:0.481951	eval-rmse:0.613766
[36]	train-rmse:0.47896	eval-rmse:0.612861
[37]	train-rmse:0.478456	eval-rmse:0.612867
[38]	train-rmse:0.476796	eval-rmse:0.612839
[39]	train-rmse:0.473557	eval-rmse:0.612437
[40]	train-rmse:0.469317	eval-rmse:0.612041
[41]	train-rmse:0.46802	eval-rmse:0.612109
[42]	train-rmse:0.465324	eval-rmse:0.611377
[43]	train-rmse:0.464353	eval-rmse:0.611329
[44]	train-rmse:0.462485	eval-rmse:0.611475
[45]	train-rmse:0.460287	eval-rmse:0.611228
[46]	train-rmse:0.457733	eval-rmse:0.611716
[47]	train-rmse:0.453754	eval-rmse:0.611449
[48]	train-rmse:0.452195	eval-rmse:0.611502
[49]	train-rmse:0.449077	eval-rmse:0.611291
[50]	train-rmse:0.448436	eval-rmse:0.611229
[51]	train-rmse:0.445931	eval-rmse:0.610931
[52]	train-rmse:0.442773	eval-rmse:0.611164
[53]	train-rmse:0.439969	eval-rmse:0.610778
[54]	train-rmse:0.438107	eval-rmse:0.61074
[55]	train-rmse:0.436048	eval-rmse:0.610663
[56]	train-rmse:0.433692	eval-rmse:0.610786
[57]	train-rmse:0.431571	eval-rmse:0.610638

In [68]:
# バリデーションデータでのスコアの確認
va_pred = model.predict(dvalid)
# 負の値は0へ
va_pred_0 = [0 if i <= 0 else i for i in va_pred]
va_pred_0

[0.7063212,
 0.85873014,
 0.29359877,
 0.6308209,
 0.8472828,
 0.72635645,
 0.25386715,
 0.12549146,
 0.13000186,
 0,
 0.99621075,
 0.023193086,
 0.5760732,
 0.48909205,
 1.4709457,
 1.8274282,
 0.94515073,
 0.46332657,
 0.21245739,
 0,
 1.5261635,
 0.65002203,
 0.15925299,
 0.39044,
 1.7826486,
 0.15240455,
 0.35857445,
 0.42482743,
 1.0988066,
 0.1432401,
 0.31873888,
 1.5820568,
 0,
 1.0105175,
 0.55179775,
 0.33234814,
 0.7817117,
 0.582351,
 0.10108635,
 0.45992988,
 0.043171242,
 0.13994174,
 0.18965557,
 0.6030785,
 1.2143712,
 0.23499486,
 0.19681941,
 0.5331275,
 0,
 0.19576538,
 0.59697294,
 0.245984,
 0.23661761,
 0.44200072,
 1.0763083,
 0.5857887,
 0.6169277,
 0.22865584,
 0.111174494,
 0.92642933,
 0.9287075,
 0.26870564,
 0,
 0.06881415,
 0.70345074,
 1.5252581,
 1.0847311,
 0,
 0.051938914,
 0.79139745,
 0.52996606,
 0,
 0.3315033,
 0.10330212,
 0.6876305,
 0.4987554,
 0,
 0.1326438,
 0.2714066,
 0.5273897,
 0.7189772,
 0.16753142,
 0.1651897,
 0.9479623,
 0.3502447,
 0.96924394,
 0.15678434,
 0.60157096,
 1.3918867,
 0.19175752,
 0,
 0.18690749,
 0.66850156,
 1.3813335,
 0.26673463,
 0.056746114,
 0.42831895,
 0.88825625,
 0.4757877,
 0,
 0.2542401,
 0.21565723,
 0.05912499,
 0.39674446,
 2.3992672,
 1.0804001,
 0.73074776,
 0.10281646,
 1.3832772,
 0.3671676,
 0.057185967,
 0.42507333,
 0.43514886,
 1.1215574,
 2.1283453,
 0.61536634,
 0.85895365,
 0.29958618,
 0.14677271,
 0.7579745,
 0.48505902,
 0.624832,
 0.10908866,
 0.41628227,
 0.5069863,
 1.8687147,
 0.11798805,
 1.8805522,
 2.3898447,
 0.7593407,
 0.16730988,
 0.0051897154,
 0.31968996,
 1.3947119,
 0.5300716,
 0.37043843,
 0.40364245,
 1.2372636,
 1.6522441,
 0.6506219,
 0.24983048,
 0.3504712,
 0.84397626,
 1.0117413,
 0.120192274,
 0.17525806,
 0.7700946,
 0.31094155,
 0.5080159,
 0,
 0.48262638,
 0.3723473,
 2.2747474,
 0.022874013,
 0.4492293,
 1.9118438,
 0.45668224,
 0.12679167,
 1.0573444,
 0.24456632,
 0.2123182,
 0.3425967,
 0.4392832,
 1.5831659,
 0.49628517,
 0.31597045,
 0,
 1.0023091,
 0.28097323,
 0.2924539,
 0.5412482,
 0.22466587,
 0.6817841,
 0.22987902,
 0.17003532,
 0,
 3.0624683,
 0.1691028,
 0.85820717,
 0.5542144,
 2.693823,
 0.23888387,
 0.34699324,
 0.1834634,
 0,
 0.6337107,
 0.027547244,
 0.51835454,
 0.432301,
 0.24900337,
 0.21868584,
 0.082730725,
 1.0493246,
 0.58953965,
 0.12038084,
 0.648771,
 0.17559974,
 0.058528744,
 0.03394556,
 1.3711451,
 0.03399798,
 0.1010555,
 2.579767,
 0.9491116,
 0.7428905,
 0.35277638,
 0.6422691,
 1.3894871,
 0,
 0.32324734,
 0.09749954,
 0.14100316,
 0.19184728,
 0.07977533,
 0.17697203,
 0.5131226,
 0.30969888,
 1.8041457,
 1.0181209,
 0.85564435,
 1.8906513,
 0.0016188323,
 0.74777174,
 2.0226126,
 0.03501282,
 1.0703148,
 0.40027177,
 0.24514651,
 0.32292897,
 0.30152392,
 0.2273334,
 0.008358354,
 0.48344642,
 0,
 1.7606605,
 0.42885423,
 0.56025565,
 1.4087421,
 0.41406694,
 0.7885825,
 0,
 0.7045971,
 0.61495155,
 0.11087247,
 1.6070769,
 1.0679036,
 0.75673217,
 0.37717012,
 0,
 2.3971872,
 0.48359266,
 0.3883547,
 0.90023655,
 0.20985119,
 1.1914427,
 0.15203227,
 1.3235538,
 0.43644834,
 1.6512723,
 0.85900337,
 0.21491344,
 0.7997183,
 0.36078924,
 0.12329184,
 1.0072687,
 0.7354474,
 0.35724097,
 0.42113465,
 0.22236687,
 1.6278903,
 1.1268073,
 0.25309223,
 0.65915424,
 0.20654692,
 1.051417,
 0.09585608,
 0.12653174,
 0.9235461,
 0.2731386,
 1.8473716,
 0.64104074,
 0.13256101,
 0.6002643,
 0.6435241,
 0.036502555,
 0.13633814,
 2.1610813,
 0.77671844,
 1.1283184,
 0.10333184,
 0.051944394,
 0.048246503,
 2.4411085,
 0.35728148,
 0.3375135,
 0.46323496,
 0.18830729,
 0.24635462,
 1.6219019,
 0.10867516,
 0.5220999,
 0.11087247,
 0.08477883,
 0.48524228,
 0.15029626,
 0,
 1.9958181,
 0.45636964,
 0.35779017,
 0.07187936,
 0.3327199,
 0,
 0.35163707,
 0.1517575,
 0.33117327,
 0.6575725,
 0.42150795,
 0.26715428,
 0.43024272,
 0.5659542,
 0.9019727,
 0.14673187,
 0.050448537,
 0.5822241,
 0.1299246,
 0.8938065,
 0,
 0.62293106,
 2.2649307,
 2.1155019,
 0.21233237,
 0.24157389,
 0.36027583,
 0.29826742,
 0.13509624,
 1.3894871,
 0,
 0.12490679,
 0.45419496,
 0.15393902,
 0,
 0.26877925,
 0.45285416,
 0.89491665,
 0.038450386,
 0.07158277,
 0.74491376,
 0.28484547,
 0.91982496,
 0.27414417,
 0.09103982,
 0.95117474,
 0.18424037,
 1.6022799,
 1.5885379,
 0.9080177,
 0.059770066,
 0.13042289,
 0.13562629,
 0.39384902,
 0.045868967,
 0.975896,
 0.96729565,
 0.3489069,
 0,
 0.5239884,
 0.6749622,
 1.1714735,
 0.14413369,
 1.4346473,
 0.04333456,
 0.26448867,
 1.2508371,
 0.20001234,
 0.14178956,
 1.2817638,
 0.10347791,
 0.23975371,
 0.47435313,
 0.15844643,
 0.29655355,
 0.5392795,
 0.41873178,
 0.07290415,
 0.20067345,
 2.1571784,
 0.5344273,
 0.16464616,
 0.3341302,
 0,
 0.6366483,
 0.116681635,
 0.19310343,
 0.6695679,
 0.33399537,
 0.19398485,
 0.7127988,
 0.29852343,
 1.4790066,
 1.0638825,
 1.0643445,
 0.7577089,
 1.070401,
 0.85558206,
 0.3448,
 0.7770381,
 0.29446486,
 0.2160049,
 0,
 0.3798813,
 1.7884207,
 0.28923464,
 0.32794726,
 0,
 0.9961432,
 0.4107235,
 0.34129548,
 1.0693899,
 0.28603548,
 0.96289325,
 0.49215013,
 0.13573733,
 1.0849562,
 0.20353937,
 0.11461694,
 2.1265604,
 0.9111494,
 2.1876945,
 0.43445593,
 0,
 0.5872871,
 0.117823124,
 0.34415293,
 0.26273772,
 0.29536414,
 0.90893924,
 2.1352656,
 0.23189318,
 0,
 0.0857066,
 0.29908848,
 0.26017725,
 0.6568115,
 0.38823956,
 0.93448085,
 0.7579899,
 0.24608637,
 0.64445996,
 1.0972903,
 0.28741702,
 0.62467295,
 1.7171546,
 0.090458125,
 0.81857675,
 0.9090781,
 0.2291538,
 0.6406496,
 0.3927437,
 0.063282095,
 0.14370422,
 0.11828435,
 1.4990762,
 0.21930021,
 0.14668807,
 0.33082217,
 0.35431507,
 0.6998694,
 0.47136557,
 0.89215463,
 1.9103477,
 0.31054786,
 0.083823726,
 0,
 0.586609,
 0.3724339,
 0.33541626,
 0.19576538,
 0.5613747,
 0.60173106,
 0.13091166,
 0.21972266,
 0.37977308,
 0.5764711,
 0.2722046,
 1.0918963,
 1.0535928,
 0.5825586,
 1.6144923,
 0.34699324,
 0,
 0.4115103,
 0.71497923,
 0.33434242,
 0.38704014,
 0.61989325,
 0.41240212,
 0.75089854,
 1.1683692,
 0.5269917,
 1.4542714,
 0.28016162,
 0.30896246,
 0,
 0.93866605,
 0.1961784,
 0.2301779,
 0.34360632,
 1.6089529,
 0.459759,
 0.89634746,
 0.31235322,
 0.43113455,
 0.54054385,
 0.30874854,
 0.39497155,
 0.21708417,
 0,
 0.7150691,
 0.39330614,
 0.22262792,
 1.0736823,
 0.60735375,
 1.47582,
 0.17005488,
 0.43737593,
 0.17960167,
 0,
 0.18740737,
 0.9758582,
 0.7653153,
 0.38479733,
 1.6827753,
 1.1468282,
 0.34785768,
 0.9674473,
 0.522086,
 0.43575484,
 0,
 0,
 0.046696123,
 1.0736823,
 0.64357233,
 0.39095706,
 0.9468669,
 0.32191637,
 0.26988977,
 1.4698775,
 0.21957876,
 0.13396096,
 0.509769,
 0,
 0.050297078,
 0.15190573,
 0.619274,
 1.1217444,
 0.67884433,
 0.3678255,
 0.32924694,
 0.2338739,
 0.15122437,
 0.3963177,
 0.4386609,
 2.3433194,
 0.7271288,
 0.077588364,
 0.76518863,
 0.21890609,
 0.69667935,
 0.7354942,
 0,
 0.042635787,
 0.19345333,
 2.223172,
 1.176627,
 0.018586302,
 0.25594762,
 1.4003432,
 1.100791,
 0.15285534,
 0.2906653,
 0.3634458,
 0.14931473,
 0.43950367,
 0.54564387,
 0.31022125,
 0.50524205,
 0.60173035,
 1.8969535,
 2.898758,
 0.07523703,
 0.40044138,
 0.0065838005,
 0.8184766,
 0.21267028,
 0.23395959,
 1.2468219,
 0.068893276,
 0.43090612,
 0.015529724,
 0.6209851,
 0.6755095,
 0.19095078,
 0.4416824,
 1.0257007,
 0.24456565,
 0.5770291,
 0.42983484,
 0.55232453,
 0.13819762,
 1.1538966,
 0.23822165,
 0.4130748,
 0.3862124,
 0.3303856,
 0.8814935,
 0,
 1.1245328,
 0.2588736,
 0.7155397,
 0.6363006,
 0.18455614,
 0.24113366,
 0.7104259,
 0.6760452,
 1.6478008,
 0.85408264,
 0.21444197,
 1.2952493,
 0.3453616,
 0.52148145,
 0.87117195,
 2.6119533,
 0.9215082,
 0,
 0.94509655,
 0.12704325,
 0.05920842,
 0.30827823,
 1.2303889,
 1.5345693,
 0.118515186,
 0.39255932,
 0.03772976,
 0.22328627,
 0.23912516,
 1.8284465,
 0.515591,
 0.3446941,
 0.28626427,
 1.096784,
 0.07202486,
 0.6377163,
 0.4047652,
 0.25858536,
 0.26146713,
 0.118661016,
 0.7994061,
 0.06944204,
 0.32305074,
 0.13761623,
 0.6739044,
 0.60574347,
 0.090938635,
 0.14411105,
 0.3431062,
 0.17942522,
 0.44921288,
 0.28240865,
 1.6249936,
 0.5117783,
 0.48341972,
 0.5159257,
 0.8135915,
 1.146084,
 0.26448867,
 0.3842262,
 0.09456005,
 0.39244652,
 0.23256703,
 0.18499137,
 0.13640569,
 0.8214975,
 0.29143456,
 0.057290997,
 0.08523673,
 0.2984282,
 0.24092151,
 0.022051966,
 0.29097232,
 0.207555,
 0.3129705,
 0,
 0.12182819,
 0.38303164,
 0.023411795,
 0.5471407,
 0.028380813,
 0.21258911,
 0.65608877,
 1.9787847,
 2.7409263,
 0.057977945,
 3.3197877,
 0.42907068,
 0.36255822,
 0.6327638,
 0.20025206,
 0.18296145,
 1.2860645,
 0.35585985,
 0.44678035,
 2.38565,
 0.5762241,
 0.7971423,
 0.009065883,
 0.6147594,
 1.8345782,
 0.92850024,
 0.6539576,
 0.3356754,
 0.58992404,
 0.5400492,
 0.068393216,
 0.29832762,
 0.085766114,
 0.34107727,
 0.2496159,
 0.19685511,
 0.6879755,
 0.29452506,
 0.6469518,
 0.2562171,
 1.0335174,
 1.8124334,
 0.6961928,
 0.19662228,
 0.30434507,
 0,
 0.5494375,
 1.0100054,
 0.34700876,
 0.25147364,
 0.2646233,
 1.4640872,
 0.3344804,
 0.2529373,
 0.6469769,
 0.35268986,
 0.19385718,
 0,
 0.2011553,
 0.13467428,
 0.48605427,
 0.18187495,
 0.107531615,
 0.54708415,
 1.1215721,
 0.1380167,
 0.0684768,
 0.5518292,
 0.6150615,
 0.5573871,
 1.1335429,
 0.30566332,
 0.2342316,
 0.50735784,
 0.042615436,
 0.2738276,
 0.23173857,
 0.3600777,
 0.36972764,
 0.4405506,
 0.75666493,
 0.2186927,
 0.20107731,
 0.9157585,
 0.29453847,
 0.508481,
 0.8786955,
 0.27909678,
 0.42983484,
 0.14941676,
 0.39147404,
 0.2188819,
 0.41535446,
 0.5872871,
 0.17537658,
 0.6426193,
 0.31389698,
 0.43113223,
 0.511236,
 0.18643437,
 0.5348548,
 0,
 0.4426533,
 0.19010097,
 0.33128268,
 0.07205624,
 0.03782916,
 0.3721632,
 0.37828875,
 0.18818602,
 1.4189655,
 0.9874344,
 0.45968968,
 0.2365093,
 0,
 0.08336831,
 0.41209382,
 0,
 0.07738823,
 0.31771186,
 0.22170986,
 0.21220134,
 1.876809,
 0.16682151,
 0.16991329,
 0.7319725,
 0.25552264,
 0.36511812,
 0,
 0,
 1.9018712,
 0.23065507,
 0.6481407,
 0.96445835,
 0.37085482,
 0.102628574,
 0.31143045,
 0.22725531,
 0.25286028,
 0.21319579,
 0.9058206,
 0.096527636,
 0.4899834,
 0.20989515,
 0.3033666,
 0.5149741,
 1.3484182,
 0.9558525,
 1.1288912,
 1.6578543,
 0.77634466,
 0.07766474,
 0.9917266,
 0.11853125,
 0.37550282,
 0.3216043,
 0.5763777,
 0.9998094,
 0.4697521,
 0.015341561,
 0.4855017,
 0.5131226,
 0.31540585,
 0.6147594,
 0.35244823,
 0,
 1.1052581,
 0.39753294,
 0,
 0.26594114,
 0.5658563,
 1.7245435,
 0.8195151,
 0.5763777,
 0.6693091,
 1.9268682,
 0.118661016,
 0.8051761,
 0.060951017,
 0,
 2.2254696,
 0.21364538,
 0.7620715,
 0.23853081,
 0.48827508,
 0.05204568,
 0.9785895,
 0.2996144,
 0.66004837,
 0.12071064,
 1.1833254,
 0.37081084,
 0.40022936,
 0,
 0.40195227,
 0.6000353,
 1.0918963,
 0.7818123,
 0.10732453,
 0.43380323,
 0.33043948,
 0.41918048,
 0.6839591,
 0.23667508,
 0.07837615,
 0.5498281,
 0.5687547,
 0.6150615,
 0.31205103,
 0.22517687,
 0.49793854,
 0.8964206,
 0.9367604,
 0.040229894,
 1.3684031,
 0.60453075,
 0.6036222,
 0.65823156,
 0.6927454,
 0.58309805,
 1.2347758,
 0.13423248,
 0,
 0,
 0.14553697,
 0.3705212,
 0.76198137,
 0,
 0.51373374,
 0.03303074,
 0.76079696,
 0.3586112,
 0.14926624,
 0.13415563,
 0.50632215,
 0.36033675,
 0.27782875,
 0.8408685,
 0.5574842,
 0.22369671,
 0.41342008,
 1.3357263,
 0.4646204,
 0.03309668,
 0.25963178,
 0.1871718,
 0.59476537,
 0,
 0.2731386,
 0.72969055,
 0.8581695,
 0.65327865,
 0.44539276,
 1.7046044,
 0.24007198,
 0.76850826,
 0.7013733,
 0.09216902,
 0.32090634,
 0.27949274,
 0.8364843,
 0.16655079,
 0.24993984,
 0.19269502,
 0.8179283,
 0.19777021,
 0.36339933,
 0.27587456,
 0.4170411,
 0.90275,
 0.25909054,
 1.5369239,
 0,
 0.43429977,
 0.20173761,
 0.4213137,
 1.2369237,
 0.8995198,
 0.92850024,
 0,
 0.24900337,
 0.43216917,
 1.1424086,
 0.106006294,
 0.27828965,
 0.048246503,
 0.23910357,
 0.5436169,
 0.06209707,
 0.14438094,
 0.19121863,
 0.14185327,
 1.2945293,
 0.706288,
 0.5239779,
 0.14263177,
 0.08309839,
 0.023413569,
 0.1254259,
 0.7433125,
 0.14255553,
 0.32157734,
 2.1680198,
 0.019019132,
 0.24613172,
 0.770743,
 0,
 0.118518464,
 ...]

In [69]:
from sklearn.metrics import mean_squared_error
score = np.sqrt(mean_squared_error(va_pred_0, y_test))
print(score)

0.6096558872255264

In [48]:
# 予測
pred = model.predict(dtest)
pred_0 = [0 if i <= 0 else i for i in pred]

### GDBT(NaNのまま，encoding多め): 0.6044626823948162

### GDBT(NaNのまま): 0.6042383633971182

### GBDT(NaNを-99に変換): 0.610822959180329

### ランダムフォレスト: 0.6326244864434752

# テストデータで予測

In [49]:
pred_df = pd.DataFrame(pred_0, columns=['応募数 合計'])
pred_df.head()

     応募数 合計
0  2.220500
1  3.307839
2  3.295953
3  3.467917
4  2.561777

In [50]:
submit = pd.concat([work_number, pred_df], axis=1)
submit.head()

       お仕事No.    応募数 合計
0  2203556553  2.220500
1  2203515280  3.307839
2  2203546900  3.295953
3  2203545344  3.467917
4  2203557987  2.561777

In [51]:
# submit.to_csv("submit_GBDT_NaN_encoding_2_0_NaNinfo.csv", index=False, encoding='utf_8_sig')