In [1]:
import numpy as np
import pandas as pd
import sklearn

In [2]:
application = pd.read_csv("train_x.csv")
application.head()

C:\Users\natsu\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (114) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,職場の様子,（紹介予定）入社後の雇用形態,勤務地 最寄駅3（駅名）,勤務地固定,休日休暇(月曜日),応募先 名称,（派遣先）配属先部署 男女比 男,勤務地 最寄駅3（沿線名）,（派遣先）勤務先写真コメント,勤務地 最寄駅3（分）,...,未使用.13,（紹介予定）待遇・福利厚生,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,応募拠点,給与/交通費 備考,残業なし,これまでの採用者例,期間･時間 備考,（派遣先）概要 勤務先名（フリガナ）
0,3,NaN,NaN,1,0,NaN,6.0,NaN,NaN,NaN,...,NaN,NaN,北千住,NaN,NaN,【月収例】19万5300円＋残業代（21日勤務の場合）,1,NaN,◆開始日はご相談可能です！詳しくはお問い合わせください！,NaN
1,3,1.0,NaN,1,0,NaN,2.0,NaN,NaN,NaN,...,NaN,完備,新御茶ノ水,5.0,NaN,【月収例】26万4600円＋残業代（21日勤務の場合）,1,NaN,NaN,NaN
2,3,1.0,NaN,1,0,NaN,2.0,NaN,NaN,NaN,...,NaN,完備,新御茶ノ水,5.0,NaN,【月収例】26万4600円＋残業代（21日勤務の場合）,1,NaN,NaN,NaN
3,2,1.0,NaN,1,0,NaN,8.0,NaN,NaN,NaN,...,NaN,完備,八丁堀,6.0,NaN,【月収例】25万9875円＋残業代（21日勤務の場合）,0,NaN,◆開始日はご相談可能です！詳しくはお問い合わせください！,NaN
4,2,1.0,NaN,1,0,NaN,8.0,NaN,NaN,NaN,...,NaN,完備,八丁堀,6.0,NaN,【月収例】25万9875円＋残業代（21日勤務の場合）,0,NaN,◆開始日はご相談可能です！詳しくはお問い合わせください！,NaN

In [3]:
len(application.columns.values)

212

In [4]:
q_x = pd.read_csv("test_x.csv")
q_x.head()

,勤務地 最寄駅3（駅名）,ミドル（40〜）活躍中,オープニングスタッフ,未使用.20,英語力不要,経験者優遇,Wordのスキルを活かす,メモ,派遣スタッフ活躍中,勤務地 最寄駅1（駅からの交通手段）,...,産休育休取得事例あり,仕事写真（下） 写真3 ファイル名,掲載期間 開始日,勤務地 最寄駅3（駅からの交通手段）,未経験OK,ブロックコード1,未使用.19,応募資格,WEB関連のスキルを活かす,対象者設定 年齢下限
0,NaN,1,NaN,NaN,1,1,1,NaN,1,1.0,...,1,NaN,2019/10/24,NaN,1,NaN,NaN,◆未経験者歓迎！<BR>【使用するＯＡスキル】Ｅｘｃｅｌ（関数）・ＰｏｗｅｒＰｏｉｎｔ（文章...,NaN,0
1,NaN,1,NaN,NaN,1,1,1,NaN,1,1.0,...,1,NaN,2019/10/24,NaN,1,NaN,NaN,【短大・専門・高専以上】◆業界経験問いません、ある方歓迎！<BR>※人事事務の経験が必要です...,NaN,0
2,NaN,1,NaN,NaN,1,1,1,NaN,1,1.0,...,1,NaN,2019/10/24,NaN,0,NaN,NaN,【専門・高専卒以上】◆事務経験・簿記３級程度の知識がある方歓迎します。<BR>【使用するＯＡ...,NaN,0
3,NaN,1,NaN,NaN,1,1,1,NaN,0,1.0,...,1,NaN,2019/10/24,NaN,1,NaN,NaN,【大卒以上】◆未経験者歓迎！<BR>【使用するＯＡスキル】Ｅｘｃｅｌ（関数）<BR><BR>...,NaN,0
4,NaN,1,NaN,NaN,1,1,1,NaN,0,1.0,...,1,NaN,2019/10/24,NaN,1,NaN,NaN,＜高卒以上＞◆未経験者歓迎！<BR>※金融機関での就業経験がある方歓迎。<BR>【使用するＯ...,NaN,0

In [5]:
# 全てnanのcolumnを削除
q_x_1 = q_x.dropna(how='all', axis=1)
q_x_1.head()

,ミドル（40〜）活躍中,英語力不要,経験者優遇,Wordのスキルを活かす,派遣スタッフ活躍中,勤務地 最寄駅1（駅からの交通手段）,派遣形態,DTP関連のスキルを活かす,勤務地 都道府県コード,休日休暇(祝日),...,（派遣先）配属先部署 男女比 女,雇用形態,（派遣先）勤務先写真ファイル名,勤務地 備考,派遣会社のうれしい特典,産休育休取得事例あり,掲載期間 開始日,未経験OK,応募資格,対象者設定 年齢下限
0,1,1,1,1,1,1.0,0,0,13,1,...,4.0,0,NaN,東京都世田谷区,"●当社は全国17,000件のお仕事を取り扱っており、毎日100名以上の方が就業を決めています...",1,2019/10/24,1,◆未経験者歓迎！<BR>【使用するＯＡスキル】Ｅｘｃｅｌ（関数）・ＰｏｗｅｒＰｏｉｎｔ（文章...,0
1,1,1,1,1,1,1.0,1,0,13,1,...,5.0,0,NaN,東京都中央区,"●当社は全国17,000件のお仕事を取り扱っており、毎日100名以上の方が就業を決めています...",1,2019/10/24,1,【短大・専門・高専以上】◆業界経験問いません、ある方歓迎！<BR>※人事事務の経験が必要です...,0
2,1,1,1,1,1,1.0,1,0,13,1,...,8.0,0,NaN,東京都千代田区,"●当社は全国17,000件のお仕事を取り扱っており、毎日100名以上の方が就業を決めています...",1,2019/10/24,0,【専門・高専卒以上】◆事務経験・簿記３級程度の知識がある方歓迎します。<BR>【使用するＯＡ...,0
3,1,1,1,1,0,1.0,1,0,13,1,...,2.0,0,NaN,東京都中央区,"●当社は全国17,000件のお仕事を取り扱っており、毎日100名以上の方が就業を決めています...",1,2019/10/24,1,【大卒以上】◆未経験者歓迎！<BR>【使用するＯＡスキル】Ｅｘｃｅｌ（関数）<BR><BR>...,0
4,1,1,1,1,0,1.0,1,0,13,1,...,4.0,0,NaN,東京都中央区,"●当社は全国17,000件のお仕事を取り扱っており、毎日100名以上の方が就業を決めています...",1,2019/10/24,1,＜高卒以上＞◆未経験者歓迎！<BR>※金融機関での就業経験がある方歓迎。<BR>【使用するＯ...,0

In [7]:
# 各行においてユニークな値のリスト
nunipue_count_list = list(q_x_1.nunique(dropna=False))
# 列名のリスト
q_x_1_columns_list = q_x_1.columns.values
# ユニークな値が1つだけの行を除外する
q_x_2 = q_x_1.copy()

for index in range(len(nunipue_count_list)):
#     ユニークな値が1つだけの時
    if nunipue_count_list[index] == 1:
        column_name = q_x_1_columns_list[index]
        q_x_2 = q_x_2.drop([column_name], axis=1)
        
q_x_2.nunique(dropna=False)

英語力不要                    2
経験者優遇                    2
Wordのスキルを活かす             2
派遣スタッフ活躍中                2
勤務地　最寄駅1（駅からの交通手段）       3
                      ...
（派遣先）配属先部署　男女比　女        12
（派遣先）勤務先写真ファイル名         24
勤務地　備考                  42
未経験OK                    2
応募資格                  2217
Length: 91, dtype: int64