# 取り組んだ軌跡：https://github.com/NatsukiH/apply_prediction  

こちらに精度比較を載せています．ぜひご覧ください．

最終の精度: 0.5908967018000341

# 前処理

In [2]:
import numpy as np
import pandas as pd
import sklearn

In [3]:
# 読み込み
application = pd.read_csv("train_x.csv")
application.head()

C:\Users\natsu\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (114) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,職場の様子,（紹介予定）入社後の雇用形態,勤務地 最寄駅3（駅名）,勤務地固定,休日休暇(月曜日),応募先 名称,（派遣先）配属先部署 男女比 男,勤務地 最寄駅3（沿線名）,（派遣先）勤務先写真コメント,勤務地 最寄駅3（分）,...,未使用.13,（紹介予定）待遇・福利厚生,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,応募拠点,給与/交通費 備考,残業なし,これまでの採用者例,期間･時間 備考,（派遣先）概要 勤務先名（フリガナ）
0,3,NaN,NaN,1,0,NaN,6.0,NaN,NaN,NaN,...,NaN,NaN,北千住,NaN,NaN,【月収例】19万5300円＋残業代（21日勤務の場合）,1,NaN,◆開始日はご相談可能です！詳しくはお問い合わせください！,NaN
1,3,1.0,NaN,1,0,NaN,2.0,NaN,NaN,NaN,...,NaN,完備,新御茶ノ水,5.0,NaN,【月収例】26万4600円＋残業代（21日勤務の場合）,1,NaN,NaN,NaN
2,3,1.0,NaN,1,0,NaN,2.0,NaN,NaN,NaN,...,NaN,完備,新御茶ノ水,5.0,NaN,【月収例】26万4600円＋残業代（21日勤務の場合）,1,NaN,NaN,NaN
3,2,1.0,NaN,1,0,NaN,8.0,NaN,NaN,NaN,...,NaN,完備,八丁堀,6.0,NaN,【月収例】25万9875円＋残業代（21日勤務の場合）,0,NaN,◆開始日はご相談可能です！詳しくはお問い合わせください！,NaN
4,2,1.0,NaN,1,0,NaN,8.0,NaN,NaN,NaN,...,NaN,完備,八丁堀,6.0,NaN,【月収例】25万9875円＋残業代（21日勤務の場合）,0,NaN,◆開始日はご相談可能です！詳しくはお問い合わせください！,NaN

In [4]:
application.describe()

,職場の様子,（紹介予定）入社後の雇用形態,勤務地 最寄駅3（駅名）,勤務地固定,休日休暇(月曜日),応募先 名称,（派遣先）配属先部署 男女比 男,勤務地 最寄駅3（沿線名）,（派遣先）勤務先写真コメント,勤務地 最寄駅3（分）,...,オフィスが禁煙・分煙,応募先 所在地 市区町村,仕事写真（下） 写真1 コメント,勤務地 市区町村コード,未使用.13,勤務地 最寄駅2（分）,応募拠点,残業なし,これまでの採用者例,（派遣先）概要 勤務先名（フリガナ）
count,15853.000000,2742.000000,0.0,15853.0,15853.000000,0.0,13801.000000,0.0,0.0,0.0,...,15853.000000,0.0,0.0,15853.000000,0.0,7359.000000,0.0,15853.000000,0.0,0.0
mean,2.946319,1.303793,NaN,1.0,0.006813,NaN,4.997464,NaN,NaN,NaN,...,0.991674,NaN,NaN,137.071848,NaN,7.621008,NaN,0.729578,NaN,NaN
std,0.306926,0.493645,NaN,0.0,0.082259,NaN,2.796697,NaN,NaN,NaN,...,0.090872,NaN,NaN,55.513015,NaN,4.577798,NaN,0.444192,NaN,NaN
min,2.000000,0.000000,NaN,1.0,0.000000,NaN,0.000000,NaN,NaN,NaN,...,0.000000,NaN,NaN,101.000000,NaN,1.000000,NaN,0.000000,NaN,NaN
25%,3.000000,1.000000,NaN,1.0,0.000000,NaN,3.000000,NaN,NaN,NaN,...,1.000000,NaN,NaN,103.000000,NaN,5.000000,NaN,0.000000,NaN,NaN
50%,3.000000,1.000000,NaN,1.0,0.000000,NaN,5.000000,NaN,NaN,NaN,...,1.000000,NaN,NaN,109.000000,NaN,7.000000,NaN,1.000000,NaN,NaN
75%,3.000000,2.000000,NaN,1.0,0.000000,NaN,7.000000,NaN,NaN,NaN,...,1.000000,NaN,NaN,201.000000,NaN,10.000000,NaN,1.000000,NaN,NaN
max,4.000000,2.000000,NaN,1.0,1.000000,NaN,10.000000,NaN,NaN,NaN,...,1.000000,NaN,NaN,631.000000,NaN,46.000000,NaN,1.000000,NaN,NaN

### 全てnanのcolumnを削除してみる

In [5]:
# 全てnanのcolumnを削除
a_1 = application.dropna(how='all', axis=1)
a_1.head()

,職場の様子,（紹介予定）入社後の雇用形態,勤務地固定,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,勤務地 最寄駅2（駅名）,大手企業,（紹介予定）雇用形態備考,週1日からOK,交通費別途支給,...,WEB登録OK,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,（紹介予定）待遇・福利厚生,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし,期間･時間 備考
0,3,NaN,1,0,6.0,NaN,0,NaN,0,0,...,1,1,121,当社スタッフ活躍中です！<BR>,NaN,北千住,NaN,【月収例】19万5300円＋残業代（21日勤務の場合）,1,◆開始日はご相談可能です！詳しくはお問い合わせください！
1,3,1.0,1,0,2.0,淡路町,1,正社員,0,0,...,1,1,101,ランチに嬉しい社員食堂完備の職場です！<BR>,完備,新御茶ノ水,5.0,【月収例】26万4600円＋残業代（21日勤務の場合）,1,NaN
2,3,1.0,1,0,2.0,淡路町,1,正社員,0,0,...,1,1,101,ランチに嬉しい社員食堂完備の職場です！<BR>,完備,新御茶ノ水,5.0,【月収例】26万4600円＋残業代（21日勤務の場合）,1,NaN
3,2,1.0,1,0,8.0,宝町,0,正社員,0,0,...,1,1,102,落ち着いた雰囲気の職場環境です！<BR>,完備,八丁堀,6.0,【月収例】25万9875円＋残業代（21日勤務の場合）,0,◆開始日はご相談可能です！詳しくはお問い合わせください！
4,2,1.0,1,0,8.0,宝町,0,正社員,0,0,...,1,1,102,落ち着いた雰囲気の職場環境です！<BR>,完備,八丁堀,6.0,【月収例】25万9875円＋残業代（21日勤務の場合）,0,◆開始日はご相談可能です！詳しくはお問い合わせください！

In [6]:
a_1.nunique(dropna=False)

職場の様子                  3
（紹介予定）入社後の雇用形態         4
勤務地固定                  1
休日休暇(月曜日)              2
（派遣先）配属先部署　男女比　男      12
                    ...
勤務地　最寄駅1（駅名）        1729
勤務地　最寄駅2（分）           33
給与/交通費　備考            556
残業なし                   2
期間･時間　備考               9
Length: 127, dtype: int64

### すべて同じ値の列は消去してみる

In [7]:
# 各行においてユニークな値のリスト
nunipue_count_list = list(a_1.nunique(dropna=False))
# 列名のリスト
a_1_columns_list = a_1.columns.values
# ユニークな値が1つだけの行を除外する
a_2 = a_1.copy()

for index in range(len(nunipue_count_list)):
#     ユニークな値が1つだけの時
    if nunipue_count_list[index] == 1:
        column_name = a_1_columns_list[index]
        a_2 = a_2.drop([column_name], axis=1)
        
a_2.nunique(dropna=False)

職場の様子                  3
（紹介予定）入社後の雇用形態         4
休日休暇(月曜日)              2
（派遣先）配属先部署　男女比　男      12
勤務地　最寄駅2（駅名）         840
                    ...
勤務地　最寄駅1（駅名）        1729
勤務地　最寄駅2（分）           33
給与/交通費　備考            556
残業なし                   2
期間･時間　備考               9
Length: 97, dtype: int64

In [8]:
a_2.head()

,職場の様子,（紹介予定）入社後の雇用形態,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,勤務地 最寄駅2（駅名）,大手企業,（紹介予定）雇用形態備考,交通費別途支給,（派遣先）配属先部署 人数,残業月20時間以上,...,給与/交通費 給与下限,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,（紹介予定）待遇・福利厚生,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし,期間･時間 備考
0,3,NaN,0,6.0,NaN,0,NaN,0,12.0,0,...,1550,1,121,当社スタッフ活躍中です！<BR>,NaN,北千住,NaN,【月収例】19万5300円＋残業代（21日勤務の場合）,1,◆開始日はご相談可能です！詳しくはお問い合わせください！
1,3,1.0,0,2.0,淡路町,1,正社員,0,33.0,0,...,1800,1,101,ランチに嬉しい社員食堂完備の職場です！<BR>,完備,新御茶ノ水,5.0,【月収例】26万4600円＋残業代（21日勤務の場合）,1,NaN
2,3,1.0,0,2.0,淡路町,1,正社員,0,33.0,0,...,1800,1,101,ランチに嬉しい社員食堂完備の職場です！<BR>,完備,新御茶ノ水,5.0,【月収例】26万4600円＋残業代（21日勤務の場合）,1,NaN
3,2,1.0,0,8.0,宝町,0,正社員,0,5.0,1,...,1650,1,102,落ち着いた雰囲気の職場環境です！<BR>,完備,八丁堀,6.0,【月収例】25万9875円＋残業代（21日勤務の場合）,0,◆開始日はご相談可能です！詳しくはお問い合わせください！
4,2,1.0,0,8.0,宝町,0,正社員,0,5.0,1,...,1650,1,102,落ち着いた雰囲気の職場環境です！<BR>,完備,八丁堀,6.0,【月収例】25万9875円＋残業代（21日勤務の場合）,0,◆開始日はご相談可能です！詳しくはお問い合わせください！

### NANが10000以上の指標を削除してみる

In [9]:
# nanのカウント
null_count = list(a_2.isnull().sum())
# 列名のリスト
a_2_columns_list = a_2.columns.values
# NANが10000以上の指標を削除してみる
a_3 = a_2.copy()

for index in range(len(null_count)):
#     NANが10000以上のとき
    if null_count[index] >= 10000:
        column_name = a_2_columns_list[index]
        a_3 = a_3.drop([column_name], axis=1)
        
a_3.isnull().sum()

職場の様子                  0
休日休暇(月曜日)              0
（派遣先）配属先部署　男女比　男    2052
勤務地　最寄駅2（駅名）        8367
大手企業                   0
                    ...
（派遣先）職場の雰囲気            4
勤務地　最寄駅1（駅名）           0
勤務地　最寄駅2（分）         8494
給与/交通費　備考           3556
残業なし                   0
Length: 86, dtype: int64

In [10]:
a_3.head()

,職場の様子,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,勤務地 最寄駅2（駅名）,大手企業,交通費別途支給,（派遣先）配属先部署 人数,残業月20時間以上,職種コード,1日7時間以下勤務OK,...,お仕事のポイント（仕事PR）,扶養控除内,給与/交通費 給与下限,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし
0,3,0,6.0,NaN,0,0,12.0,0,22010,1,...,◆駅からスグ！飲食店・コンビニが近く便利！職場環境ＧＯＯＤ◎！当社含む派遣スタッフ多数活躍中...,0,1550,1,121,当社スタッフ活躍中です！<BR>,北千住,NaN,【月収例】19万5300円＋残業代（21日勤務の場合）,1
1,3,0,2.0,淡路町,1,0,33.0,0,20020,1,...,◆開始日相談可能です♪複数路線が利用でき便利！休憩室完備の自社ビル！当社スタッフさん就業中！...,0,1800,1,101,ランチに嬉しい社員食堂完備の職場です！<BR>,新御茶ノ水,5.0,【月収例】26万4600円＋残業代（21日勤務の場合）,1
2,3,0,2.0,淡路町,1,0,33.0,0,20020,1,...,◆開始日相談可能です♪複数路線が利用でき便利！休憩室完備の自社ビル！当社スタッフさん就業中！...,0,1800,1,101,ランチに嬉しい社員食堂完備の職場です！<BR>,新御茶ノ水,5.0,【月収例】26万4600円＋残業代（21日勤務の場合）,1
3,2,0,8.0,宝町,0,0,5.0,1,20020,0,...,◆最寄駅から徒歩圏内！複数路線が利用可能！近くにコンビニ・カフェがあり便利！分煙されており快...,0,1650,1,102,落ち着いた雰囲気の職場環境です！<BR>,八丁堀,6.0,【月収例】25万9875円＋残業代（21日勤務の場合）,0
4,2,0,8.0,宝町,0,0,5.0,1,20020,0,...,◆最寄駅から徒歩圏内！複数路線が利用可能！近くにコンビニ・カフェがあり便利！分煙されており快...,0,1650,1,102,落ち着いた雰囲気の職場環境です！<BR>,八丁堀,6.0,【月収例】25万9875円＋残業代（21日勤務の場合）,0

### テストデータの読み込み

In [11]:
t_x = pd.read_csv("test_x.csv")
t_x.head()

,勤務地 最寄駅3（駅名）,ミドル（40〜）活躍中,オープニングスタッフ,未使用.20,英語力不要,経験者優遇,Wordのスキルを活かす,メモ,派遣スタッフ活躍中,勤務地 最寄駅1（駅からの交通手段）,...,産休育休取得事例あり,仕事写真（下） 写真3 ファイル名,掲載期間 開始日,勤務地 最寄駅3（駅からの交通手段）,未経験OK,ブロックコード1,未使用.19,応募資格,WEB関連のスキルを活かす,対象者設定 年齢下限
0,NaN,1,NaN,NaN,1,1,1,NaN,1,1.0,...,1,NaN,2019/10/24,NaN,1,NaN,NaN,◆未経験者歓迎！<BR>【使用するＯＡスキル】Ｅｘｃｅｌ（関数）・ＰｏｗｅｒＰｏｉｎｔ（文章...,NaN,0
1,NaN,1,NaN,NaN,1,1,1,NaN,1,1.0,...,1,NaN,2019/10/24,NaN,1,NaN,NaN,【短大・専門・高専以上】◆業界経験問いません、ある方歓迎！<BR>※人事事務の経験が必要です...,NaN,0
2,NaN,1,NaN,NaN,1,1,1,NaN,1,1.0,...,1,NaN,2019/10/24,NaN,0,NaN,NaN,【専門・高専卒以上】◆事務経験・簿記３級程度の知識がある方歓迎します。<BR>【使用するＯＡ...,NaN,0
3,NaN,1,NaN,NaN,1,1,1,NaN,0,1.0,...,1,NaN,2019/10/24,NaN,1,NaN,NaN,【大卒以上】◆未経験者歓迎！<BR>【使用するＯＡスキル】Ｅｘｃｅｌ（関数）<BR><BR>...,NaN,0
4,NaN,1,NaN,NaN,1,1,1,NaN,0,1.0,...,1,NaN,2019/10/24,NaN,1,NaN,NaN,＜高卒以上＞◆未経験者歓迎！<BR>※金融機関での就業経験がある方歓迎。<BR>【使用するＯ...,NaN,0

In [12]:
# a_3にカラムを合わせる
columns_list = list(a_3.columns.values)
t_x_1 = t_x[columns_list]
t_x_1.head()

,職場の様子,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,勤務地 最寄駅2（駅名）,大手企業,交通費別途支給,（派遣先）配属先部署 人数,残業月20時間以上,職種コード,1日7時間以下勤務OK,...,お仕事のポイント（仕事PR）,扶養控除内,給与/交通費 給与下限,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし
0,3,0,6.0,二子玉川,0,0,9.0,0,22010,1,...,◆同業務就業の方が在籍で安心！オシャレを楽しめるオフィカジＯＫ♪給湯設備・ホッと一息つける休...,0,1600,1,112,派遣スタッフ活躍中です！<BR>,成城学園前,15.0,【月収例】23万5200円＋残業代（21日勤務の場合）,1
1,3,0,5.0,水天宮前,0,0,11.0,0,22030,1,...,◆２つの駅からアクセス◎！飲食店・コンビニが近くお昼もラクチン！禁煙でクリーンな環境！オフィ...,0,1700,1,102,落ち着いた雰囲気の職場環境です！<BR>,人形町,1.0,【月収例】24万9900円＋残業代（21日勤務の場合）,0
2,3,0,2.0,淡路町,1,0,33.0,0,20020,1,...,◆開始日相談可能です♪複数路線が利用でき便利！休憩室完備の自社ビル！当社スタッフさん就業中！...,0,1800,1,101,ランチに嬉しい社員食堂完備の職場です！<BR>,新御茶ノ水,5.0,【月収例】26万4600円＋残業代（21日勤務の場合）,1
3,2,0,8.0,宝町,0,0,5.0,1,20020,0,...,◆最寄駅から徒歩圏内！複数路線が利用可能！近くにコンビニ・カフェがあり便利！分煙されており快...,0,1650,1,102,落ち着いた雰囲気の職場環境です！<BR>,八丁堀,6.0,【月収例】25万9875円＋残業代（21日勤務の場合）,0
4,2,0,6.0,日本橋,0,0,8.0,0,20020,1,...,◆駅からスグ！飲食店・コンビニが近く何かと便利！禁煙でクリーンな環境！カジュアル×デニムＯＫ...,0,1700,1,102,落ち着いた雰囲気のオフィスです！<BR>,茅場町,7.0,【月収例】24万9900円＋残業代（21日勤務の場合）,1

In [13]:
# object型のみ抽出
a_3_object = a_3.select_dtypes(include=object)
a_3_object.head()

,勤務地 最寄駅2（駅名）,掲載期間 開始日,勤務地 最寄駅2（沿線名）,休日休暇 備考,期間・時間 勤務時間,勤務地 備考,拠点番号,お仕事名,期間・時間 勤務開始日,（派遣先）配属先部署,仕事内容,勤務地 最寄駅1（沿線名）,応募資格,派遣会社のうれしい特典,掲載期間 終了日,お仕事のポイント（仕事PR）,（派遣先）職場の雰囲気,勤務地 最寄駅1（駅名）,給与/交通費 備考
0,NaN,2019/11/27,NaN,※土・日・祝がお休みです。※企業カレンダーあります。,9:30〜16:30 <BR>※残業はほとんどありません。<BR>※休憩は６０分です。,東京都足立区,206東京,ほぼ１６時半終業☆大学＊申請受付ｅｔｃ！未経験スタートＯＫ☆,2020/1/6,事務処理を行う部署,１月スタート！実働短め☆残業ほとんどなし×基本土日祝お休み！朝は少しゆっくりの９：３０出勤で...,東京メトロ千代田線,◆未経験者歓迎！<BR>【使用するＯＡスキル】Ｅｘｃｅｌ（ＶＬＯＯＫ関数）<BR><BR>▼...,"●当社は全国17,000件のお仕事を取り扱っており、毎日100名以上の方が就業を決めています...",2020/11/27,◆駅からスグ！飲食店・コンビニが近く便利！職場環境ＧＯＯＤ◎！当社含む派遣スタッフ多数活躍中...,当社スタッフ活躍中です！<BR>,北千住,【月収例】19万5300円＋残業代（21日勤務の場合）
1,淡路町,2019/11/27,東京メトロ丸ノ内線,※土・日・祝がお休みです。,9:00〜17:00 <BR>※残業はほとんどありません。<BR>※休憩は６０分です。,東京都千代田区,206東京,≪3ヶ月後正社員！≫大手損保会社でコツコツ事務＊社員食堂あり,2019/11/26,経理部,＜大手損保会社＞産休・育休取得実績ありの企業さんです♪ランチに嬉しい社員食堂完備の職場ですよ...,東京メトロ千代田線,【専門・高専卒以上】◆事務経験・簿記３級程度の知識がある方歓迎します。<BR>【使用するＯＡ...,"●当社は全国17,000件のお仕事を取り扱っており、毎日100名以上の方が就業を決めています...",2020/11/27,◆開始日相談可能です♪複数路線が利用でき便利！休憩室完備の自社ビル！当社スタッフさん就業中！...,ランチに嬉しい社員食堂完備の職場です！<BR>,新御茶ノ水,【月収例】26万4600円＋残業代（21日勤務の場合）
2,淡路町,2019/11/27,東京メトロ丸ノ内線,※土・日・祝がお休みです。,9:00〜17:00 <BR>※残業はほとんどありません。<BR>※休憩は６０分です。,東京都千代田区,206東京,≪3ヶ月後正社員！≫大手損保会社でコツコツ事務＊社員食堂あり,2019/11/26,経理部,＜大手損保会社＞産休・育休取得実績ありの企業さんです♪ランチに嬉しい社員食堂完備の職場ですよ...,東京メトロ千代田線,【専門・高専卒以上】◆事務経験・簿記３級程度の知識がある方歓迎します。<BR>【使用するＯＡ...,"●当社は全国17,000件のお仕事を取り扱っており、毎日100名以上の方が就業を決めています...",2020/11/27,◆開始日相談可能です♪複数路線が利用でき便利！休憩室完備の自社ビル！当社スタッフさん就業中！...,ランチに嬉しい社員食堂完備の職場です！<BR>,新御茶ノ水,【月収例】26万4600円＋残業代（21日勤務の場合）
3,宝町,2019/11/27,都営浅草線,※土・日・祝がお休みです。,9:00〜17:30 <BR>※休憩は６０分です。,東京都中央区,206東京,【未経験でも6ヶ月後社員】賞与年4.5ヶ月分＊非営利団体で事務,2019/11/26,企画調整部,安心安定の非営利団体！落ち着いた雰囲気の職場環境です！<BR>【ＯＡ事務】<BR>会議や委員...,東京メトロ日比谷線,【大卒以上】◆未経験者歓迎！<BR>【使用するＯＡスキル】Ｅｘｃｅｌ（関数）<BR><BR>...,"●当社は全国17,000件のお仕事を取り扱っており、毎日100名以上の方が就業を決めています...",2020/11/27,◆最寄駅から徒歩圏内！複数路線が利用可能！近くにコンビニ・カフェがあり便利！分煙されており快...,落ち着いた雰囲気の職場環境です！<BR>,八丁堀,【月収例】25万9875円＋残業代（21日勤務の場合）
4,宝町,2019/11/27,都営浅草線,※土・日・祝がお休みです。,9:00〜17:30 <BR>※休憩は６０分です。,東京都中央区,206東京,【未経験でも6ヶ月後社員】賞与年4.5ヶ月分＊非営利団体で事務,2019/11/26,企画調整部,安心安定の非営利団体！落ち着いた雰囲気の職場環境です！<BR>【ＯＡ事務】<BR>会議や委員...,東京メトロ日比谷線,【大卒以上】◆未経験者歓迎！<BR>【使用するＯＡスキル】Ｅｘｃｅｌ（関数）<BR><BR>...,"●当社は全国17,000件のお仕事を取り扱っており、毎日100名以上の方が就業を決めています...",2020/11/27,◆最寄駅から徒歩圏内！複数路線が利用可能！近くにコンビニ・カフェがあり便利！分煙されており快...,落ち着いた雰囲気の職場環境です！<BR>,八丁堀,【月収例】25万9875円＋残業代（21日勤務の場合）

In [14]:
df_info_a_3_object = pd.DataFrame({"unique count": list(a_3_object.nunique(dropna=False)), "null count": list(a_3_object.isnull().sum())}, index=list(a_3_object.columns.values))
df_info_a_3_object

                unique count  null count
勤務地　最寄駅2（駅名）             840        8367
掲載期間　開始日                   2           0
勤務地　最寄駅2（沿線名）            219        8367
休日休暇　備考                  752           0
期間・時間　勤務時間              3059           0
勤務地　備考                   736           0
拠点番号                      52           0
お仕事名                    9925           0
期間・時間　勤務開始日               94           0
（派遣先）配属先部署              3574           3
仕事内容                   11086           0
勤務地　最寄駅1（沿線名）            351           0
応募資格                    4385           0
派遣会社のうれしい特典               27           0
掲載期間　終了日                   2           0
お仕事のポイント（仕事PR）          9636           0
（派遣先）職場の雰囲気              866           4
勤務地　最寄駅1（駅名）            1729           0
給与/交通費　備考                556        3556

##### エンコーディングするカテゴリ変数の候補メモ

・~~勤務地　最寄駅2（駅名）~~　　→1があるからいらなそう

・~~掲載期間　開始日・終了日~~ 　→二値へ

・~~勤務地　最寄駅2（沿線名）~~  →駅名があるので、なくても良さげ

★休日休暇　備考

★~~期間・時間　勤務時間~~

★勤務地　備考

・~~拠点番号~~  →番号のみを抽出

・~~お仕事名~~  →ほぼ全部違うから無視
    
・~~期間・時間　勤務開始日~~

★~~（派遣先）配属先部署~~

・~~仕事内容~~  →お仕事名と同じく

・~~勤務地　最寄駅1（沿線名）~~　→駅名があるので、なくても良さげ

★~~応募資格~~

★派遣会社のうれしい特典

・~~お仕事のポイント（仕事PR）~~  →お仕事名と同じく

★（派遣先）職場の雰囲気

★勤務地　最寄駅1（駅名）

★給与/交通費　備考

submit_GBDT_Nan_encodingの時よりも少しエンコーディングする変数を減らす  
あまりにも種類が多いもの（ばらばらなもの）のカラムは消去していくことにする

In [15]:
# trainデータに対してNANをなくす
a_4 = a_3.copy()
a_4["休日休暇　備考"] = a_4["休日休暇　備考"].fillna("missing")
# a_4["期間・時間　勤務時間"] = a_4["期間・時間　勤務時間"].fillna("missing")
a_4["勤務地　備考"] = a_4["勤務地　備考"].fillna("missing")
# a_4["（派遣先）配属先部署"] = a_4["（派遣先）配属先部署"].fillna("missing")
# a_4["応募資格"] = a_4["応募資格"].fillna("missing")
a_4["派遣会社のうれしい特典"] = a_4["派遣会社のうれしい特典"].fillna("missing")
a_4["（派遣先）職場の雰囲気"] = a_4["（派遣先）職場の雰囲気"].fillna("missing")
a_4["勤務地　最寄駅1（駅名）"] = a_4["勤務地　最寄駅1（駅名）"].fillna("missing")
a_4["給与/交通費　備考"] = a_4["給与/交通費　備考"].fillna("missing")

In [16]:
# testデータに対してNANをなくす
t_x_2 = t_x_1.copy()
t_x_2["休日休暇　備考"] = t_x_2["休日休暇　備考"].fillna("missing")
# t_x_2["期間・時間　勤務時間"] = t_x_2["期間・時間　勤務時間"].fillna("missing")
t_x_2["勤務地　備考"] = t_x_2["勤務地　備考"].fillna("missing")
# t_x_2["（派遣先）配属先部署"] = t_x_2["（派遣先）配属先部署"].fillna("missing")
# t_x_2["応募資格"] = t_x_2["応募資格"].fillna("missing")
t_x_2["派遣会社のうれしい特典"] = t_x_2["派遣会社のうれしい特典"].fillna("missing")
t_x_2["（派遣先）職場の雰囲気"] = t_x_2["（派遣先）職場の雰囲気"].fillna("missing")
t_x_2["勤務地　最寄駅1（駅名）"] = t_x_2["勤務地　最寄駅1（駅名）"].fillna("missing")
t_x_2["給与/交通費　備考"] = t_x_2["給与/交通費　備考"].fillna("missing")

In [17]:
# "休日休暇　備考","期間・時間　勤務時間","勤務地　備考","（派遣先）配属先部署","応募資格","派遣会社のうれしい特典","（派遣先）職場の雰囲気","勤務地　最寄駅1（駅名）","給与/交通費　備考"
# ,,,,,,,

In [18]:
from sklearn.preprocessing import LabelEncoder

a_5 = a_4.copy()
t_x_3 = t_x_2.copy()
le1 = LabelEncoder()
# a_5とt_x_3においてラベル付け
le1.fit(pd.concat([a_5["休日休暇　備考"], t_x_3["休日休暇　備考"]], sort=True))
a_5["休日休暇　備考"] = le1.transform(a_5["休日休暇　備考"])
t_x_3["休日休暇　備考"] = le1.transform(t_x_3["休日休暇　備考"])

In [19]:
# le2 = LabelEncoder()
# le2.fit(pd.concat([a_5["期間・時間　勤務時間"], t_x_3["期間・時間　勤務時間"]], sort=True))
# a_5["期間・時間　勤務時間"] = le2.transform(a_5["期間・時間　勤務時間"])
# t_x_3["期間・時間　勤務時間"] = le2.transform(t_x_3["期間・時間　勤務時間"])

le3 = LabelEncoder()
le3.fit(pd.concat([a_5["勤務地　備考"], t_x_3["勤務地　備考"]], sort=True))
a_5["勤務地　備考"] = le3.transform(a_5["勤務地　備考"])
t_x_3["勤務地　備考"] = le3.transform(t_x_3["勤務地　備考"])

# le4 = LabelEncoder()
# le4.fit(pd.concat([a_5["（派遣先）配属先部署"], t_x_3["（派遣先）配属先部署"]], sort=True))
# a_5["（派遣先）配属先部署"] = le4.transform(a_5["（派遣先）配属先部署"])
# t_x_3["（派遣先）配属先部署"] = le4.transform(t_x_3["（派遣先）配属先部署"])

# le5 = LabelEncoder()
# le5.fit(pd.concat([a_5["応募資格"], t_x_3["応募資格"]], sort=True))
# a_5["応募資格"] = le5.transform(a_5["応募資格"])
# t_x_3["応募資格"] = le5.transform(t_x_3["応募資格"])

le6 = LabelEncoder()
le6.fit(pd.concat([a_5["派遣会社のうれしい特典"], t_x_3["派遣会社のうれしい特典"]], sort=True))
a_5["派遣会社のうれしい特典"] = le6.transform(a_5["派遣会社のうれしい特典"])
t_x_3["派遣会社のうれしい特典"] = le6.transform(t_x_3["派遣会社のうれしい特典"])

le7 = LabelEncoder()
le7.fit(pd.concat([a_5["（派遣先）職場の雰囲気"], t_x_3["（派遣先）職場の雰囲気"]], sort=True))
a_5["（派遣先）職場の雰囲気"] = le7.transform(a_5["（派遣先）職場の雰囲気"])
t_x_3["（派遣先）職場の雰囲気"] = le7.transform(t_x_3["（派遣先）職場の雰囲気"])

le8 = LabelEncoder()
le8.fit(pd.concat([a_5["勤務地　最寄駅1（駅名）"], t_x_3["勤務地　最寄駅1（駅名）"]], sort=True))
a_5["勤務地　最寄駅1（駅名）"] = le8.transform(a_5["勤務地　最寄駅1（駅名）"])
t_x_3["勤務地　最寄駅1（駅名）"] = le8.transform(t_x_3["勤務地　最寄駅1（駅名）"])

le9 = LabelEncoder()
le9.fit(pd.concat([a_5["給与/交通費　備考"], t_x_3["給与/交通費　備考"]], sort=True))
a_5["給与/交通費　備考"] = le9.transform(a_5["給与/交通費　備考"])
t_x_3["給与/交通費　備考"] = le9.transform(t_x_3["給与/交通費　備考"])

In [20]:
# trainデータに対して使わないカラムの削除
a_5 = a_5.drop(["勤務地　最寄駅2（駅名）", "勤務地　最寄駅2（沿線名）", "お仕事名", "期間・時間　勤務開始日", "仕事内容", "勤務地　最寄駅1（沿線名）", "お仕事のポイント（仕事PR）", "掲載期間　終了日", "期間・時間　勤務時間", "（派遣先）配属先部署", "応募資格"], axis=1)
a_5.head()

,職場の様子,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,大手企業,交通費別途支給,（派遣先）配属先部署 人数,残業月20時間以上,職種コード,1日7時間以下勤務OK,短時間勤務OK(1日4h以内),...,休日休暇(金曜日),扶養控除内,給与/交通費 給与下限,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし
0,3,0,6.0,0,0,12.0,0,22010,1,0,...,0,0,1550,1,121,477,325,NaN,186,1
1,3,0,2.0,1,0,33.0,0,20020,1,0,...,0,0,1800,1,101,185,832,5.0,424,1
2,3,0,2.0,1,0,33.0,0,20020,1,0,...,0,0,1800,1,101,185,832,5.0,424,1
3,2,0,8.0,0,0,5.0,1,20020,0,0,...,0,0,1650,1,102,777,261,6.0,411,0
4,2,0,8.0,0,0,5.0,1,20020,0,0,...,0,0,1650,1,102,777,261,6.0,411,0

In [21]:
# testデータに対して使わないカラムの削除
t_x_3 = t_x_3.drop(["勤務地　最寄駅2（駅名）", "勤務地　最寄駅2（沿線名）", "お仕事名", "期間・時間　勤務開始日", "仕事内容", "勤務地　最寄駅1（沿線名）", "お仕事のポイント（仕事PR）", "掲載期間　終了日", "期間・時間　勤務時間", "（派遣先）配属先部署", "応募資格"], axis=1)
t_x_3.head()

,職場の様子,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,大手企業,交通費別途支給,（派遣先）配属先部署 人数,残業月20時間以上,職種コード,1日7時間以下勤務OK,短時間勤務OK(1日4h以内),...,休日休暇(金曜日),扶養控除内,給与/交通費 給与下限,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし
0,3,0,6.0,0,0,9.0,0,22010,1,0,...,0,0,1600,1,112,608,773,15.0,325,1
1,3,0,5.0,0,0,11.0,0,22030,1,0,...,0,0,1700,1,102,777,205,1.0,373,0
2,3,0,2.0,1,0,33.0,0,20020,1,0,...,0,0,1800,1,101,185,832,5.0,424,1
3,2,0,8.0,0,0,5.0,1,20020,0,0,...,0,0,1650,1,102,777,261,6.0,411,0
4,2,0,6.0,0,0,8.0,0,20020,1,0,...,0,0,1700,1,102,773,1401,7.0,373,1

In [22]:
# 掲載開始日を０，１にエンコード
# trainデータ
day_mapping = {"2019/11/27": 0, "2019/9/25": 1}
a_5["掲載期間　開始日"] = a_5['掲載期間　開始日'].map(day_mapping)

In [23]:
# testデータ
t_x_3 = t_x_3.replace('2019/10/24', 3)
t_x_3.head()

,職場の様子,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,大手企業,交通費別途支給,（派遣先）配属先部署 人数,残業月20時間以上,職種コード,1日7時間以下勤務OK,短時間勤務OK(1日4h以内),...,休日休暇(金曜日),扶養控除内,給与/交通費 給与下限,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし
0,3,0,6.0,0,0,9.0,0,22010,1,0,...,0,0,1600,1,112,608,773,15.0,325,1
1,3,0,5.0,0,0,11.0,0,22030,1,0,...,0,0,1700,1,102,777,205,1.0,373,0
2,3,0,2.0,1,0,33.0,0,20020,1,0,...,0,0,1800,1,101,185,832,5.0,424,1
3,2,0,8.0,0,0,5.0,1,20020,0,0,...,0,0,1650,1,102,777,261,6.0,411,0
4,2,0,6.0,0,0,8.0,0,20020,1,0,...,0,0,1700,1,102,773,1401,7.0,373,1

In [24]:
# trainデータの拠点番号
func = lambda x: int(x[:3])
a_5["拠点番号"] = a_5["拠点番号"].map(func)
a_5.head()

,職場の様子,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,大手企業,交通費別途支給,（派遣先）配属先部署 人数,残業月20時間以上,職種コード,1日7時間以下勤務OK,短時間勤務OK(1日4h以内),...,休日休暇(金曜日),扶養控除内,給与/交通費 給与下限,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし
0,3,0,6.0,0,0,12.0,0,22010,1,0,...,0,0,1550,1,121,477,325,NaN,186,1
1,3,0,2.0,1,0,33.0,0,20020,1,0,...,0,0,1800,1,101,185,832,5.0,424,1
2,3,0,2.0,1,0,33.0,0,20020,1,0,...,0,0,1800,1,101,185,832,5.0,424,1
3,2,0,8.0,0,0,5.0,1,20020,0,0,...,0,0,1650,1,102,777,261,6.0,411,0
4,2,0,8.0,0,0,5.0,1,20020,0,0,...,0,0,1650,1,102,777,261,6.0,411,0

In [25]:
# testデータの拠点番号
# trainデータの拠点番号
func = lambda x: int(x[:3])
t_x_3["拠点番号"] = t_x_3["拠点番号"].map(func)
t_x_3.head()

,職場の様子,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,大手企業,交通費別途支給,（派遣先）配属先部署 人数,残業月20時間以上,職種コード,1日7時間以下勤務OK,短時間勤務OK(1日4h以内),...,休日休暇(金曜日),扶養控除内,給与/交通費 給与下限,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし
0,3,0,6.0,0,0,9.0,0,22010,1,0,...,0,0,1600,1,112,608,773,15.0,325,1
1,3,0,5.0,0,0,11.0,0,22030,1,0,...,0,0,1700,1,102,777,205,1.0,373,0
2,3,0,2.0,1,0,33.0,0,20020,1,0,...,0,0,1800,1,101,185,832,5.0,424,1
3,2,0,8.0,0,0,5.0,1,20020,0,0,...,0,0,1650,1,102,777,261,6.0,411,0
4,2,0,6.0,0,0,8.0,0,20020,1,0,...,0,0,1700,1,102,773,1401,7.0,373,1

In [26]:
# 予測用データ
submit_x = t_x_3

In [27]:
work_number = submit_x["お仕事No."]
submit_x_test = np.array(submit_x.drop(["お仕事No."], axis=1))
submit_x_test.shape

(3391, 74)

In [28]:
a_5.describe()

,職場の様子,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,大手企業,交通費別途支給,（派遣先）配属先部署 人数,残業月20時間以上,職種コード,1日7時間以下勤務OK,短時間勤務OK(1日4h以内),...,休日休暇(金曜日),扶養控除内,給与/交通費 給与下限,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし
count,15853.000000,15853.000000,13801.000000,15853.000000,15853.000000,13814.000000,15853.000000,15853.000000,15853.000000,15853.000000,...,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,7359.000000,15853.000000,15853.000000
mean,2.946319,0.006813,4.997464,0.237242,0.218129,14.174461,0.064972,20637.698227,0.277802,0.010219,...,0.009903,0.011670,1469.690279,0.991674,137.071848,434.118211,848.275027,7.621008,243.595282,0.729578
std,0.306926,0.082259,2.796697,0.425405,0.412989,23.165115,0.246484,2598.874377,0.447930,0.100574,...,0.099025,0.107398,244.447800,0.090872,55.513015,234.841303,494.809165,4.577798,176.965509,0.444192
min,2.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,20020.000000,0.000000,0.000000,...,0.000000,0.000000,800.000000,0.000000,101.000000,0.000000,0.000000,1.000000,0.000000,0.000000
25%,3.000000,0.000000,3.000000,0.000000,0.000000,5.000000,0.000000,20020.000000,0.000000,0.000000,...,0.000000,0.000000,1300.000000,1.000000,103.000000,232.000000,430.000000,5.000000,72.000000,0.000000
50%,3.000000,0.000000,5.000000,0.000000,0.000000,8.000000,0.000000,20030.000000,0.000000,0.000000,...,0.000000,0.000000,1500.000000,1.000000,109.000000,404.000000,882.000000,7.000000,269.000000,1.000000
75%,3.000000,0.000000,7.000000,0.000000,0.000000,15.000000,0.000000,20710.000000,1.000000,0.000000,...,0.000000,0.000000,1650.000000,1.000000,201.000000,665.000000,1228.000000,10.000000,409.000000,1.000000
max,4.000000,1.000000,10.000000,1.000000,1.000000,574.000000,1.000000,80310.000000,1.000000,1.000000,...,1.000000,1.000000,2850.000000,1.000000,631.000000,936.000000,1748.000000,46.000000,575.000000,1.000000

In [29]:
# 前処理後データ
application_after = a_5
application_after.head()

,職場の様子,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,大手企業,交通費別途支給,（派遣先）配属先部署 人数,残業月20時間以上,職種コード,1日7時間以下勤務OK,短時間勤務OK(1日4h以内),...,休日休暇(金曜日),扶養控除内,給与/交通費 給与下限,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし
0,3,0,6.0,0,0,12.0,0,22010,1,0,...,0,0,1550,1,121,477,325,NaN,186,1
1,3,0,2.0,1,0,33.0,0,20020,1,0,...,0,0,1800,1,101,185,832,5.0,424,1
2,3,0,2.0,1,0,33.0,0,20020,1,0,...,0,0,1800,1,101,185,832,5.0,424,1
3,2,0,8.0,0,0,5.0,1,20020,0,0,...,0,0,1650,1,102,777,261,6.0,411,0
4,2,0,8.0,0,0,5.0,1,20020,0,0,...,0,0,1650,1,102,777,261,6.0,411,0

### yの読み込み

In [30]:
df_y = pd.read_csv("train_y.csv")
df_y.head()

       お仕事No.    応募数 合計
0  2203566799  1.945910
1  2203546900  3.951244
2  2203546900  3.295837
3  2203545344  3.970292
4  2203545344  3.784190

In [31]:
len(df_y)

15853

# 回帰問題

In [32]:
y = df_y["応募数 合計"]
X = application_after.drop(["お仕事No."], axis=1)

In [33]:
y_array = np.array(y)
X_array = np.array(X)

In [34]:
print("y_array: ", y_array.shape)
print("X_array: ", X_array.shape)

y_array:  (15853,)
X_array:  (15853, 74)

In [35]:
# train/testに分割する
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_array, y_array, test_size=0.4, random_state=0)

In [36]:
print("X_train: ", X_train.shape)
print("y_train: ", y_train.shape)
print("X_test: ", X_test.shape)
print("y_test: ", y_test.shape)

X_train:  (9511, 74)
y_train:  (9511,)
X_test:  (6342, 74)
y_test:  (6342,)

# GBDT LIghtGBM

In [37]:
import lightgbm as lgb

In [38]:
# 特徴量と目的変数をlightgbmのデータ構造に変換する
lgb_train = lgb.Dataset(X_train, y_train)
lgb_eval = lgb.Dataset(X_test, y_test)

In [48]:
# ハイパーパラメータの設定
params = {"seed": 71, "verbose": 0, "metrics": "rmse"}
num_round = 228

In [49]:
# 学習の実行
# バリデーションデータもモデルに渡し、学習の進行とともにスコアがどう変わるかモニタリングする
model = lgb.train(params, lgb_train, num_boost_round = num_round, valid_names = ["train", "valid"], valid_sets = [lgb_train, lgb_eval])

[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.054352 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[1]	train's rmse: 0.776544	valid's rmse: 0.750591
[2]	train's rmse: 0.759196	valid's rmse: 0.734561
[3]	train's rmse: 0.743992	valid's rmse: 0.721069
[4]	train's rmse: 0.731795	valid's rmse: 0.710624
[5]	train's rmse: 0.720457	valid's rmse: 0.70133
[6]	train's rmse: 0.710393	valid's rmse: 0.692666
[7]	train's rmse: 0.701248	valid's rmse: 0.685734
[8]	train's rmse: 0.693545	valid's rmse: 0.679883
[9]	train's rmse: 0.686693	valid's rmse: 0.675003
[10]	train's rmse: 0.679697	valid's rmse: 0.66993
[11]	train's rmse: 0.674297	valid's rmse: 0.666582
[12]	train's rmse: 0.668034	valid's rmse: 0.661921
[13]	train's rmse: 0.663082	valid's rmse: 0.658548
[14]	train's rmse: 0.658574	valid's rmse: 0.655424
[15]	train's rmse: 0.65421	valid's rmse: 0.653551
[16]	train's rmse: 0.64975	valid's rmse: 0.650673
[17]	train's rmse: 0.646264	valid's rmse: 0.649202
[18]	train's rmse: 0.642956	valid's rmse: 0.647546
[19]	train's rmse: 0.639279	valid's rmse: 0.64557
[20]	train's rmse: 0.63621	valid's rmse: 0.644268
[21]	train's rmse: 0.633094	valid's rmse: 0.642921
[22]	train's rmse: 0.629314	valid's rmse: 0.641258
[23]	train's rmse: 0.626337	valid's rmse: 0.640375
[24]	train's rmse: 0.62289	valid's rmse: 0.63832
[25]	train's rmse: 0.619736	valid's rmse: 0.636858
[26]	train's rmse: 0.61614	valid's rmse: 0.635161
[27]	train's rmse: 0.613188	valid's rmse: 0.633579
[28]	train's rmse: 0.610483	valid's rmse: 0.632394
[29]	train's rmse: 0.607412	valid's rmse: 0.630542
[30]	train's rmse: 0.604485	valid's rmse: 0.629366
[31]	train's rmse: 0.602126	valid's rmse: 0.628279
[32]	train's rmse: 0.599814	valid's rmse: 0.627708
[33]	train's rmse: 0.597307	valid's rmse: 0.626866
[34]	train's rmse: 0.594769	valid's rmse: 0.625724
[35]	train's rmse: 0.592464	valid's rmse: 0.624662
[36]	train's rmse: 0.590269	valid's rmse: 0.62365
[37]	train's rmse: 0.587968	valid's rmse: 0.622776
[38]	train's rmse: 0.585552	valid's rmse: 0.621927
[39]	train's rmse: 0.583541	valid's rmse: 0.621142
[40]	train's rmse: 0.581765	valid's rmse: 0.620639
[41]	train's rmse: 0.579496	valid's rmse: 0.619834
[42]	train's rmse: 0.577888	valid's rmse: 0.619438
[43]	train's rmse: 0.575767	valid's rmse: 0.618691
[44]	train's rmse: 0.573936	valid's rmse: 0.618368
[45]	train's rmse: 0.571853	valid's rmse: 0.617521
[46]	train's rmse: 0.570283	valid's rmse: 0.61732
[47]	train's rmse: 0.568443	valid's rmse: 0.616468
[48]	train's rmse: 0.566826	valid's rmse: 0.616163
[49]	train's rmse: 0.565385	valid's rmse: 0.615644
[50]	train's rmse: 0.564047	valid's rmse: 0.615213
[51]	train's rmse: 0.562248	valid's rmse: 0.614738
[52]	train's rmse: 0.560713	valid's rmse: 0.614026
[53]	train's rmse: 0.559377	valid's rmse: 0.613586
[54]	train's rmse: 0.558024	valid's rmse: 0.613469
[55]	train's rmse: 0.556671	valid's rmse: 0.613101
[56]	train's rmse: 0.555264	valid's rmse: 0.612746
[57]	train's rmse: 0.553354	valid's rmse: 0.612058
[58]	train's rmse: 0.55205	valid's rmse: 0.611645
[59]	train's rmse: 0.550641	valid's rmse: 0.611366
[60]	train's rmse: 0.549369	valid's rmse: 0.61114
[61]	train's rmse: 0.54807	valid's rmse: 0.610728
[62]	train's rmse: 0.546329	valid's rmse: 0.610042
[63]	train's rmse: 0.545149	valid's rmse: 0.609695
[64]	train's rmse: 0.543562	valid's rmse: 0.609184
[65]	train's rmse: 0.542125	valid's rmse: 0.608711
[66]	train's rmse: 0.541055	valid's rmse: 0.608626
[67]	train's rmse: 0.539647	valid's rmse: 0.608069
[68]	train's rmse: 0.538752	valid's rmse: 0.607925
[69]	train's rmse: 0.53759	valid's rmse: 0.607385
[70]	train's rmse: 0.536545	valid's rmse: 0.607332
[71]	train's rmse: 0.535483	valid's rmse: 0.607055
[72]	train's rmse: 0.534135	valid's rmse: 0.606809
[73]	train's rmse: 0.532758	valid's rmse: 0.606292
[74]	train's rmse: 0.531964	valid's rmse: 0.606124
[75]	train's rmse: 0.530767	valid's rmse: 0.605339
[76]	train's rmse: 0.529506	valid's rmse: 0.605192
[77]	train's rmse: 0.52855	valid's rmse: 0.604896
[78]	train's rmse: 0.527338	valid's rmse: 0.604589
[79]	train's rmse: 0.526054	valid's rmse: 0.604196
[80]	train's rmse: 0.524506	valid's rmse: 0.603804
[81]	train's rmse: 0.523447	valid's rmse: 0.603513
[82]	train's rmse: 0.522388	valid's rmse: 0.603417
[83]	train's rmse: 0.521415	valid's rmse: 0.603295
[84]	train's rmse: 0.520439	valid's rmse: 0.603175
[85]	train's rmse: 0.519742	valid's rmse: 0.603115
[86]	train's rmse: 0.51892	valid's rmse: 0.602918
[87]	train's rmse: 0.518091	valid's rmse: 0.602723
[88]	train's rmse: 0.517048	valid's rmse: 0.60259
[89]	train's rmse: 0.5161	valid's rmse: 0.60236
[90]	train's rmse: 0.515446	valid's rmse: 0.602338
[91]	train's rmse: 0.514641	valid's rmse: 0.602156
[92]	train's rmse: 0.513801	valid's rmse: 0.601772
[93]	train's rmse: 0.512848	valid's rmse: 0.601556
[94]	train's rmse: 0.511771	valid's rmse: 0.601204
[95]	train's rmse: 0.511007	valid's rmse: 0.601213
[96]	train's rmse: 0.510132	valid's rmse: 0.600978
[97]	train's rmse: 0.509225	valid's rmse: 0.600789
[98]	train's rmse: 0.507973	valid's rmse: 0.60069
[99]	train's rmse: 0.50704	valid's rmse: 0.600461
[100]	train's rmse: 0.506446	valid's rmse: 0.600297
[101]	train's rmse: 0.505552	valid's rmse: 0.600187
[102]	train's rmse: 0.504545	valid's rmse: 0.59999
[103]	train's rmse: 0.503844	valid's rmse: 0.599812
[104]	train's rmse: 0.502467	valid's rmse: 0.599345
[105]	train's rmse: 0.501947	valid's rmse: 0.599374
[106]	train's rmse: 0.500669	valid's rmse: 0.598874
[107]	train's rmse: 0.499666	valid's rmse: 0.598823
[108]	train's rmse: 0.498704	valid's rmse: 0.598802
[109]	train's rmse: 0.497912	valid's rmse: 0.598528
[110]	train's rmse: 0.496923	valid's rmse: 0.598259
[111]	train's rmse: 0.496039	valid's rmse: 0.598198
[112]	train's rmse: 0.495278	valid's rmse: 0.598094
[113]	train's rmse: 0.494742	valid's rmse: 0.598062
[114]	train's rmse: 0.493821	valid's rmse: 0.597865
[115]	train's rmse: 0.493051	valid's rmse: 0.597427
[116]	train's rmse: 0.492164	valid's rmse: 0.597476
[117]	train's rmse: 0.491296	valid's rmse: 0.597372
[118]	train's rmse: 0.490587	valid's rmse: 0.597321
[119]	train's rmse: 0.489502	valid's rmse: 0.597201
[120]	train's rmse: 0.488837	valid's rmse: 0.597078
[121]	train's rmse: 0.488071	valid's rmse: 0.596928
[122]	train's rmse: 0.487325	valid's rmse: 0.596848
[123]	train's rmse: 0.486748	valid's rmse: 0.596746
[124]	train's rmse: 0.485791	valid's rmse: 0.596656
[125]	train's rmse: 0.485109	valid's rmse: 0.596558
[126]	train's rmse: 0.484344	valid's rmse: 0.596587
[127]	train's rmse: 0.483514	valid's rmse: 0.596603
[128]	train's rmse: 0.482874	valid's rmse: 0.596667
[129]	train's rmse: 0.481748	valid's rmse: 0.596192
[130]	train's rmse: 0.48122	valid's rmse: 0.596198
[131]	train's rmse: 0.480536	valid's rmse: 0.596113
[132]	train's rmse: 0.479878	valid's rmse: 0.595906
[133]	train's rmse: 0.479286	valid's rmse: 0.595791
[134]	train's rmse: 0.478394	valid's rmse: 0.595572
[135]	train's rmse: 0.477936	valid's rmse: 0.595548
[136]	train's rmse: 0.476761	valid's rmse: 0.59528
[137]	train's rmse: 0.475933	valid's rmse: 0.595162
[138]	train's rmse: 0.475146	valid's rmse: 0.595109
[139]	train's rmse: 0.474589	valid's rmse: 0.594975
[140]	train's rmse: 0.473814	valid's rmse: 0.594884
[141]	train's rmse: 0.4734	valid's rmse: 0.594937
[142]	train's rmse: 0.472497	valid's rmse: 0.594762
[143]	train's rmse: 0.471685	valid's rmse: 0.594792
[144]	train's rmse: 0.471027	valid's rmse: 0.594788
[145]	train's rmse: 0.470322	valid's rmse: 0.594637
[146]	train's rmse: 0.469623	valid's rmse: 0.594686
[147]	train's rmse: 0.468942	valid's rmse: 0.594705
[148]	train's rmse: 0.468506	valid's rmse: 0.594682
[149]	train's rmse: 0.467711	valid's rmse: 0.594471
[150]	train's rmse: 0.467055	valid's rmse: 0.594319
[151]	train's rmse: 0.466333	valid's rmse: 0.594205
[152]	train's rmse: 0.465799	valid's rmse: 0.594104
[153]	train's rmse: 0.465147	valid's rmse: 0.593858
[154]	train's rmse: 0.464124	valid's rmse: 0.593637
[155]	train's rmse: 0.463509	valid's rmse: 0.593627
[156]	train's rmse: 0.462999	valid's rmse: 0.593509
[157]	train's rmse: 0.462579	valid's rmse: 0.593524
[158]	train's rmse: 0.461851	valid's rmse: 0.593556
[159]	train's rmse: 0.461347	valid's rmse: 0.593675
[160]	train's rmse: 0.46027	valid's rmse: 0.593489
[161]	train's rmse: 0.459618	valid's rmse: 0.593587
[162]	train's rmse: 0.458846	valid's rmse: 0.593157
[163]	train's rmse: 0.458051	valid's rmse: 0.593053
[164]	train's rmse: 0.45748	valid's rmse: 0.592818
[165]	train's rmse: 0.456926	valid's rmse: 0.592912
[166]	train's rmse: 0.456102	valid's rmse: 0.592556
[167]	train's rmse: 0.455462	valid's rmse: 0.592704
[168]	train's rmse: 0.454896	valid's rmse: 0.592757
[169]	train's rmse: 0.454023	valid's rmse: 0.592862
[170]	train's rmse: 0.453545	valid's rmse: 0.59294
[171]	train's rmse: 0.452895	valid's rmse: 0.592977
[172]	train's rmse: 0.452172	valid's rmse: 0.592864

[173]	train's rmse: 0.451366	valid's rmse: 0.59281
[174]	train's rmse: 0.450802	valid's rmse: 0.592678
[175]	train's rmse: 0.449997	valid's rmse: 0.592654
[176]	train's rmse: 0.44944	valid's rmse: 0.5926
[177]	train's rmse: 0.448948	valid's rmse: 0.59266
[178]	train's rmse: 0.448038	valid's rmse: 0.592744
[179]	train's rmse: 0.44758	valid's rmse: 0.592757
[180]	train's rmse: 0.447162	valid's rmse: 0.592751
[181]	train's rmse: 0.446576	valid's rmse: 0.592695
[182]	train's rmse: 0.445722	valid's rmse: 0.592575
[183]	train's rmse: 0.445152	valid's rmse: 0.59258
[184]	train's rmse: 0.444543	valid's rmse: 0.592391
[185]	train's rmse: 0.444032	valid's rmse: 0.592279
[186]	train's rmse: 0.443572	valid's rmse: 0.592386
[187]	train's rmse: 0.443067	valid's rmse: 0.592275
[188]	train's rmse: 0.44268	valid's rmse: 0.592185
[189]	train's rmse: 0.44214	valid's rmse: 0.592153
[190]	train's rmse: 0.441693	valid's rmse: 0.592062
[191]	train's rmse: 0.441215	valid's rmse: 0.592255
[192]	train's rmse: 0.440746	valid's rmse: 0.592138
[193]	train's rmse: 0.440239	valid's rmse: 0.592094
[194]	train's rmse: 0.4398	valid's rmse: 0.592214
[195]	train's rmse: 0.439153	valid's rmse: 0.592247
[196]	train's rmse: 0.438629	valid's rmse: 0.592224
[197]	train's rmse: 0.438146	valid's rmse: 0.592296
[198]	train's rmse: 0.437483	valid's rmse: 0.592092
[199]	train's rmse: 0.436857	valid's rmse: 0.592069
[200]	train's rmse: 0.436392	valid's rmse: 0.592027
[201]	train's rmse: 0.435956	valid's rmse: 0.591959
[202]	train's rmse: 0.435574	valid's rmse: 0.591923
[203]	train's rmse: 0.435249	valid's rmse: 0.591932
[204]	train's rmse: 0.434744	valid's rmse: 0.591871
[205]	train's rmse: 0.433982	valid's rmse: 0.591763
[206]	train's rmse: 0.433407	valid's rmse: 0.591806
[207]	train's rmse: 0.433061	valid's rmse: 0.591741
[208]	train's rmse: 0.432718	valid's rmse: 0.591756
[209]	train's rmse: 0.432082	valid's rmse: 0.591685
[210]	train's rmse: 0.431468	valid's rmse: 0.591755
[211]	train's rmse: 0.430953	valid's rmse: 0.591556
[212]	train's rmse: 0.430387	valid's rmse: 0.591517
[213]	train's rmse: 0.430085	valid's rmse: 0.591587
[214]	train's rmse: 0.429674	valid's rmse: 0.591471
[215]	train's rmse: 0.429429	valid's rmse: 0.591482
[216]	train's rmse: 0.428799	valid's rmse: 0.591562
[217]	train's rmse: 0.428356	valid's rmse: 0.591551
[218]	train's rmse: 0.428057	valid's rmse: 0.59147
[219]	train's rmse: 0.427419	valid's rmse: 0.591457
[220]	train's rmse: 0.42696	valid's rmse: 0.591496
[221]	train's rmse: 0.426224	valid's rmse: 0.59135
[222]	train's rmse: 0.425845	valid's rmse: 0.591438
[223]	train's rmse: 0.425429	valid's rmse: 0.591491
[224]	train's rmse: 0.424896	valid's rmse: 0.591435
[225]	train's rmse: 0.424507	valid's rmse: 0.591405
[226]	train's rmse: 0.424174	valid's rmse: 0.591539
[227]	train's rmse: 0.423384	valid's rmse: 0.591294
[228]	train's rmse: 0.422922	valid's rmse: 0.591337

In [55]:
# バリデーションデータでのスコアの確認
va_pred = model.predict(X_test)
# 負の値は0へ
va_pred_0 = [0 if i <= 0 else i for i in va_pred]

In [56]:
from sklearn.metrics import mean_squared_error
score = np.sqrt(mean_squared_error(va_pred_0, y_test))
print(score)

0.5908967018000341

In [58]:
# 予測
pred = model.predict(submit_x_test)
pred_0 = [0 if i <= 0 else i for i in pred]

### GDBT(NaNのまま，encoding多め): 0.6044626823948162

### GDBT(NaNのまま): 0.6042383633971182

### GBDT(NaNを-99に変換): 0.610822959180329

### ランダムフォレスト: 0.6326244864434752

# テストデータで予測

In [59]:
pred_df = pd.DataFrame(pred_0, columns=['応募数 合計'])
pred_df.head()

     応募数 合計
0  2.054021
1  3.086947
2  3.196478
3  3.765384
4  1.955700

In [60]:
submit = pd.concat([work_number, pred_df], axis=1)
submit.head()

       お仕事No.    応募数 合計
0  2203556553  2.054021
1  2203515280  3.086947
2  2203546900  3.196478
3  2203545344  3.765384
4  2203557987  1.955700

In [61]:
submit.to_csv("submit_LightGBM_NaN_encoding_2_0.csv", index=False, encoding='utf_8_sig')