# 取り組んだ軌跡(Githubリポジトリ)：https://github.com/NatsukiH/apply_prediction  

こちらに精度比較を載せています．ぜひご覧ください．

最終の精度: 0.5892398722162967

# 前処理

In [1]:
import numpy as np
import pandas as pd
import sklearn

In [2]:
# 読み込み
application = pd.read_csv("train_x.csv")
application.head()

C:\Users\natsu\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (114) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,職場の様子,（紹介予定）入社後の雇用形態,勤務地 最寄駅3（駅名）,勤務地固定,休日休暇(月曜日),応募先 名称,（派遣先）配属先部署 男女比 男,勤務地 最寄駅3（沿線名）,（派遣先）勤務先写真コメント,勤務地 最寄駅3（分）,...,未使用.13,（紹介予定）待遇・福利厚生,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,応募拠点,給与/交通費 備考,残業なし,これまでの採用者例,期間･時間 備考,（派遣先）概要 勤務先名（フリガナ）
0,3,NaN,NaN,1,0,NaN,6.0,NaN,NaN,NaN,...,NaN,NaN,北千住,NaN,NaN,【月収例】19万5300円＋残業代（21日勤務の場合）,1,NaN,◆開始日はご相談可能です！詳しくはお問い合わせください！,NaN
1,3,1.0,NaN,1,0,NaN,2.0,NaN,NaN,NaN,...,NaN,完備,新御茶ノ水,5.0,NaN,【月収例】26万4600円＋残業代（21日勤務の場合）,1,NaN,NaN,NaN
2,3,1.0,NaN,1,0,NaN,2.0,NaN,NaN,NaN,...,NaN,完備,新御茶ノ水,5.0,NaN,【月収例】26万4600円＋残業代（21日勤務の場合）,1,NaN,NaN,NaN
3,2,1.0,NaN,1,0,NaN,8.0,NaN,NaN,NaN,...,NaN,完備,八丁堀,6.0,NaN,【月収例】25万9875円＋残業代（21日勤務の場合）,0,NaN,◆開始日はご相談可能です！詳しくはお問い合わせください！,NaN
4,2,1.0,NaN,1,0,NaN,8.0,NaN,NaN,NaN,...,NaN,完備,八丁堀,6.0,NaN,【月収例】25万9875円＋残業代（21日勤務の場合）,0,NaN,◆開始日はご相談可能です！詳しくはお問い合わせください！,NaN

In [3]:
application.describe()

,職場の様子,（紹介予定）入社後の雇用形態,勤務地 最寄駅3（駅名）,勤務地固定,休日休暇(月曜日),応募先 名称,（派遣先）配属先部署 男女比 男,勤務地 最寄駅3（沿線名）,（派遣先）勤務先写真コメント,勤務地 最寄駅3（分）,...,オフィスが禁煙・分煙,応募先 所在地 市区町村,仕事写真（下） 写真1 コメント,勤務地 市区町村コード,未使用.13,勤務地 最寄駅2（分）,応募拠点,残業なし,これまでの採用者例,（派遣先）概要 勤務先名（フリガナ）
count,15853.000000,2742.000000,0.0,15853.0,15853.000000,0.0,13801.000000,0.0,0.0,0.0,...,15853.000000,0.0,0.0,15853.000000,0.0,7359.000000,0.0,15853.000000,0.0,0.0
mean,2.946319,1.303793,NaN,1.0,0.006813,NaN,4.997464,NaN,NaN,NaN,...,0.991674,NaN,NaN,137.071848,NaN,7.621008,NaN,0.729578,NaN,NaN
std,0.306926,0.493645,NaN,0.0,0.082259,NaN,2.796697,NaN,NaN,NaN,...,0.090872,NaN,NaN,55.513015,NaN,4.577798,NaN,0.444192,NaN,NaN
min,2.000000,0.000000,NaN,1.0,0.000000,NaN,0.000000,NaN,NaN,NaN,...,0.000000,NaN,NaN,101.000000,NaN,1.000000,NaN,0.000000,NaN,NaN
25%,3.000000,1.000000,NaN,1.0,0.000000,NaN,3.000000,NaN,NaN,NaN,...,1.000000,NaN,NaN,103.000000,NaN,5.000000,NaN,0.000000,NaN,NaN
50%,3.000000,1.000000,NaN,1.0,0.000000,NaN,5.000000,NaN,NaN,NaN,...,1.000000,NaN,NaN,109.000000,NaN,7.000000,NaN,1.000000,NaN,NaN
75%,3.000000,2.000000,NaN,1.0,0.000000,NaN,7.000000,NaN,NaN,NaN,...,1.000000,NaN,NaN,201.000000,NaN,10.000000,NaN,1.000000,NaN,NaN
max,4.000000,2.000000,NaN,1.0,1.000000,NaN,10.000000,NaN,NaN,NaN,...,1.000000,NaN,NaN,631.000000,NaN,46.000000,NaN,1.000000,NaN,NaN

### 全てnanのcolumnを削除してみる

In [4]:
# 全てnanのcolumnを削除
a_1 = application.dropna(how='all', axis=1)
a_1.head()

,職場の様子,（紹介予定）入社後の雇用形態,勤務地固定,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,勤務地 最寄駅2（駅名）,大手企業,（紹介予定）雇用形態備考,週1日からOK,交通費別途支給,...,WEB登録OK,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,（紹介予定）待遇・福利厚生,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし,期間･時間 備考
0,3,NaN,1,0,6.0,NaN,0,NaN,0,0,...,1,1,121,当社スタッフ活躍中です！<BR>,NaN,北千住,NaN,【月収例】19万5300円＋残業代（21日勤務の場合）,1,◆開始日はご相談可能です！詳しくはお問い合わせください！
1,3,1.0,1,0,2.0,淡路町,1,正社員,0,0,...,1,1,101,ランチに嬉しい社員食堂完備の職場です！<BR>,完備,新御茶ノ水,5.0,【月収例】26万4600円＋残業代（21日勤務の場合）,1,NaN
2,3,1.0,1,0,2.0,淡路町,1,正社員,0,0,...,1,1,101,ランチに嬉しい社員食堂完備の職場です！<BR>,完備,新御茶ノ水,5.0,【月収例】26万4600円＋残業代（21日勤務の場合）,1,NaN
3,2,1.0,1,0,8.0,宝町,0,正社員,0,0,...,1,1,102,落ち着いた雰囲気の職場環境です！<BR>,完備,八丁堀,6.0,【月収例】25万9875円＋残業代（21日勤務の場合）,0,◆開始日はご相談可能です！詳しくはお問い合わせください！
4,2,1.0,1,0,8.0,宝町,0,正社員,0,0,...,1,1,102,落ち着いた雰囲気の職場環境です！<BR>,完備,八丁堀,6.0,【月収例】25万9875円＋残業代（21日勤務の場合）,0,◆開始日はご相談可能です！詳しくはお問い合わせください！

In [5]:
a_1.nunique(dropna=False)

職場の様子                  3
（紹介予定）入社後の雇用形態         4
勤務地固定                  1
休日休暇(月曜日)              2
（派遣先）配属先部署　男女比　男      12
                    ...
勤務地　最寄駅1（駅名）        1729
勤務地　最寄駅2（分）           33
給与/交通費　備考            556
残業なし                   2
期間･時間　備考               9
Length: 127, dtype: int64

### すべて同じ値の列は消去してみる

In [6]:
# 各行においてユニークな値のリスト
nunipue_count_list = list(a_1.nunique(dropna=False))
# 列名のリスト
a_1_columns_list = a_1.columns.values
# ユニークな値が1つだけの行を除外する
a_2 = a_1.copy()

for index in range(len(nunipue_count_list)):
#     ユニークな値が1つだけの時
    if nunipue_count_list[index] == 1:
        column_name = a_1_columns_list[index]
        a_2 = a_2.drop([column_name], axis=1)
        
a_2.nunique(dropna=False)

職場の様子                  3
（紹介予定）入社後の雇用形態         4
休日休暇(月曜日)              2
（派遣先）配属先部署　男女比　男      12
勤務地　最寄駅2（駅名）         840
                    ...
勤務地　最寄駅1（駅名）        1729
勤務地　最寄駅2（分）           33
給与/交通費　備考            556
残業なし                   2
期間･時間　備考               9
Length: 97, dtype: int64

In [7]:
a_2.head()

,職場の様子,（紹介予定）入社後の雇用形態,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,勤務地 最寄駅2（駅名）,大手企業,（紹介予定）雇用形態備考,交通費別途支給,（派遣先）配属先部署 人数,残業月20時間以上,...,給与/交通費 給与下限,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,（紹介予定）待遇・福利厚生,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし,期間･時間 備考
0,3,NaN,0,6.0,NaN,0,NaN,0,12.0,0,...,1550,1,121,当社スタッフ活躍中です！<BR>,NaN,北千住,NaN,【月収例】19万5300円＋残業代（21日勤務の場合）,1,◆開始日はご相談可能です！詳しくはお問い合わせください！
1,3,1.0,0,2.0,淡路町,1,正社員,0,33.0,0,...,1800,1,101,ランチに嬉しい社員食堂完備の職場です！<BR>,完備,新御茶ノ水,5.0,【月収例】26万4600円＋残業代（21日勤務の場合）,1,NaN
2,3,1.0,0,2.0,淡路町,1,正社員,0,33.0,0,...,1800,1,101,ランチに嬉しい社員食堂完備の職場です！<BR>,完備,新御茶ノ水,5.0,【月収例】26万4600円＋残業代（21日勤務の場合）,1,NaN
3,2,1.0,0,8.0,宝町,0,正社員,0,5.0,1,...,1650,1,102,落ち着いた雰囲気の職場環境です！<BR>,完備,八丁堀,6.0,【月収例】25万9875円＋残業代（21日勤務の場合）,0,◆開始日はご相談可能です！詳しくはお問い合わせください！
4,2,1.0,0,8.0,宝町,0,正社員,0,5.0,1,...,1650,1,102,落ち着いた雰囲気の職場環境です！<BR>,完備,八丁堀,6.0,【月収例】25万9875円＋残業代（21日勤務の場合）,0,◆開始日はご相談可能です！詳しくはお問い合わせください！

### NANが10000以上の指標を削除してみる

In [8]:
# nanのカウント
null_count = list(a_2.isnull().sum())
# 列名のリスト
a_2_columns_list = a_2.columns.values
# NANが10000以上の指標を削除してみる
a_3 = a_2.copy()

for index in range(len(null_count)):
#     NANが10000以上のとき
    if null_count[index] >= 10000:
        column_name = a_2_columns_list[index]
        a_3 = a_3.drop([column_name], axis=1)
        
a_3.isnull().sum()

職場の様子                  0
休日休暇(月曜日)              0
（派遣先）配属先部署　男女比　男    2052
勤務地　最寄駅2（駅名）        8367
大手企業                   0
                    ...
（派遣先）職場の雰囲気            4
勤務地　最寄駅1（駅名）           0
勤務地　最寄駅2（分）         8494
給与/交通費　備考           3556
残業なし                   0
Length: 86, dtype: int64

In [9]:
a_3.head()

,職場の様子,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,勤務地 最寄駅2（駅名）,大手企業,交通費別途支給,（派遣先）配属先部署 人数,残業月20時間以上,職種コード,1日7時間以下勤務OK,...,お仕事のポイント（仕事PR）,扶養控除内,給与/交通費 給与下限,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし
0,3,0,6.0,NaN,0,0,12.0,0,22010,1,...,◆駅からスグ！飲食店・コンビニが近く便利！職場環境ＧＯＯＤ◎！当社含む派遣スタッフ多数活躍中...,0,1550,1,121,当社スタッフ活躍中です！<BR>,北千住,NaN,【月収例】19万5300円＋残業代（21日勤務の場合）,1
1,3,0,2.0,淡路町,1,0,33.0,0,20020,1,...,◆開始日相談可能です♪複数路線が利用でき便利！休憩室完備の自社ビル！当社スタッフさん就業中！...,0,1800,1,101,ランチに嬉しい社員食堂完備の職場です！<BR>,新御茶ノ水,5.0,【月収例】26万4600円＋残業代（21日勤務の場合）,1
2,3,0,2.0,淡路町,1,0,33.0,0,20020,1,...,◆開始日相談可能です♪複数路線が利用でき便利！休憩室完備の自社ビル！当社スタッフさん就業中！...,0,1800,1,101,ランチに嬉しい社員食堂完備の職場です！<BR>,新御茶ノ水,5.0,【月収例】26万4600円＋残業代（21日勤務の場合）,1
3,2,0,8.0,宝町,0,0,5.0,1,20020,0,...,◆最寄駅から徒歩圏内！複数路線が利用可能！近くにコンビニ・カフェがあり便利！分煙されており快...,0,1650,1,102,落ち着いた雰囲気の職場環境です！<BR>,八丁堀,6.0,【月収例】25万9875円＋残業代（21日勤務の場合）,0
4,2,0,8.0,宝町,0,0,5.0,1,20020,0,...,◆最寄駅から徒歩圏内！複数路線が利用可能！近くにコンビニ・カフェがあり便利！分煙されており快...,0,1650,1,102,落ち着いた雰囲気の職場環境です！<BR>,八丁堀,6.0,【月収例】25万9875円＋残業代（21日勤務の場合）,0

### テストデータの読み込み

In [10]:
t_x = pd.read_csv("test_x.csv")
t_x.head()

,勤務地 最寄駅3（駅名）,ミドル（40〜）活躍中,オープニングスタッフ,未使用.20,英語力不要,経験者優遇,Wordのスキルを活かす,メモ,派遣スタッフ活躍中,勤務地 最寄駅1（駅からの交通手段）,...,産休育休取得事例あり,仕事写真（下） 写真3 ファイル名,掲載期間 開始日,勤務地 最寄駅3（駅からの交通手段）,未経験OK,ブロックコード1,未使用.19,応募資格,WEB関連のスキルを活かす,対象者設定 年齢下限
0,NaN,1,NaN,NaN,1,1,1,NaN,1,1.0,...,1,NaN,2019/10/24,NaN,1,NaN,NaN,◆未経験者歓迎！<BR>【使用するＯＡスキル】Ｅｘｃｅｌ（関数）・ＰｏｗｅｒＰｏｉｎｔ（文章...,NaN,0
1,NaN,1,NaN,NaN,1,1,1,NaN,1,1.0,...,1,NaN,2019/10/24,NaN,1,NaN,NaN,【短大・専門・高専以上】◆業界経験問いません、ある方歓迎！<BR>※人事事務の経験が必要です...,NaN,0
2,NaN,1,NaN,NaN,1,1,1,NaN,1,1.0,...,1,NaN,2019/10/24,NaN,0,NaN,NaN,【専門・高専卒以上】◆事務経験・簿記３級程度の知識がある方歓迎します。<BR>【使用するＯＡ...,NaN,0
3,NaN,1,NaN,NaN,1,1,1,NaN,0,1.0,...,1,NaN,2019/10/24,NaN,1,NaN,NaN,【大卒以上】◆未経験者歓迎！<BR>【使用するＯＡスキル】Ｅｘｃｅｌ（関数）<BR><BR>...,NaN,0
4,NaN,1,NaN,NaN,1,1,1,NaN,0,1.0,...,1,NaN,2019/10/24,NaN,1,NaN,NaN,＜高卒以上＞◆未経験者歓迎！<BR>※金融機関での就業経験がある方歓迎。<BR>【使用するＯ...,NaN,0

In [11]:
# a_3にカラムを合わせる
columns_list = list(a_3.columns.values)
t_x_1 = t_x[columns_list]
t_x_1.head()

,職場の様子,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,勤務地 最寄駅2（駅名）,大手企業,交通費別途支給,（派遣先）配属先部署 人数,残業月20時間以上,職種コード,1日7時間以下勤務OK,...,お仕事のポイント（仕事PR）,扶養控除内,給与/交通費 給与下限,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし
0,3,0,6.0,二子玉川,0,0,9.0,0,22010,1,...,◆同業務就業の方が在籍で安心！オシャレを楽しめるオフィカジＯＫ♪給湯設備・ホッと一息つける休...,0,1600,1,112,派遣スタッフ活躍中です！<BR>,成城学園前,15.0,【月収例】23万5200円＋残業代（21日勤務の場合）,1
1,3,0,5.0,水天宮前,0,0,11.0,0,22030,1,...,◆２つの駅からアクセス◎！飲食店・コンビニが近くお昼もラクチン！禁煙でクリーンな環境！オフィ...,0,1700,1,102,落ち着いた雰囲気の職場環境です！<BR>,人形町,1.0,【月収例】24万9900円＋残業代（21日勤務の場合）,0
2,3,0,2.0,淡路町,1,0,33.0,0,20020,1,...,◆開始日相談可能です♪複数路線が利用でき便利！休憩室完備の自社ビル！当社スタッフさん就業中！...,0,1800,1,101,ランチに嬉しい社員食堂完備の職場です！<BR>,新御茶ノ水,5.0,【月収例】26万4600円＋残業代（21日勤務の場合）,1
3,2,0,8.0,宝町,0,0,5.0,1,20020,0,...,◆最寄駅から徒歩圏内！複数路線が利用可能！近くにコンビニ・カフェがあり便利！分煙されており快...,0,1650,1,102,落ち着いた雰囲気の職場環境です！<BR>,八丁堀,6.0,【月収例】25万9875円＋残業代（21日勤務の場合）,0
4,2,0,6.0,日本橋,0,0,8.0,0,20020,1,...,◆駅からスグ！飲食店・コンビニが近く何かと便利！禁煙でクリーンな環境！カジュアル×デニムＯＫ...,0,1700,1,102,落ち着いた雰囲気のオフィスです！<BR>,茅場町,7.0,【月収例】24万9900円＋残業代（21日勤務の場合）,1

In [12]:
# object型のみ抽出
a_3_object = a_3.select_dtypes(include=object)
a_3_object.head()

,勤務地 最寄駅2（駅名）,掲載期間 開始日,勤務地 最寄駅2（沿線名）,休日休暇 備考,期間・時間 勤務時間,勤務地 備考,拠点番号,お仕事名,期間・時間 勤務開始日,（派遣先）配属先部署,仕事内容,勤務地 最寄駅1（沿線名）,応募資格,派遣会社のうれしい特典,掲載期間 終了日,お仕事のポイント（仕事PR）,（派遣先）職場の雰囲気,勤務地 最寄駅1（駅名）,給与/交通費 備考
0,NaN,2019/11/27,NaN,※土・日・祝がお休みです。※企業カレンダーあります。,9:30〜16:30 <BR>※残業はほとんどありません。<BR>※休憩は６０分です。,東京都足立区,206東京,ほぼ１６時半終業☆大学＊申請受付ｅｔｃ！未経験スタートＯＫ☆,2020/1/6,事務処理を行う部署,１月スタート！実働短め☆残業ほとんどなし×基本土日祝お休み！朝は少しゆっくりの９：３０出勤で...,東京メトロ千代田線,◆未経験者歓迎！<BR>【使用するＯＡスキル】Ｅｘｃｅｌ（ＶＬＯＯＫ関数）<BR><BR>▼...,"●当社は全国17,000件のお仕事を取り扱っており、毎日100名以上の方が就業を決めています...",2020/11/27,◆駅からスグ！飲食店・コンビニが近く便利！職場環境ＧＯＯＤ◎！当社含む派遣スタッフ多数活躍中...,当社スタッフ活躍中です！<BR>,北千住,【月収例】19万5300円＋残業代（21日勤務の場合）
1,淡路町,2019/11/27,東京メトロ丸ノ内線,※土・日・祝がお休みです。,9:00〜17:00 <BR>※残業はほとんどありません。<BR>※休憩は６０分です。,東京都千代田区,206東京,≪3ヶ月後正社員！≫大手損保会社でコツコツ事務＊社員食堂あり,2019/11/26,経理部,＜大手損保会社＞産休・育休取得実績ありの企業さんです♪ランチに嬉しい社員食堂完備の職場ですよ...,東京メトロ千代田線,【専門・高専卒以上】◆事務経験・簿記３級程度の知識がある方歓迎します。<BR>【使用するＯＡ...,"●当社は全国17,000件のお仕事を取り扱っており、毎日100名以上の方が就業を決めています...",2020/11/27,◆開始日相談可能です♪複数路線が利用でき便利！休憩室完備の自社ビル！当社スタッフさん就業中！...,ランチに嬉しい社員食堂完備の職場です！<BR>,新御茶ノ水,【月収例】26万4600円＋残業代（21日勤務の場合）
2,淡路町,2019/11/27,東京メトロ丸ノ内線,※土・日・祝がお休みです。,9:00〜17:00 <BR>※残業はほとんどありません。<BR>※休憩は６０分です。,東京都千代田区,206東京,≪3ヶ月後正社員！≫大手損保会社でコツコツ事務＊社員食堂あり,2019/11/26,経理部,＜大手損保会社＞産休・育休取得実績ありの企業さんです♪ランチに嬉しい社員食堂完備の職場ですよ...,東京メトロ千代田線,【専門・高専卒以上】◆事務経験・簿記３級程度の知識がある方歓迎します。<BR>【使用するＯＡ...,"●当社は全国17,000件のお仕事を取り扱っており、毎日100名以上の方が就業を決めています...",2020/11/27,◆開始日相談可能です♪複数路線が利用でき便利！休憩室完備の自社ビル！当社スタッフさん就業中！...,ランチに嬉しい社員食堂完備の職場です！<BR>,新御茶ノ水,【月収例】26万4600円＋残業代（21日勤務の場合）
3,宝町,2019/11/27,都営浅草線,※土・日・祝がお休みです。,9:00〜17:30 <BR>※休憩は６０分です。,東京都中央区,206東京,【未経験でも6ヶ月後社員】賞与年4.5ヶ月分＊非営利団体で事務,2019/11/26,企画調整部,安心安定の非営利団体！落ち着いた雰囲気の職場環境です！<BR>【ＯＡ事務】<BR>会議や委員...,東京メトロ日比谷線,【大卒以上】◆未経験者歓迎！<BR>【使用するＯＡスキル】Ｅｘｃｅｌ（関数）<BR><BR>...,"●当社は全国17,000件のお仕事を取り扱っており、毎日100名以上の方が就業を決めています...",2020/11/27,◆最寄駅から徒歩圏内！複数路線が利用可能！近くにコンビニ・カフェがあり便利！分煙されており快...,落ち着いた雰囲気の職場環境です！<BR>,八丁堀,【月収例】25万9875円＋残業代（21日勤務の場合）
4,宝町,2019/11/27,都営浅草線,※土・日・祝がお休みです。,9:00〜17:30 <BR>※休憩は６０分です。,東京都中央区,206東京,【未経験でも6ヶ月後社員】賞与年4.5ヶ月分＊非営利団体で事務,2019/11/26,企画調整部,安心安定の非営利団体！落ち着いた雰囲気の職場環境です！<BR>【ＯＡ事務】<BR>会議や委員...,東京メトロ日比谷線,【大卒以上】◆未経験者歓迎！<BR>【使用するＯＡスキル】Ｅｘｃｅｌ（関数）<BR><BR>...,"●当社は全国17,000件のお仕事を取り扱っており、毎日100名以上の方が就業を決めています...",2020/11/27,◆最寄駅から徒歩圏内！複数路線が利用可能！近くにコンビニ・カフェがあり便利！分煙されており快...,落ち着いた雰囲気の職場環境です！<BR>,八丁堀,【月収例】25万9875円＋残業代（21日勤務の場合）

In [13]:
df_info_a_3_object = pd.DataFrame({"unique count": list(a_3_object.nunique(dropna=False)), "null count": list(a_3_object.isnull().sum())}, index=list(a_3_object.columns.values))
df_info_a_3_object

                unique count  null count
勤務地　最寄駅2（駅名）             840        8367
掲載期間　開始日                   2           0
勤務地　最寄駅2（沿線名）            219        8367
休日休暇　備考                  752           0
期間・時間　勤務時間              3059           0
勤務地　備考                   736           0
拠点番号                      52           0
お仕事名                    9925           0
期間・時間　勤務開始日               94           0
（派遣先）配属先部署              3574           3
仕事内容                   11086           0
勤務地　最寄駅1（沿線名）            351           0
応募資格                    4385           0
派遣会社のうれしい特典               27           0
掲載期間　終了日                   2           0
お仕事のポイント（仕事PR）          9636           0
（派遣先）職場の雰囲気              866           4
勤務地　最寄駅1（駅名）            1729           0
給与/交通費　備考                556        3556

##### エンコーディングするカテゴリ変数の候補メモ

・~~勤務地　最寄駅2（駅名）~~　　→1があるからいらなそう

・~~掲載期間　開始日・終了日~~ 　→二値へ

・~~勤務地　最寄駅2（沿線名）~~  →駅名があるので、なくても良さげ

★休日休暇　備考

★~~期間・時間　勤務時間~~

★勤務地　備考

・~~拠点番号~~  →番号のみを抽出

・~~お仕事名~~  →ほぼ全部違うから無視
    
・~~期間・時間　勤務開始日~~

★~~（派遣先）配属先部署~~

・~~仕事内容~~  →お仕事名と同じく

・~~勤務地　最寄駅1（沿線名）~~　→駅名があるので、なくても良さげ

★~~応募資格~~

★派遣会社のうれしい特典

・~~お仕事のポイント（仕事PR）~~  →お仕事名と同じく

★（派遣先）職場の雰囲気

★勤務地　最寄駅1（駅名）

★給与/交通費　備考

submit_GBDT_Nan_encodingの時よりも少しエンコーディングする変数を減らす  
あまりにも種類が多いもの（ばらばらなもの）のカラムは消去していくことにする

In [14]:
# trainデータに対してNANをなくす
a_4 = a_3.copy()
a_4["休日休暇　備考"] = a_4["休日休暇　備考"].fillna("missing")
# a_4["期間・時間　勤務時間"] = a_4["期間・時間　勤務時間"].fillna("missing")
a_4["勤務地　備考"] = a_4["勤務地　備考"].fillna("missing")
# a_4["（派遣先）配属先部署"] = a_4["（派遣先）配属先部署"].fillna("missing")
# a_4["応募資格"] = a_4["応募資格"].fillna("missing")
a_4["派遣会社のうれしい特典"] = a_4["派遣会社のうれしい特典"].fillna("missing")
a_4["（派遣先）職場の雰囲気"] = a_4["（派遣先）職場の雰囲気"].fillna("missing")
a_4["勤務地　最寄駅1（駅名）"] = a_4["勤務地　最寄駅1（駅名）"].fillna("missing")
a_4["給与/交通費　備考"] = a_4["給与/交通費　備考"].fillna("missing")

In [15]:
# testデータに対してNANをなくす
t_x_2 = t_x_1.copy()
t_x_2["休日休暇　備考"] = t_x_2["休日休暇　備考"].fillna("missing")
# t_x_2["期間・時間　勤務時間"] = t_x_2["期間・時間　勤務時間"].fillna("missing")
t_x_2["勤務地　備考"] = t_x_2["勤務地　備考"].fillna("missing")
# t_x_2["（派遣先）配属先部署"] = t_x_2["（派遣先）配属先部署"].fillna("missing")
# t_x_2["応募資格"] = t_x_2["応募資格"].fillna("missing")
t_x_2["派遣会社のうれしい特典"] = t_x_2["派遣会社のうれしい特典"].fillna("missing")
t_x_2["（派遣先）職場の雰囲気"] = t_x_2["（派遣先）職場の雰囲気"].fillna("missing")
t_x_2["勤務地　最寄駅1（駅名）"] = t_x_2["勤務地　最寄駅1（駅名）"].fillna("missing")
t_x_2["給与/交通費　備考"] = t_x_2["給与/交通費　備考"].fillna("missing")

In [16]:
# "休日休暇　備考","期間・時間　勤務時間","勤務地　備考","（派遣先）配属先部署","応募資格","派遣会社のうれしい特典","（派遣先）職場の雰囲気","勤務地　最寄駅1（駅名）","給与/交通費　備考"
# ,,,,,,,

In [17]:
from sklearn.preprocessing import LabelEncoder

a_5 = a_4.copy()
t_x_3 = t_x_2.copy()
le1 = LabelEncoder()
# a_5とt_x_3においてラベル付け
le1.fit(pd.concat([a_5["休日休暇　備考"], t_x_3["休日休暇　備考"]], sort=True))
a_5["休日休暇　備考"] = le1.transform(a_5["休日休暇　備考"])
t_x_3["休日休暇　備考"] = le1.transform(t_x_3["休日休暇　備考"])

In [18]:
# le2 = LabelEncoder()
# le2.fit(pd.concat([a_5["期間・時間　勤務時間"], t_x_3["期間・時間　勤務時間"]], sort=True))
# a_5["期間・時間　勤務時間"] = le2.transform(a_5["期間・時間　勤務時間"])
# t_x_3["期間・時間　勤務時間"] = le2.transform(t_x_3["期間・時間　勤務時間"])

le3 = LabelEncoder()
le3.fit(pd.concat([a_5["勤務地　備考"], t_x_3["勤務地　備考"]], sort=True))
a_5["勤務地　備考"] = le3.transform(a_5["勤務地　備考"])
t_x_3["勤務地　備考"] = le3.transform(t_x_3["勤務地　備考"])

# le4 = LabelEncoder()
# le4.fit(pd.concat([a_5["（派遣先）配属先部署"], t_x_3["（派遣先）配属先部署"]], sort=True))
# a_5["（派遣先）配属先部署"] = le4.transform(a_5["（派遣先）配属先部署"])
# t_x_3["（派遣先）配属先部署"] = le4.transform(t_x_3["（派遣先）配属先部署"])

# le5 = LabelEncoder()
# le5.fit(pd.concat([a_5["応募資格"], t_x_3["応募資格"]], sort=True))
# a_5["応募資格"] = le5.transform(a_5["応募資格"])
# t_x_3["応募資格"] = le5.transform(t_x_3["応募資格"])

le6 = LabelEncoder()
le6.fit(pd.concat([a_5["派遣会社のうれしい特典"], t_x_3["派遣会社のうれしい特典"]], sort=True))
a_5["派遣会社のうれしい特典"] = le6.transform(a_5["派遣会社のうれしい特典"])
t_x_3["派遣会社のうれしい特典"] = le6.transform(t_x_3["派遣会社のうれしい特典"])

le7 = LabelEncoder()
le7.fit(pd.concat([a_5["（派遣先）職場の雰囲気"], t_x_3["（派遣先）職場の雰囲気"]], sort=True))
a_5["（派遣先）職場の雰囲気"] = le7.transform(a_5["（派遣先）職場の雰囲気"])
t_x_3["（派遣先）職場の雰囲気"] = le7.transform(t_x_3["（派遣先）職場の雰囲気"])

le8 = LabelEncoder()
le8.fit(pd.concat([a_5["勤務地　最寄駅1（駅名）"], t_x_3["勤務地　最寄駅1（駅名）"]], sort=True))
a_5["勤務地　最寄駅1（駅名）"] = le8.transform(a_5["勤務地　最寄駅1（駅名）"])
t_x_3["勤務地　最寄駅1（駅名）"] = le8.transform(t_x_3["勤務地　最寄駅1（駅名）"])

le9 = LabelEncoder()
le9.fit(pd.concat([a_5["給与/交通費　備考"], t_x_3["給与/交通費　備考"]], sort=True))
a_5["給与/交通費　備考"] = le9.transform(a_5["給与/交通費　備考"])
t_x_3["給与/交通費　備考"] = le9.transform(t_x_3["給与/交通費　備考"])

In [19]:
# trainデータに対して使わないカラムの削除
a_5 = a_5.drop(["勤務地　最寄駅2（駅名）", "勤務地　最寄駅2（沿線名）", "お仕事名", "期間・時間　勤務開始日", "仕事内容", "勤務地　最寄駅1（沿線名）", "お仕事のポイント（仕事PR）", "掲載期間　終了日", "期間・時間　勤務時間", "（派遣先）配属先部署", "応募資格"], axis=1)
a_5.head()

,職場の様子,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,大手企業,交通費別途支給,（派遣先）配属先部署 人数,残業月20時間以上,職種コード,1日7時間以下勤務OK,短時間勤務OK(1日4h以内),...,休日休暇(金曜日),扶養控除内,給与/交通費 給与下限,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし
0,3,0,6.0,0,0,12.0,0,22010,1,0,...,0,0,1550,1,121,477,325,NaN,186,1
1,3,0,2.0,1,0,33.0,0,20020,1,0,...,0,0,1800,1,101,185,832,5.0,424,1
2,3,0,2.0,1,0,33.0,0,20020,1,0,...,0,0,1800,1,101,185,832,5.0,424,1
3,2,0,8.0,0,0,5.0,1,20020,0,0,...,0,0,1650,1,102,777,261,6.0,411,0
4,2,0,8.0,0,0,5.0,1,20020,0,0,...,0,0,1650,1,102,777,261,6.0,411,0

In [20]:
# testデータに対して使わないカラムの削除
t_x_3 = t_x_3.drop(["勤務地　最寄駅2（駅名）", "勤務地　最寄駅2（沿線名）", "お仕事名", "期間・時間　勤務開始日", "仕事内容", "勤務地　最寄駅1（沿線名）", "お仕事のポイント（仕事PR）", "掲載期間　終了日", "期間・時間　勤務時間", "（派遣先）配属先部署", "応募資格"], axis=1)
t_x_3.head()

,職場の様子,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,大手企業,交通費別途支給,（派遣先）配属先部署 人数,残業月20時間以上,職種コード,1日7時間以下勤務OK,短時間勤務OK(1日4h以内),...,休日休暇(金曜日),扶養控除内,給与/交通費 給与下限,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし
0,3,0,6.0,0,0,9.0,0,22010,1,0,...,0,0,1600,1,112,608,773,15.0,325,1
1,3,0,5.0,0,0,11.0,0,22030,1,0,...,0,0,1700,1,102,777,205,1.0,373,0
2,3,0,2.0,1,0,33.0,0,20020,1,0,...,0,0,1800,1,101,185,832,5.0,424,1
3,2,0,8.0,0,0,5.0,1,20020,0,0,...,0,0,1650,1,102,777,261,6.0,411,0
4,2,0,6.0,0,0,8.0,0,20020,1,0,...,0,0,1700,1,102,773,1401,7.0,373,1

In [21]:
# 掲載開始日を０，１にエンコード
# trainデータ
day_mapping = {"2019/11/27": 0, "2019/9/25": 1}
a_5["掲載期間　開始日"] = a_5['掲載期間　開始日'].map(day_mapping)

In [22]:
# testデータ
t_x_3 = t_x_3.replace('2019/10/24', 3)
t_x_3.head()

,職場の様子,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,大手企業,交通費別途支給,（派遣先）配属先部署 人数,残業月20時間以上,職種コード,1日7時間以下勤務OK,短時間勤務OK(1日4h以内),...,休日休暇(金曜日),扶養控除内,給与/交通費 給与下限,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし
0,3,0,6.0,0,0,9.0,0,22010,1,0,...,0,0,1600,1,112,608,773,15.0,325,1
1,3,0,5.0,0,0,11.0,0,22030,1,0,...,0,0,1700,1,102,777,205,1.0,373,0
2,3,0,2.0,1,0,33.0,0,20020,1,0,...,0,0,1800,1,101,185,832,5.0,424,1
3,2,0,8.0,0,0,5.0,1,20020,0,0,...,0,0,1650,1,102,777,261,6.0,411,0
4,2,0,6.0,0,0,8.0,0,20020,1,0,...,0,0,1700,1,102,773,1401,7.0,373,1

In [23]:
# trainデータの拠点番号
func = lambda x: int(x[:3])
a_5["拠点番号"] = a_5["拠点番号"].map(func)
a_5.head()

,職場の様子,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,大手企業,交通費別途支給,（派遣先）配属先部署 人数,残業月20時間以上,職種コード,1日7時間以下勤務OK,短時間勤務OK(1日4h以内),...,休日休暇(金曜日),扶養控除内,給与/交通費 給与下限,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし
0,3,0,6.0,0,0,12.0,0,22010,1,0,...,0,0,1550,1,121,477,325,NaN,186,1
1,3,0,2.0,1,0,33.0,0,20020,1,0,...,0,0,1800,1,101,185,832,5.0,424,1
2,3,0,2.0,1,0,33.0,0,20020,1,0,...,0,0,1800,1,101,185,832,5.0,424,1
3,2,0,8.0,0,0,5.0,1,20020,0,0,...,0,0,1650,1,102,777,261,6.0,411,0
4,2,0,8.0,0,0,5.0,1,20020,0,0,...,0,0,1650,1,102,777,261,6.0,411,0

In [24]:
# testデータの拠点番号
# trainデータの拠点番号
func = lambda x: int(x[:3])
t_x_3["拠点番号"] = t_x_3["拠点番号"].map(func)
t_x_3.head()

,職場の様子,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,大手企業,交通費別途支給,（派遣先）配属先部署 人数,残業月20時間以上,職種コード,1日7時間以下勤務OK,短時間勤務OK(1日4h以内),...,休日休暇(金曜日),扶養控除内,給与/交通費 給与下限,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし
0,3,0,6.0,0,0,9.0,0,22010,1,0,...,0,0,1600,1,112,608,773,15.0,325,1
1,3,0,5.0,0,0,11.0,0,22030,1,0,...,0,0,1700,1,102,777,205,1.0,373,0
2,3,0,2.0,1,0,33.0,0,20020,1,0,...,0,0,1800,1,101,185,832,5.0,424,1
3,2,0,8.0,0,0,5.0,1,20020,0,0,...,0,0,1650,1,102,777,261,6.0,411,0
4,2,0,6.0,0,0,8.0,0,20020,1,0,...,0,0,1700,1,102,773,1401,7.0,373,1

In [25]:
# 予測用データ
submit_x = t_x_3

In [26]:
work_number = submit_x["お仕事No."]
submit_x_test = np.array(submit_x.drop(["お仕事No."], axis=1))
submit_x_test.shape

(3391, 74)

In [27]:
a_5.describe()

,職場の様子,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,大手企業,交通費別途支給,（派遣先）配属先部署 人数,残業月20時間以上,職種コード,1日7時間以下勤務OK,短時間勤務OK(1日4h以内),...,休日休暇(金曜日),扶養控除内,給与/交通費 給与下限,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし
count,15853.000000,15853.000000,13801.000000,15853.000000,15853.000000,13814.000000,15853.000000,15853.000000,15853.000000,15853.000000,...,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,7359.000000,15853.000000,15853.000000
mean,2.946319,0.006813,4.997464,0.237242,0.218129,14.174461,0.064972,20637.698227,0.277802,0.010219,...,0.009903,0.011670,1469.690279,0.991674,137.071848,434.118211,848.275027,7.621008,243.595282,0.729578
std,0.306926,0.082259,2.796697,0.425405,0.412989,23.165115,0.246484,2598.874377,0.447930,0.100574,...,0.099025,0.107398,244.447800,0.090872,55.513015,234.841303,494.809165,4.577798,176.965509,0.444192
min,2.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,20020.000000,0.000000,0.000000,...,0.000000,0.000000,800.000000,0.000000,101.000000,0.000000,0.000000,1.000000,0.000000,0.000000
25%,3.000000,0.000000,3.000000,0.000000,0.000000,5.000000,0.000000,20020.000000,0.000000,0.000000,...,0.000000,0.000000,1300.000000,1.000000,103.000000,232.000000,430.000000,5.000000,72.000000,0.000000
50%,3.000000,0.000000,5.000000,0.000000,0.000000,8.000000,0.000000,20030.000000,0.000000,0.000000,...,0.000000,0.000000,1500.000000,1.000000,109.000000,404.000000,882.000000,7.000000,269.000000,1.000000
75%,3.000000,0.000000,7.000000,0.000000,0.000000,15.000000,0.000000,20710.000000,1.000000,0.000000,...,0.000000,0.000000,1650.000000,1.000000,201.000000,665.000000,1228.000000,10.000000,409.000000,1.000000
max,4.000000,1.000000,10.000000,1.000000,1.000000,574.000000,1.000000,80310.000000,1.000000,1.000000,...,1.000000,1.000000,2850.000000,1.000000,631.000000,936.000000,1748.000000,46.000000,575.000000,1.000000

In [28]:
# 前処理後データ
application_after = a_5
application_after.head()

,職場の様子,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,大手企業,交通費別途支給,（派遣先）配属先部署 人数,残業月20時間以上,職種コード,1日7時間以下勤務OK,短時間勤務OK(1日4h以内),...,休日休暇(金曜日),扶養控除内,給与/交通費 給与下限,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし
0,3,0,6.0,0,0,12.0,0,22010,1,0,...,0,0,1550,1,121,477,325,NaN,186,1
1,3,0,2.0,1,0,33.0,0,20020,1,0,...,0,0,1800,1,101,185,832,5.0,424,1
2,3,0,2.0,1,0,33.0,0,20020,1,0,...,0,0,1800,1,101,185,832,5.0,424,1
3,2,0,8.0,0,0,5.0,1,20020,0,0,...,0,0,1650,1,102,777,261,6.0,411,0
4,2,0,8.0,0,0,5.0,1,20020,0,0,...,0,0,1650,1,102,777,261,6.0,411,0

In [72]:
application_after.columns

Index(['職場の様子', '休日休暇(月曜日)', '（派遣先）配属先部署　男女比　男', '大手企業', '交通費別途支給',
       '（派遣先）配属先部署　人数', '残業月20時間以上', '職種コード', '1日7時間以下勤務OK', '短時間勤務OK(1日4h以内)',
       '駅から徒歩5分以内', '学校・公的機関（官公庁）', '土日祝のみ勤務', '掲載期間　開始日', 'Wordのスキルを活かす',
       '勤務地　最寄駅1（分）', 'お仕事No.', '派遣スタッフ活躍中', '大量募集', 'Accessのスキルを活かす',
       '休日休暇(火曜日)', '平日休みあり', '勤務地　最寄駅2（駅からの交通手段）', '休日休暇　備考', 'フラグオプション選択',
       '期間・時間　勤務期間', '派遣形態', '週2・3日OK', '勤務先公開', 'Excelのスキルを活かす', '16時前退社OK',
       '正社員登用あり', '残業月20時間未満', '勤務地　備考', '英語力不要', '拠点番号', '休日休暇(日曜日)',
       '社員食堂あり', '10時以降出社OK', '英語以外の語学力を活かす', '休日休暇(祝日)', '外資系企業', '服装自由',
       'PowerPointのスキルを活かす', '（派遣先）配属先部署　男女比　女', '休日休暇(土曜日)', '休日休暇(木曜日)',
       '（派遣先）配属先部署　平均年齢', '英語力を活かす', '会社概要　業界コード', '勤務地　都道府県コード', 'PCスキル不要',
       '車通勤OK', '制服あり', '休日休暇(水曜日)', '仕事の仕方', '勤務地　最寄駅1（駅からの交通手段）', '紹介予定派遣',
       'シフト勤務', '経験者優遇', '週4日勤務', '未経験OK', '派遣会社のうれしい特典', '土日祝休み',
       '給与/交通費　交通費', '休日休暇(金曜日)', '扶養控除内', '給与/交通費　給与下限', 'オフィスが禁煙・分煙',
       '勤務地　市区町村コード', '（派遣先）職場の雰囲気', '勤務地　最寄駅1（駅名）', '勤務地　最寄駅2（分）',
       '給与/交通費　備考', '残業なし'],
      dtype='object')

### yの読み込み

In [29]:
df_y = pd.read_csv("train_y.csv")
df_y.head()

       お仕事No.    応募数 合計
0  2203566799  1.945910
1  2203546900  3.951244
2  2203546900  3.295837
3  2203545344  3.970292
4  2203545344  3.784190

In [30]:
len(df_y)

15853

# 回帰問題

In [31]:
y = df_y["応募数 合計"]
X = application_after.drop(["お仕事No."], axis=1)

In [32]:
y_array = np.array(y)
X_array = np.array(X)

In [33]:
print("y_array: ", y_array.shape)
print("X_array: ", X_array.shape)

y_array:  (15853,)
X_array:  (15853, 74)

In [34]:
# train/testに分割する
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_array, y_array, test_size=0.4, random_state=0)

In [35]:
print("X_train: ", X_train.shape)
print("y_train: ", y_train.shape)
print("X_test: ", X_test.shape)
print("y_test: ", y_test.shape)

X_train:  (9511, 74)
y_train:  (9511,)
X_test:  (6342, 74)
y_test:  (6342,)

# GBDT LIghtGBM

パラメータチューニングの際に参考にしたページ  
https://nykergoto.hatenablog.jp/entry/2019/03/29/%E5%8B%BE%E9%85%8D%E3%83%96%E3%83%BC%E3%82%B9%E3%83%86%E3%82%A3%E3%83%B3%E3%82%B0%E3%81%A7%E5%A4%A7%E4%BA%8B%E3%81%AA%E3%83%91%E3%83%A9%E3%83%A1%E3%83%BC%E3%82%BF%E3%81%AE%E6%B0%97%E6%8C%81%E3%81%A1

In [36]:
import lightgbm as lgb

In [37]:
# 特徴量と目的変数をlightgbmのデータ構造に変換する
lgb_train = lgb.Dataset(X_train, y_train)
lgb_eval = lgb.Dataset(X_test, y_test)

In [83]:
# ハイパーパラメータの設定
# "colsample_bytree"を変更
params = {"colsample_bytree": 0.7, "seed": 71, "verbose": 0, "metrics": "rmse"}
num_round = 265
# num_round = 400

#### パラメータチューニングに関するメモ  
max_depth: 増やしても精度が上がらなかった  
colsample_bytree: 小さい方が良いみたい(0.7より小さいと精度が上がらない)

In [84]:
# 学習の実行
# バリデーションデータもモデルに渡し、学習の進行とともにスコアがどう変わるかモニタリングする
model = lgb.train(params, lgb_train, num_boost_round = num_round, valid_names = ["train", "valid"], valid_sets = [lgb_train, lgb_eval])

[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.043998 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[1]	train's rmse: 0.776739	valid's rmse: 0.750801
[2]	train's rmse: 0.760365	valid's rmse: 0.735904
[3]	train's rmse: 0.746449	valid's rmse: 0.723073
[4]	train's rmse: 0.73361	valid's rmse: 0.711734
[5]	train's rmse: 0.72246	valid's rmse: 0.702609
[6]	train's rmse: 0.712923	valid's rmse: 0.695686
[7]	train's rmse: 0.705354	valid's rmse: 0.690519
[8]	train's rmse: 0.698724	valid's rmse: 0.686424
[9]	train's rmse: 0.691563	valid's rmse: 0.681306
[10]	train's rmse: 0.684146	valid's rmse: 0.675548
[11]	train's rmse: 0.678935	valid's rmse: 0.672041
[12]	train's rmse: 0.672332	valid's rmse: 0.667144
[13]	train's rmse: 0.666531	valid's rmse: 0.66273
[14]	train's rmse: 0.661053	valid's rmse: 0.659313
[15]	train's rmse: 0.656313	valid's rmse: 0.6555
[16]	train's rmse: 0.652412	valid's rmse: 0.652679
[17]	train's rmse: 0.648698	valid's rmse: 0.650921
[18]	train's rmse: 0.644754	valid's rmse: 0.648272
[19]	train's rmse: 0.641076	valid's rmse: 0.646025
[20]	train's rmse: 0.637393	valid's rmse: 0.644311
[21]	train's rmse: 0.634594	valid's rmse: 0.643331
[22]	train's rmse: 0.63172	valid's rmse: 0.641858
[23]	train's rmse: 0.629104	valid's rmse: 0.64057
[24]	train's rmse: 0.626495	valid's rmse: 0.639346
[25]	train's rmse: 0.623738	valid's rmse: 0.637925
[26]	train's rmse: 0.62075	valid's rmse: 0.63586
[27]	train's rmse: 0.617962	valid's rmse: 0.634361
[28]	train's rmse: 0.615222	valid's rmse: 0.63327
[29]	train's rmse: 0.61173	valid's rmse: 0.63095
[30]	train's rmse: 0.609633	valid's rmse: 0.630151
[31]	train's rmse: 0.607309	valid's rmse: 0.62943
[32]	train's rmse: 0.605099	valid's rmse: 0.628827
[33]	train's rmse: 0.602751	valid's rmse: 0.627804
[34]	train's rmse: 0.60099	valid's rmse: 0.626998
[35]	train's rmse: 0.598249	valid's rmse: 0.62541
[36]	train's rmse: 0.595973	valid's rmse: 0.624443
[37]	train's rmse: 0.59358	valid's rmse: 0.62352
[38]	train's rmse: 0.591279	valid's rmse: 0.622595
[39]	train's rmse: 0.589386	valid's rmse: 0.621864
[40]	train's rmse: 0.587361	valid's rmse: 0.621405
[41]	train's rmse: 0.585543	valid's rmse: 0.620389
[42]	train's rmse: 0.583711	valid's rmse: 0.619618
[43]	train's rmse: 0.581926	valid's rmse: 0.618875
[44]	train's rmse: 0.580169	valid's rmse: 0.618149
[45]	train's rmse: 0.578579	valid's rmse: 0.617427
[46]	train's rmse: 0.577189	valid's rmse: 0.61718
[47]	train's rmse: 0.575319	valid's rmse: 0.616424
[48]	train's rmse: 0.574023	valid's rmse: 0.616114
[49]	train's rmse: 0.572092	valid's rmse: 0.615471
[50]	train's rmse: 0.570616	valid's rmse: 0.615276
[51]	train's rmse: 0.568854	valid's rmse: 0.614982
[52]	train's rmse: 0.567469	valid's rmse: 0.614524
[53]	train's rmse: 0.566014	valid's rmse: 0.614349
[54]	train's rmse: 0.564837	valid's rmse: 0.613783
[55]	train's rmse: 0.563186	valid's rmse: 0.613502
[56]	train's rmse: 0.56149	valid's rmse: 0.612949
[57]	train's rmse: 0.560153	valid's rmse: 0.612564
[58]	train's rmse: 0.558624	valid's rmse: 0.611879
[59]	train's rmse: 0.557485	valid's rmse: 0.611802
[60]	train's rmse: 0.556322	valid's rmse: 0.611481
[61]	train's rmse: 0.555185	valid's rmse: 0.611266
[62]	train's rmse: 0.553877	valid's rmse: 0.611022
[63]	train's rmse: 0.552881	valid's rmse: 0.61073
[64]	train's rmse: 0.551555	valid's rmse: 0.61059
[65]	train's rmse: 0.549948	valid's rmse: 0.610308
[66]	train's rmse: 0.548911	valid's rmse: 0.609886
[67]	train's rmse: 0.547898	valid's rmse: 0.609411
[68]	train's rmse: 0.546645	valid's rmse: 0.609059
[69]	train's rmse: 0.545543	valid's rmse: 0.609077
[70]	train's rmse: 0.544144	valid's rmse: 0.608565
[71]	train's rmse: 0.543231	valid's rmse: 0.608544
[72]	train's rmse: 0.542258	valid's rmse: 0.608232
[73]	train's rmse: 0.541032	valid's rmse: 0.608046
[74]	train's rmse: 0.5397	valid's rmse: 0.607638
[75]	train's rmse: 0.538741	valid's rmse: 0.607378
[76]	train's rmse: 0.537628	valid's rmse: 0.607042
[77]	train's rmse: 0.536506	valid's rmse: 0.606893
[78]	train's rmse: 0.535234	valid's rmse: 0.606193
[79]	train's rmse: 0.533893	valid's rmse: 0.605721
[80]	train's rmse: 0.53268	valid's rmse: 0.605486
[81]	train's rmse: 0.531768	valid's rmse: 0.605297
[82]	train's rmse: 0.530831	valid's rmse: 0.605079
[83]	train's rmse: 0.5299	valid's rmse: 0.604807
[84]	train's rmse: 0.528959	valid's rmse: 0.60483
[85]	train's rmse: 0.52801	valid's rmse: 0.604471
[86]	train's rmse: 0.526628	valid's rmse: 0.604043
[87]	train's rmse: 0.525256	valid's rmse: 0.603612
[88]	train's rmse: 0.524203	valid's rmse: 0.603415
[89]	train's rmse: 0.523233	valid's rmse: 0.603063
[90]	train's rmse: 0.52202	valid's rmse: 0.602494
[91]	train's rmse: 0.52121	valid's rmse: 0.602244
[92]	train's rmse: 0.520249	valid's rmse: 0.601922
[93]	train's rmse: 0.519453	valid's rmse: 0.601914
[94]	train's rmse: 0.518228	valid's rmse: 0.601661
[95]	train's rmse: 0.517055	valid's rmse: 0.601351
[96]	train's rmse: 0.515917	valid's rmse: 0.601191
[97]	train's rmse: 0.514474	valid's rmse: 0.600745
[98]	train's rmse: 0.513298	valid's rmse: 0.600545
[99]	train's rmse: 0.512443	valid's rmse: 0.600275
[100]	train's rmse: 0.511617	valid's rmse: 0.60003
[101]	train's rmse: 0.510826	valid's rmse: 0.599907
[102]	train's rmse: 0.509975	valid's rmse: 0.599567
[103]	train's rmse: 0.509119	valid's rmse: 0.599574
[104]	train's rmse: 0.508134	valid's rmse: 0.599348
[105]	train's rmse: 0.507419	valid's rmse: 0.599303
[106]	train's rmse: 0.506835	valid's rmse: 0.599301
[107]	train's rmse: 0.505899	valid's rmse: 0.598964
[108]	train's rmse: 0.505209	valid's rmse: 0.59887
[109]	train's rmse: 0.504357	valid's rmse: 0.598682
[110]	train's rmse: 0.503686	valid's rmse: 0.598646
[111]	train's rmse: 0.502895	valid's rmse: 0.598472
[112]	train's rmse: 0.502039	valid's rmse: 0.598266
[113]	train's rmse: 0.501183	valid's rmse: 0.598033
[114]	train's rmse: 0.500296	valid's rmse: 0.597896
[115]	train's rmse: 0.49971	valid's rmse: 0.597835
[116]	train's rmse: 0.498715	valid's rmse: 0.597558
[117]	train's rmse: 0.498145	valid's rmse: 0.597461
[118]	train's rmse: 0.497363	valid's rmse: 0.597163
[119]	train's rmse: 0.496621	valid's rmse: 0.597092
[120]	train's rmse: 0.495763	valid's rmse: 0.597152
[121]	train's rmse: 0.494849	valid's rmse: 0.597039
[122]	train's rmse: 0.494266	valid's rmse: 0.596885
[123]	train's rmse: 0.493667	valid's rmse: 0.596877
[124]	train's rmse: 0.492922	valid's rmse: 0.596688
[125]	train's rmse: 0.49238	valid's rmse: 0.596534
[126]	train's rmse: 0.491433	valid's rmse: 0.596494
[127]	train's rmse: 0.490794	valid's rmse: 0.596213
[128]	train's rmse: 0.490085	valid's rmse: 0.596226
[129]	train's rmse: 0.489615	valid's rmse: 0.596159
[130]	train's rmse: 0.488912	valid's rmse: 0.596073
[131]	train's rmse: 0.4882	valid's rmse: 0.596002
[132]	train's rmse: 0.487598	valid's rmse: 0.595916
[133]	train's rmse: 0.486566	valid's rmse: 0.595671
[134]	train's rmse: 0.486033	valid's rmse: 0.595684
[135]	train's rmse: 0.485359	valid's rmse: 0.595425
[136]	train's rmse: 0.484518	valid's rmse: 0.595158
[137]	train's rmse: 0.483852	valid's rmse: 0.595254
[138]	train's rmse: 0.482992	valid's rmse: 0.595092
[139]	train's rmse: 0.481876	valid's rmse: 0.594901
[140]	train's rmse: 0.481086	valid's rmse: 0.594643
[141]	train's rmse: 0.480114	valid's rmse: 0.594822
[142]	train's rmse: 0.4796	valid's rmse: 0.594745
[143]	train's rmse: 0.478901	valid's rmse: 0.594613
[144]	train's rmse: 0.478396	valid's rmse: 0.59473
[145]	train's rmse: 0.477854	valid's rmse: 0.594591
[146]	train's rmse: 0.477377	valid's rmse: 0.594441
[147]	train's rmse: 0.476603	valid's rmse: 0.594246
[148]	train's rmse: 0.475973	valid's rmse: 0.594127
[149]	train's rmse: 0.475477	valid's rmse: 0.594032
[150]	train's rmse: 0.47453	valid's rmse: 0.593926
[151]	train's rmse: 0.473562	valid's rmse: 0.59377
[152]	train's rmse: 0.473096	valid's rmse: 0.593752
[153]	train's rmse: 0.472626	valid's rmse: 0.593699
[154]	train's rmse: 0.471875	valid's rmse: 0.59369
[155]	train's rmse: 0.471036	valid's rmse: 0.593642
[156]	train's rmse: 0.470062	valid's rmse: 0.593442
[157]	train's rmse: 0.469585	valid's rmse: 0.593257
[158]	train's rmse: 0.468975	valid's rmse: 0.593457
[159]	train's rmse: 0.468079	valid's rmse: 0.593382

[160]	train's rmse: 0.467365	valid's rmse: 0.593236
[161]	train's rmse: 0.466942	valid's rmse: 0.59317
[162]	train's rmse: 0.466477	valid's rmse: 0.593278
[163]	train's rmse: 0.466068	valid's rmse: 0.593163
[164]	train's rmse: 0.465482	valid's rmse: 0.593061
[165]	train's rmse: 0.464853	valid's rmse: 0.593076
[166]	train's rmse: 0.464308	valid's rmse: 0.59301
[167]	train's rmse: 0.46361	valid's rmse: 0.593028
[168]	train's rmse: 0.463232	valid's rmse: 0.592948
[169]	train's rmse: 0.462517	valid's rmse: 0.592769
[170]	train's rmse: 0.462083	valid's rmse: 0.592613
[171]	train's rmse: 0.461677	valid's rmse: 0.592596
[172]	train's rmse: 0.460952	valid's rmse: 0.592406
[173]	train's rmse: 0.460138	valid's rmse: 0.592329
[174]	train's rmse: 0.459784	valid's rmse: 0.592272
[175]	train's rmse: 0.459347	valid's rmse: 0.592311
[176]	train's rmse: 0.458614	valid's rmse: 0.591994
[177]	train's rmse: 0.45822	valid's rmse: 0.592179
[178]	train's rmse: 0.457663	valid's rmse: 0.592026
[179]	train's rmse: 0.457208	valid's rmse: 0.591973
[180]	train's rmse: 0.456694	valid's rmse: 0.592046
[181]	train's rmse: 0.45625	valid's rmse: 0.592005
[182]	train's rmse: 0.455683	valid's rmse: 0.59196
[183]	train's rmse: 0.454968	valid's rmse: 0.591843
[184]	train's rmse: 0.454406	valid's rmse: 0.591622
[185]	train's rmse: 0.453842	valid's rmse: 0.591568
[186]	train's rmse: 0.453233	valid's rmse: 0.591548
[187]	train's rmse: 0.452834	valid's rmse: 0.591645
[188]	train's rmse: 0.452456	valid's rmse: 0.591619
[189]	train's rmse: 0.452038	valid's rmse: 0.591658
[190]	train's rmse: 0.451464	valid's rmse: 0.591699
[191]	train's rmse: 0.450677	valid's rmse: 0.591767
[192]	train's rmse: 0.450254	valid's rmse: 0.591792
[193]	train's rmse: 0.449753	valid's rmse: 0.591682
[194]	train's rmse: 0.449016	valid's rmse: 0.591787
[195]	train's rmse: 0.448242	valid's rmse: 0.591627
[196]	train's rmse: 0.447647	valid's rmse: 0.591571
[197]	train's rmse: 0.447242	valid's rmse: 0.591671
[198]	train's rmse: 0.446727	valid's rmse: 0.591531
[199]	train's rmse: 0.446277	valid's rmse: 0.591398
[200]	train's rmse: 0.445719	valid's rmse: 0.591338
[201]	train's rmse: 0.44528	valid's rmse: 0.591346
[202]	train's rmse: 0.444655	valid's rmse: 0.591386
[203]	train's rmse: 0.444163	valid's rmse: 0.591151
[204]	train's rmse: 0.443686	valid's rmse: 0.591292
[205]	train's rmse: 0.443375	valid's rmse: 0.591404
[206]	train's rmse: 0.442916	valid's rmse: 0.59131
[207]	train's rmse: 0.442402	valid's rmse: 0.591211
[208]	train's rmse: 0.441823	valid's rmse: 0.591099
[209]	train's rmse: 0.441361	valid's rmse: 0.591048
[210]	train's rmse: 0.440785	valid's rmse: 0.591052
[211]	train's rmse: 0.440364	valid's rmse: 0.591104
[212]	train's rmse: 0.439664	valid's rmse: 0.590947
[213]	train's rmse: 0.438921	valid's rmse: 0.590867
[214]	train's rmse: 0.43865	valid's rmse: 0.590887
[215]	train's rmse: 0.438086	valid's rmse: 0.590756
[216]	train's rmse: 0.437486	valid's rmse: 0.590673
[217]	train's rmse: 0.436943	valid's rmse: 0.590607
[218]	train's rmse: 0.436674	valid's rmse: 0.590528
[219]	train's rmse: 0.436288	valid's rmse: 0.590513
[220]	train's rmse: 0.43583	valid's rmse: 0.590458
[221]	train's rmse: 0.435346	valid's rmse: 0.590301
[222]	train's rmse: 0.434996	valid's rmse: 0.590262
[223]	train's rmse: 0.434511	valid's rmse: 0.590296
[224]	train's rmse: 0.433842	valid's rmse: 0.590445
[225]	train's rmse: 0.433517	valid's rmse: 0.590361
[226]	train's rmse: 0.433057	valid's rmse: 0.590331
[227]	train's rmse: 0.432745	valid's rmse: 0.590435
[228]	train's rmse: 0.432275	valid's rmse: 0.590398
[229]	train's rmse: 0.43184	valid's rmse: 0.590494
[230]	train's rmse: 0.431511	valid's rmse: 0.590466
[231]	train's rmse: 0.431003	valid's rmse: 0.590522
[232]	train's rmse: 0.430733	valid's rmse: 0.590463
[233]	train's rmse: 0.430394	valid's rmse: 0.590395
[234]	train's rmse: 0.430031	valid's rmse: 0.59049
[235]	train's rmse: 0.429796	valid's rmse: 0.590534
[236]	train's rmse: 0.429468	valid's rmse: 0.590597
[237]	train's rmse: 0.429081	valid's rmse: 0.590494
[238]	train's rmse: 0.428723	valid's rmse: 0.590405
[239]	train's rmse: 0.428377	valid's rmse: 0.590409
[240]	train's rmse: 0.427948	valid's rmse: 0.590395
[241]	train's rmse: 0.427522	valid's rmse: 0.590285
[242]	train's rmse: 0.427172	valid's rmse: 0.590409
[243]	train's rmse: 0.426606	valid's rmse: 0.590347
[244]	train's rmse: 0.42623	valid's rmse: 0.590446
[245]	train's rmse: 0.42575	valid's rmse: 0.590484
[246]	train's rmse: 0.425293	valid's rmse: 0.590381
[247]	train's rmse: 0.424984	valid's rmse: 0.590373
[248]	train's rmse: 0.424638	valid's rmse: 0.590351
[249]	train's rmse: 0.424172	valid's rmse: 0.590444
[250]	train's rmse: 0.4239	valid's rmse: 0.590421
[251]	train's rmse: 0.423576	valid's rmse: 0.590382
[252]	train's rmse: 0.423271	valid's rmse: 0.590392
[253]	train's rmse: 0.422769	valid's rmse: 0.590396
[254]	train's rmse: 0.422271	valid's rmse: 0.590321
[255]	train's rmse: 0.42197	valid's rmse: 0.590299
[256]	train's rmse: 0.421686	valid's rmse: 0.590235
[257]	train's rmse: 0.421167	valid's rmse: 0.590226
[258]	train's rmse: 0.420739	valid's rmse: 0.590167
[259]	train's rmse: 0.420159	valid's rmse: 0.590231
[260]	train's rmse: 0.419754	valid's rmse: 0.590234
[261]	train's rmse: 0.419284	valid's rmse: 0.590032
[262]	train's rmse: 0.418778	valid's rmse: 0.589876
[263]	train's rmse: 0.418314	valid's rmse: 0.589857
[264]	train's rmse: 0.418005	valid's rmse: 0.589797
[265]	train's rmse: 0.417623	valid's rmse: 0.589763

In [66]:
# バリデーションデータでのスコアの確認
va_pred = model.predict(X_test)
# 負の値は0へ
va_pred_0 = [0 if i <= 0 else i for i in va_pred]

In [67]:
from sklearn.metrics import mean_squared_error
score = np.sqrt(mean_squared_error(va_pred_0, y_test))
print(score)

0.5892398722162967

In [68]:
# 予測
pred = model.predict(submit_x_test)
pred_0 = [0 if i <= 0 else i for i in pred]

### GDBT(NaNのまま，encoding多め): 0.6044626823948162

### GDBT(NaNのまま): 0.6042383633971182

### GBDT(NaNを-99に変換): 0.610822959180329

### ランダムフォレスト: 0.6326244864434752

# テストデータで予測

In [69]:
pred_df = pd.DataFrame(pred_0, columns=['応募数 合計'])
pred_df.head()

     応募数 合計
0  2.385892
1  3.230068
2  3.318403
3  3.770081
4  2.304754

In [70]:
submit = pd.concat([work_number, pred_df], axis=1)
submit.head()

       お仕事No.    応募数 合計
0  2203556553  2.385892
1  2203515280  3.230068
2  2203546900  3.318403
3  2203545344  3.770081
4  2203557987  2.304754

In [71]:
submit.to_csv("submit_LightGBM_NaN_encoding_2_0_tuning.csv", index=False, encoding='utf_8_sig')