# 取り組んだ軌跡：https://github.com/NatsukiH/apply_prediction

最終の精度: 0.5999766265357284

# 前処理

In [1]:
import numpy as np
import pandas as pd
import sklearn

In [2]:
# 読み込み
application = pd.read_csv("train_x.csv")
application.head()

C:\Users\natsu\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (114) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,職場の様子,（紹介予定）入社後の雇用形態,勤務地 最寄駅3（駅名）,勤務地固定,休日休暇(月曜日),応募先 名称,（派遣先）配属先部署 男女比 男,勤務地 最寄駅3（沿線名）,（派遣先）勤務先写真コメント,勤務地 最寄駅3（分）,...,未使用.13,（紹介予定）待遇・福利厚生,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,応募拠点,給与/交通費 備考,残業なし,これまでの採用者例,期間･時間 備考,（派遣先）概要 勤務先名（フリガナ）
0,3,NaN,NaN,1,0,NaN,6.0,NaN,NaN,NaN,...,NaN,NaN,北千住,NaN,NaN,【月収例】19万5300円＋残業代（21日勤務の場合）,1,NaN,◆開始日はご相談可能です！詳しくはお問い合わせください！,NaN
1,3,1.0,NaN,1,0,NaN,2.0,NaN,NaN,NaN,...,NaN,完備,新御茶ノ水,5.0,NaN,【月収例】26万4600円＋残業代（21日勤務の場合）,1,NaN,NaN,NaN
2,3,1.0,NaN,1,0,NaN,2.0,NaN,NaN,NaN,...,NaN,完備,新御茶ノ水,5.0,NaN,【月収例】26万4600円＋残業代（21日勤務の場合）,1,NaN,NaN,NaN
3,2,1.0,NaN,1,0,NaN,8.0,NaN,NaN,NaN,...,NaN,完備,八丁堀,6.0,NaN,【月収例】25万9875円＋残業代（21日勤務の場合）,0,NaN,◆開始日はご相談可能です！詳しくはお問い合わせください！,NaN
4,2,1.0,NaN,1,0,NaN,8.0,NaN,NaN,NaN,...,NaN,完備,八丁堀,6.0,NaN,【月収例】25万9875円＋残業代（21日勤務の場合）,0,NaN,◆開始日はご相談可能です！詳しくはお問い合わせください！,NaN

In [3]:
application.describe()

,職場の様子,（紹介予定）入社後の雇用形態,勤務地 最寄駅3（駅名）,勤務地固定,休日休暇(月曜日),応募先 名称,（派遣先）配属先部署 男女比 男,勤務地 最寄駅3（沿線名）,（派遣先）勤務先写真コメント,勤務地 最寄駅3（分）,...,オフィスが禁煙・分煙,応募先 所在地 市区町村,仕事写真（下） 写真1 コメント,勤務地 市区町村コード,未使用.13,勤務地 最寄駅2（分）,応募拠点,残業なし,これまでの採用者例,（派遣先）概要 勤務先名（フリガナ）
count,15853.000000,2742.000000,0.0,15853.0,15853.000000,0.0,13801.000000,0.0,0.0,0.0,...,15853.000000,0.0,0.0,15853.000000,0.0,7359.000000,0.0,15853.000000,0.0,0.0
mean,2.946319,1.303793,NaN,1.0,0.006813,NaN,4.997464,NaN,NaN,NaN,...,0.991674,NaN,NaN,137.071848,NaN,7.621008,NaN,0.729578,NaN,NaN
std,0.306926,0.493645,NaN,0.0,0.082259,NaN,2.796697,NaN,NaN,NaN,...,0.090872,NaN,NaN,55.513015,NaN,4.577798,NaN,0.444192,NaN,NaN
min,2.000000,0.000000,NaN,1.0,0.000000,NaN,0.000000,NaN,NaN,NaN,...,0.000000,NaN,NaN,101.000000,NaN,1.000000,NaN,0.000000,NaN,NaN
25%,3.000000,1.000000,NaN,1.0,0.000000,NaN,3.000000,NaN,NaN,NaN,...,1.000000,NaN,NaN,103.000000,NaN,5.000000,NaN,0.000000,NaN,NaN
50%,3.000000,1.000000,NaN,1.0,0.000000,NaN,5.000000,NaN,NaN,NaN,...,1.000000,NaN,NaN,109.000000,NaN,7.000000,NaN,1.000000,NaN,NaN
75%,3.000000,2.000000,NaN,1.0,0.000000,NaN,7.000000,NaN,NaN,NaN,...,1.000000,NaN,NaN,201.000000,NaN,10.000000,NaN,1.000000,NaN,NaN
max,4.000000,2.000000,NaN,1.0,1.000000,NaN,10.000000,NaN,NaN,NaN,...,1.000000,NaN,NaN,631.000000,NaN,46.000000,NaN,1.000000,NaN,NaN

### 全てnanのcolumnを削除してみる

In [4]:
# 全てnanのcolumnを削除
a_1 = application.dropna(how='all', axis=1)
a_1.head()

,職場の様子,（紹介予定）入社後の雇用形態,勤務地固定,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,勤務地 最寄駅2（駅名）,大手企業,（紹介予定）雇用形態備考,週1日からOK,交通費別途支給,...,WEB登録OK,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,（紹介予定）待遇・福利厚生,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし,期間･時間 備考
0,3,NaN,1,0,6.0,NaN,0,NaN,0,0,...,1,1,121,当社スタッフ活躍中です！<BR>,NaN,北千住,NaN,【月収例】19万5300円＋残業代（21日勤務の場合）,1,◆開始日はご相談可能です！詳しくはお問い合わせください！
1,3,1.0,1,0,2.0,淡路町,1,正社員,0,0,...,1,1,101,ランチに嬉しい社員食堂完備の職場です！<BR>,完備,新御茶ノ水,5.0,【月収例】26万4600円＋残業代（21日勤務の場合）,1,NaN
2,3,1.0,1,0,2.0,淡路町,1,正社員,0,0,...,1,1,101,ランチに嬉しい社員食堂完備の職場です！<BR>,完備,新御茶ノ水,5.0,【月収例】26万4600円＋残業代（21日勤務の場合）,1,NaN
3,2,1.0,1,0,8.0,宝町,0,正社員,0,0,...,1,1,102,落ち着いた雰囲気の職場環境です！<BR>,完備,八丁堀,6.0,【月収例】25万9875円＋残業代（21日勤務の場合）,0,◆開始日はご相談可能です！詳しくはお問い合わせください！
4,2,1.0,1,0,8.0,宝町,0,正社員,0,0,...,1,1,102,落ち着いた雰囲気の職場環境です！<BR>,完備,八丁堀,6.0,【月収例】25万9875円＋残業代（21日勤務の場合）,0,◆開始日はご相談可能です！詳しくはお問い合わせください！

In [5]:
a_1.nunique(dropna=False)

職場の様子                  3
（紹介予定）入社後の雇用形態         4
勤務地固定                  1
休日休暇(月曜日)              2
（派遣先）配属先部署　男女比　男      12
                    ...
勤務地　最寄駅1（駅名）        1729
勤務地　最寄駅2（分）           33
給与/交通費　備考            556
残業なし                   2
期間･時間　備考               9
Length: 127, dtype: int64

### すべて同じ値の列は消去してみる

In [6]:
# 各行においてユニークな値のリスト
nunipue_count_list = list(a_1.nunique(dropna=False))
# 列名のリスト
a_1_columns_list = a_1.columns.values
# ユニークな値が1つだけの行を除外する
a_2 = a_1.copy()

for index in range(len(nunipue_count_list)):
#     ユニークな値が1つだけの時
    if nunipue_count_list[index] == 1:
        column_name = a_1_columns_list[index]
        a_2 = a_2.drop([column_name], axis=1)
        
a_2.nunique(dropna=False)

職場の様子                  3
（紹介予定）入社後の雇用形態         4
休日休暇(月曜日)              2
（派遣先）配属先部署　男女比　男      12
勤務地　最寄駅2（駅名）         840
                    ...
勤務地　最寄駅1（駅名）        1729
勤務地　最寄駅2（分）           33
給与/交通費　備考            556
残業なし                   2
期間･時間　備考               9
Length: 97, dtype: int64

In [7]:
a_2.head()

,職場の様子,（紹介予定）入社後の雇用形態,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,勤務地 最寄駅2（駅名）,大手企業,（紹介予定）雇用形態備考,交通費別途支給,（派遣先）配属先部署 人数,残業月20時間以上,...,給与/交通費 給与下限,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,（紹介予定）待遇・福利厚生,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし,期間･時間 備考
0,3,NaN,0,6.0,NaN,0,NaN,0,12.0,0,...,1550,1,121,当社スタッフ活躍中です！<BR>,NaN,北千住,NaN,【月収例】19万5300円＋残業代（21日勤務の場合）,1,◆開始日はご相談可能です！詳しくはお問い合わせください！
1,3,1.0,0,2.0,淡路町,1,正社員,0,33.0,0,...,1800,1,101,ランチに嬉しい社員食堂完備の職場です！<BR>,完備,新御茶ノ水,5.0,【月収例】26万4600円＋残業代（21日勤務の場合）,1,NaN
2,3,1.0,0,2.0,淡路町,1,正社員,0,33.0,0,...,1800,1,101,ランチに嬉しい社員食堂完備の職場です！<BR>,完備,新御茶ノ水,5.0,【月収例】26万4600円＋残業代（21日勤務の場合）,1,NaN
3,2,1.0,0,8.0,宝町,0,正社員,0,5.0,1,...,1650,1,102,落ち着いた雰囲気の職場環境です！<BR>,完備,八丁堀,6.0,【月収例】25万9875円＋残業代（21日勤務の場合）,0,◆開始日はご相談可能です！詳しくはお問い合わせください！
4,2,1.0,0,8.0,宝町,0,正社員,0,5.0,1,...,1650,1,102,落ち着いた雰囲気の職場環境です！<BR>,完備,八丁堀,6.0,【月収例】25万9875円＋残業代（21日勤務の場合）,0,◆開始日はご相談可能です！詳しくはお問い合わせください！

### NANが10000以上の指標を削除してみる

In [8]:
# nanのカウント
null_count = list(a_2.isnull().sum())
# 列名のリスト
a_2_columns_list = a_2.columns.values
# NANが10000以上の指標を削除してみる
a_3 = a_2.copy()

for index in range(len(null_count)):
#     NANが10000以上のとき
    if null_count[index] >= 10000:
        column_name = a_2_columns_list[index]
        a_3 = a_3.drop([column_name], axis=1)
        
a_3.isnull().sum()

職場の様子                  0
休日休暇(月曜日)              0
（派遣先）配属先部署　男女比　男    2052
勤務地　最寄駅2（駅名）        8367
大手企業                   0
                    ...
（派遣先）職場の雰囲気            4
勤務地　最寄駅1（駅名）           0
勤務地　最寄駅2（分）         8494
給与/交通費　備考           3556
残業なし                   0
Length: 86, dtype: int64

In [9]:
a_3.head()

,職場の様子,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,勤務地 最寄駅2（駅名）,大手企業,交通費別途支給,（派遣先）配属先部署 人数,残業月20時間以上,職種コード,1日7時間以下勤務OK,...,お仕事のポイント（仕事PR）,扶養控除内,給与/交通費 給与下限,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし
0,3,0,6.0,NaN,0,0,12.0,0,22010,1,...,◆駅からスグ！飲食店・コンビニが近く便利！職場環境ＧＯＯＤ◎！当社含む派遣スタッフ多数活躍中...,0,1550,1,121,当社スタッフ活躍中です！<BR>,北千住,NaN,【月収例】19万5300円＋残業代（21日勤務の場合）,1
1,3,0,2.0,淡路町,1,0,33.0,0,20020,1,...,◆開始日相談可能です♪複数路線が利用でき便利！休憩室完備の自社ビル！当社スタッフさん就業中！...,0,1800,1,101,ランチに嬉しい社員食堂完備の職場です！<BR>,新御茶ノ水,5.0,【月収例】26万4600円＋残業代（21日勤務の場合）,1
2,3,0,2.0,淡路町,1,0,33.0,0,20020,1,...,◆開始日相談可能です♪複数路線が利用でき便利！休憩室完備の自社ビル！当社スタッフさん就業中！...,0,1800,1,101,ランチに嬉しい社員食堂完備の職場です！<BR>,新御茶ノ水,5.0,【月収例】26万4600円＋残業代（21日勤務の場合）,1
3,2,0,8.0,宝町,0,0,5.0,1,20020,0,...,◆最寄駅から徒歩圏内！複数路線が利用可能！近くにコンビニ・カフェがあり便利！分煙されており快...,0,1650,1,102,落ち着いた雰囲気の職場環境です！<BR>,八丁堀,6.0,【月収例】25万9875円＋残業代（21日勤務の場合）,0
4,2,0,8.0,宝町,0,0,5.0,1,20020,0,...,◆最寄駅から徒歩圏内！複数路線が利用可能！近くにコンビニ・カフェがあり便利！分煙されており快...,0,1650,1,102,落ち着いた雰囲気の職場環境です！<BR>,八丁堀,6.0,【月収例】25万9875円＋残業代（21日勤務の場合）,0

### テストデータの読み込み

In [10]:
t_x = pd.read_csv("test_x.csv")
t_x.head()

,勤務地 最寄駅3（駅名）,ミドル（40〜）活躍中,オープニングスタッフ,未使用.20,英語力不要,経験者優遇,Wordのスキルを活かす,メモ,派遣スタッフ活躍中,勤務地 最寄駅1（駅からの交通手段）,...,産休育休取得事例あり,仕事写真（下） 写真3 ファイル名,掲載期間 開始日,勤務地 最寄駅3（駅からの交通手段）,未経験OK,ブロックコード1,未使用.19,応募資格,WEB関連のスキルを活かす,対象者設定 年齢下限
0,NaN,1,NaN,NaN,1,1,1,NaN,1,1.0,...,1,NaN,2019/10/24,NaN,1,NaN,NaN,◆未経験者歓迎！<BR>【使用するＯＡスキル】Ｅｘｃｅｌ（関数）・ＰｏｗｅｒＰｏｉｎｔ（文章...,NaN,0
1,NaN,1,NaN,NaN,1,1,1,NaN,1,1.0,...,1,NaN,2019/10/24,NaN,1,NaN,NaN,【短大・専門・高専以上】◆業界経験問いません、ある方歓迎！<BR>※人事事務の経験が必要です...,NaN,0
2,NaN,1,NaN,NaN,1,1,1,NaN,1,1.0,...,1,NaN,2019/10/24,NaN,0,NaN,NaN,【専門・高専卒以上】◆事務経験・簿記３級程度の知識がある方歓迎します。<BR>【使用するＯＡ...,NaN,0
3,NaN,1,NaN,NaN,1,1,1,NaN,0,1.0,...,1,NaN,2019/10/24,NaN,1,NaN,NaN,【大卒以上】◆未経験者歓迎！<BR>【使用するＯＡスキル】Ｅｘｃｅｌ（関数）<BR><BR>...,NaN,0
4,NaN,1,NaN,NaN,1,1,1,NaN,0,1.0,...,1,NaN,2019/10/24,NaN,1,NaN,NaN,＜高卒以上＞◆未経験者歓迎！<BR>※金融機関での就業経験がある方歓迎。<BR>【使用するＯ...,NaN,0

In [11]:
# a_3にカラムを合わせる
columns_list = list(a_3.columns.values)
t_x_1 = t_x[columns_list]
t_x_1.head()

,職場の様子,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,勤務地 最寄駅2（駅名）,大手企業,交通費別途支給,（派遣先）配属先部署 人数,残業月20時間以上,職種コード,1日7時間以下勤務OK,...,お仕事のポイント（仕事PR）,扶養控除内,給与/交通費 給与下限,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし
0,3,0,6.0,二子玉川,0,0,9.0,0,22010,1,...,◆同業務就業の方が在籍で安心！オシャレを楽しめるオフィカジＯＫ♪給湯設備・ホッと一息つける休...,0,1600,1,112,派遣スタッフ活躍中です！<BR>,成城学園前,15.0,【月収例】23万5200円＋残業代（21日勤務の場合）,1
1,3,0,5.0,水天宮前,0,0,11.0,0,22030,1,...,◆２つの駅からアクセス◎！飲食店・コンビニが近くお昼もラクチン！禁煙でクリーンな環境！オフィ...,0,1700,1,102,落ち着いた雰囲気の職場環境です！<BR>,人形町,1.0,【月収例】24万9900円＋残業代（21日勤務の場合）,0
2,3,0,2.0,淡路町,1,0,33.0,0,20020,1,...,◆開始日相談可能です♪複数路線が利用でき便利！休憩室完備の自社ビル！当社スタッフさん就業中！...,0,1800,1,101,ランチに嬉しい社員食堂完備の職場です！<BR>,新御茶ノ水,5.0,【月収例】26万4600円＋残業代（21日勤務の場合）,1
3,2,0,8.0,宝町,0,0,5.0,1,20020,0,...,◆最寄駅から徒歩圏内！複数路線が利用可能！近くにコンビニ・カフェがあり便利！分煙されており快...,0,1650,1,102,落ち着いた雰囲気の職場環境です！<BR>,八丁堀,6.0,【月収例】25万9875円＋残業代（21日勤務の場合）,0
4,2,0,6.0,日本橋,0,0,8.0,0,20020,1,...,◆駅からスグ！飲食店・コンビニが近く何かと便利！禁煙でクリーンな環境！カジュアル×デニムＯＫ...,0,1700,1,102,落ち着いた雰囲気のオフィスです！<BR>,茅場町,7.0,【月収例】24万9900円＋残業代（21日勤務の場合）,1

In [12]:
# object型のみ抽出
a_3_object = a_3.select_dtypes(include=object)
a_3_object.head()

,勤務地 最寄駅2（駅名）,掲載期間 開始日,勤務地 最寄駅2（沿線名）,休日休暇 備考,期間・時間 勤務時間,勤務地 備考,拠点番号,お仕事名,期間・時間 勤務開始日,（派遣先）配属先部署,仕事内容,勤務地 最寄駅1（沿線名）,応募資格,派遣会社のうれしい特典,掲載期間 終了日,お仕事のポイント（仕事PR）,（派遣先）職場の雰囲気,勤務地 最寄駅1（駅名）,給与/交通費 備考
0,NaN,2019/11/27,NaN,※土・日・祝がお休みです。※企業カレンダーあります。,9:30〜16:30 <BR>※残業はほとんどありません。<BR>※休憩は６０分です。,東京都足立区,206東京,ほぼ１６時半終業☆大学＊申請受付ｅｔｃ！未経験スタートＯＫ☆,2020/1/6,事務処理を行う部署,１月スタート！実働短め☆残業ほとんどなし×基本土日祝お休み！朝は少しゆっくりの９：３０出勤で...,東京メトロ千代田線,◆未経験者歓迎！<BR>【使用するＯＡスキル】Ｅｘｃｅｌ（ＶＬＯＯＫ関数）<BR><BR>▼...,"●当社は全国17,000件のお仕事を取り扱っており、毎日100名以上の方が就業を決めています...",2020/11/27,◆駅からスグ！飲食店・コンビニが近く便利！職場環境ＧＯＯＤ◎！当社含む派遣スタッフ多数活躍中...,当社スタッフ活躍中です！<BR>,北千住,【月収例】19万5300円＋残業代（21日勤務の場合）
1,淡路町,2019/11/27,東京メトロ丸ノ内線,※土・日・祝がお休みです。,9:00〜17:00 <BR>※残業はほとんどありません。<BR>※休憩は６０分です。,東京都千代田区,206東京,≪3ヶ月後正社員！≫大手損保会社でコツコツ事務＊社員食堂あり,2019/11/26,経理部,＜大手損保会社＞産休・育休取得実績ありの企業さんです♪ランチに嬉しい社員食堂完備の職場ですよ...,東京メトロ千代田線,【専門・高専卒以上】◆事務経験・簿記３級程度の知識がある方歓迎します。<BR>【使用するＯＡ...,"●当社は全国17,000件のお仕事を取り扱っており、毎日100名以上の方が就業を決めています...",2020/11/27,◆開始日相談可能です♪複数路線が利用でき便利！休憩室完備の自社ビル！当社スタッフさん就業中！...,ランチに嬉しい社員食堂完備の職場です！<BR>,新御茶ノ水,【月収例】26万4600円＋残業代（21日勤務の場合）
2,淡路町,2019/11/27,東京メトロ丸ノ内線,※土・日・祝がお休みです。,9:00〜17:00 <BR>※残業はほとんどありません。<BR>※休憩は６０分です。,東京都千代田区,206東京,≪3ヶ月後正社員！≫大手損保会社でコツコツ事務＊社員食堂あり,2019/11/26,経理部,＜大手損保会社＞産休・育休取得実績ありの企業さんです♪ランチに嬉しい社員食堂完備の職場ですよ...,東京メトロ千代田線,【専門・高専卒以上】◆事務経験・簿記３級程度の知識がある方歓迎します。<BR>【使用するＯＡ...,"●当社は全国17,000件のお仕事を取り扱っており、毎日100名以上の方が就業を決めています...",2020/11/27,◆開始日相談可能です♪複数路線が利用でき便利！休憩室完備の自社ビル！当社スタッフさん就業中！...,ランチに嬉しい社員食堂完備の職場です！<BR>,新御茶ノ水,【月収例】26万4600円＋残業代（21日勤務の場合）
3,宝町,2019/11/27,都営浅草線,※土・日・祝がお休みです。,9:00〜17:30 <BR>※休憩は６０分です。,東京都中央区,206東京,【未経験でも6ヶ月後社員】賞与年4.5ヶ月分＊非営利団体で事務,2019/11/26,企画調整部,安心安定の非営利団体！落ち着いた雰囲気の職場環境です！<BR>【ＯＡ事務】<BR>会議や委員...,東京メトロ日比谷線,【大卒以上】◆未経験者歓迎！<BR>【使用するＯＡスキル】Ｅｘｃｅｌ（関数）<BR><BR>...,"●当社は全国17,000件のお仕事を取り扱っており、毎日100名以上の方が就業を決めています...",2020/11/27,◆最寄駅から徒歩圏内！複数路線が利用可能！近くにコンビニ・カフェがあり便利！分煙されており快...,落ち着いた雰囲気の職場環境です！<BR>,八丁堀,【月収例】25万9875円＋残業代（21日勤務の場合）
4,宝町,2019/11/27,都営浅草線,※土・日・祝がお休みです。,9:00〜17:30 <BR>※休憩は６０分です。,東京都中央区,206東京,【未経験でも6ヶ月後社員】賞与年4.5ヶ月分＊非営利団体で事務,2019/11/26,企画調整部,安心安定の非営利団体！落ち着いた雰囲気の職場環境です！<BR>【ＯＡ事務】<BR>会議や委員...,東京メトロ日比谷線,【大卒以上】◆未経験者歓迎！<BR>【使用するＯＡスキル】Ｅｘｃｅｌ（関数）<BR><BR>...,"●当社は全国17,000件のお仕事を取り扱っており、毎日100名以上の方が就業を決めています...",2020/11/27,◆最寄駅から徒歩圏内！複数路線が利用可能！近くにコンビニ・カフェがあり便利！分煙されており快...,落ち着いた雰囲気の職場環境です！<BR>,八丁堀,【月収例】25万9875円＋残業代（21日勤務の場合）

In [13]:
df_info_a_3_object = pd.DataFrame({"unique count": list(a_3_object.nunique(dropna=False)), "null count": list(a_3_object.isnull().sum())}, index=list(a_3_object.columns.values))
df_info_a_3_object

                unique count  null count
勤務地　最寄駅2（駅名）             840        8367
掲載期間　開始日                   2           0
勤務地　最寄駅2（沿線名）            219        8367
休日休暇　備考                  752           0
期間・時間　勤務時間              3059           0
勤務地　備考                   736           0
拠点番号                      52           0
お仕事名                    9925           0
期間・時間　勤務開始日               94           0
（派遣先）配属先部署              3574           3
仕事内容                   11086           0
勤務地　最寄駅1（沿線名）            351           0
応募資格                    4385           0
派遣会社のうれしい特典               27           0
掲載期間　終了日                   2           0
お仕事のポイント（仕事PR）          9636           0
（派遣先）職場の雰囲気              866           4
勤務地　最寄駅1（駅名）            1729           0
給与/交通費　備考                556        3556

##### エンコーディングするカテゴリ変数の候補メモ

・~~勤務地　最寄駅2（駅名）~~　　→1があるからいらなそう

・~~掲載期間　開始日・終了日~~ 　→二値へ

・~~勤務地　最寄駅2（沿線名）~~  →駅名があるので、なくても良さげ

★休日休暇　備考

★~~期間・時間　勤務時間~~

★勤務地　備考

・~~拠点番号~~  →番号のみを抽出

・~~お仕事名~~  →ほぼ全部違うから無視
    
・~~期間・時間　勤務開始日~~

★~~（派遣先）配属先部署~~

・~~仕事内容~~  →お仕事名と同じく

・~~勤務地　最寄駅1（沿線名）~~　→駅名があるので、なくても良さげ

★~~応募資格~~

★派遣会社のうれしい特典

・~~お仕事のポイント（仕事PR）~~  →お仕事名と同じく

★（派遣先）職場の雰囲気

★勤務地　最寄駅1（駅名）

★給与/交通費　備考

submit_GBDT_Nan_encodingの時よりも少しエンコーディングする変数を減らす  
あまりにも種類が多いもの（ばらばらなもの）のカラムは消去していくことにする

In [14]:
# trainデータに対してNANをなくす
a_4 = a_3.copy()
a_4["休日休暇　備考"] = a_4["休日休暇　備考"].fillna("missing")
# a_4["期間・時間　勤務時間"] = a_4["期間・時間　勤務時間"].fillna("missing")
a_4["勤務地　備考"] = a_4["勤務地　備考"].fillna("missing")
# a_4["（派遣先）配属先部署"] = a_4["（派遣先）配属先部署"].fillna("missing")
# a_4["応募資格"] = a_4["応募資格"].fillna("missing")
a_4["派遣会社のうれしい特典"] = a_4["派遣会社のうれしい特典"].fillna("missing")
a_4["（派遣先）職場の雰囲気"] = a_4["（派遣先）職場の雰囲気"].fillna("missing")
a_4["勤務地　最寄駅1（駅名）"] = a_4["勤務地　最寄駅1（駅名）"].fillna("missing")
a_4["給与/交通費　備考"] = a_4["給与/交通費　備考"].fillna("missing")

In [15]:
# testデータに対してNANをなくす
t_x_2 = t_x_1.copy()
t_x_2["休日休暇　備考"] = t_x_2["休日休暇　備考"].fillna("missing")
# t_x_2["期間・時間　勤務時間"] = t_x_2["期間・時間　勤務時間"].fillna("missing")
t_x_2["勤務地　備考"] = t_x_2["勤務地　備考"].fillna("missing")
# t_x_2["（派遣先）配属先部署"] = t_x_2["（派遣先）配属先部署"].fillna("missing")
# t_x_2["応募資格"] = t_x_2["応募資格"].fillna("missing")
t_x_2["派遣会社のうれしい特典"] = t_x_2["派遣会社のうれしい特典"].fillna("missing")
t_x_2["（派遣先）職場の雰囲気"] = t_x_2["（派遣先）職場の雰囲気"].fillna("missing")
t_x_2["勤務地　最寄駅1（駅名）"] = t_x_2["勤務地　最寄駅1（駅名）"].fillna("missing")
t_x_2["給与/交通費　備考"] = t_x_2["給与/交通費　備考"].fillna("missing")

In [16]:
# "休日休暇　備考","期間・時間　勤務時間","勤務地　備考","（派遣先）配属先部署","応募資格","派遣会社のうれしい特典","（派遣先）職場の雰囲気","勤務地　最寄駅1（駅名）","給与/交通費　備考"
# ,,,,,,,

In [17]:
from sklearn.preprocessing import LabelEncoder

a_5 = a_4.copy()
t_x_3 = t_x_2.copy()
le1 = LabelEncoder()
# a_5とt_x_3においてラベル付け
le1.fit(pd.concat([a_5["休日休暇　備考"], t_x_3["休日休暇　備考"]], sort=True))
a_5["休日休暇　備考"] = le1.transform(a_5["休日休暇　備考"])
t_x_3["休日休暇　備考"] = le1.transform(t_x_3["休日休暇　備考"])

In [18]:
# le2 = LabelEncoder()
# le2.fit(pd.concat([a_5["期間・時間　勤務時間"], t_x_3["期間・時間　勤務時間"]], sort=True))
# a_5["期間・時間　勤務時間"] = le2.transform(a_5["期間・時間　勤務時間"])
# t_x_3["期間・時間　勤務時間"] = le2.transform(t_x_3["期間・時間　勤務時間"])

le3 = LabelEncoder()
le3.fit(pd.concat([a_5["勤務地　備考"], t_x_3["勤務地　備考"]], sort=True))
a_5["勤務地　備考"] = le3.transform(a_5["勤務地　備考"])
t_x_3["勤務地　備考"] = le3.transform(t_x_3["勤務地　備考"])

# le4 = LabelEncoder()
# le4.fit(pd.concat([a_5["（派遣先）配属先部署"], t_x_3["（派遣先）配属先部署"]], sort=True))
# a_5["（派遣先）配属先部署"] = le4.transform(a_5["（派遣先）配属先部署"])
# t_x_3["（派遣先）配属先部署"] = le4.transform(t_x_3["（派遣先）配属先部署"])

# le5 = LabelEncoder()
# le5.fit(pd.concat([a_5["応募資格"], t_x_3["応募資格"]], sort=True))
# a_5["応募資格"] = le5.transform(a_5["応募資格"])
# t_x_3["応募資格"] = le5.transform(t_x_3["応募資格"])

le6 = LabelEncoder()
le6.fit(pd.concat([a_5["派遣会社のうれしい特典"], t_x_3["派遣会社のうれしい特典"]], sort=True))
a_5["派遣会社のうれしい特典"] = le6.transform(a_5["派遣会社のうれしい特典"])
t_x_3["派遣会社のうれしい特典"] = le6.transform(t_x_3["派遣会社のうれしい特典"])

le7 = LabelEncoder()
le7.fit(pd.concat([a_5["（派遣先）職場の雰囲気"], t_x_3["（派遣先）職場の雰囲気"]], sort=True))
a_5["（派遣先）職場の雰囲気"] = le7.transform(a_5["（派遣先）職場の雰囲気"])
t_x_3["（派遣先）職場の雰囲気"] = le7.transform(t_x_3["（派遣先）職場の雰囲気"])

le8 = LabelEncoder()
le8.fit(pd.concat([a_5["勤務地　最寄駅1（駅名）"], t_x_3["勤務地　最寄駅1（駅名）"]], sort=True))
a_5["勤務地　最寄駅1（駅名）"] = le8.transform(a_5["勤務地　最寄駅1（駅名）"])
t_x_3["勤務地　最寄駅1（駅名）"] = le8.transform(t_x_3["勤務地　最寄駅1（駅名）"])

le9 = LabelEncoder()
le9.fit(pd.concat([a_5["給与/交通費　備考"], t_x_3["給与/交通費　備考"]], sort=True))
a_5["給与/交通費　備考"] = le9.transform(a_5["給与/交通費　備考"])
t_x_3["給与/交通費　備考"] = le9.transform(t_x_3["給与/交通費　備考"])

In [19]:
# trainデータに対して使わないカラムの削除
a_5 = a_5.drop(["勤務地　最寄駅2（駅名）", "勤務地　最寄駅2（沿線名）", "お仕事名", "期間・時間　勤務開始日", "仕事内容", "勤務地　最寄駅1（沿線名）", "お仕事のポイント（仕事PR）", "掲載期間　終了日", "期間・時間　勤務時間", "（派遣先）配属先部署", "応募資格"], axis=1)
a_5.head()

,職場の様子,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,大手企業,交通費別途支給,（派遣先）配属先部署 人数,残業月20時間以上,職種コード,1日7時間以下勤務OK,短時間勤務OK(1日4h以内),...,休日休暇(金曜日),扶養控除内,給与/交通費 給与下限,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし
0,3,0,6.0,0,0,12.0,0,22010,1,0,...,0,0,1550,1,121,477,325,NaN,186,1
1,3,0,2.0,1,0,33.0,0,20020,1,0,...,0,0,1800,1,101,185,832,5.0,424,1
2,3,0,2.0,1,0,33.0,0,20020,1,0,...,0,0,1800,1,101,185,832,5.0,424,1
3,2,0,8.0,0,0,5.0,1,20020,0,0,...,0,0,1650,1,102,777,261,6.0,411,0
4,2,0,8.0,0,0,5.0,1,20020,0,0,...,0,0,1650,1,102,777,261,6.0,411,0

In [20]:
# testデータに対して使わないカラムの削除
t_x_3 = t_x_3.drop(["勤務地　最寄駅2（駅名）", "勤務地　最寄駅2（沿線名）", "お仕事名", "期間・時間　勤務開始日", "仕事内容", "勤務地　最寄駅1（沿線名）", "お仕事のポイント（仕事PR）", "掲載期間　終了日", "期間・時間　勤務時間", "（派遣先）配属先部署", "応募資格"], axis=1)
t_x_3.head()

,職場の様子,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,大手企業,交通費別途支給,（派遣先）配属先部署 人数,残業月20時間以上,職種コード,1日7時間以下勤務OK,短時間勤務OK(1日4h以内),...,休日休暇(金曜日),扶養控除内,給与/交通費 給与下限,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし
0,3,0,6.0,0,0,9.0,0,22010,1,0,...,0,0,1600,1,112,608,773,15.0,325,1
1,3,0,5.0,0,0,11.0,0,22030,1,0,...,0,0,1700,1,102,777,205,1.0,373,0
2,3,0,2.0,1,0,33.0,0,20020,1,0,...,0,0,1800,1,101,185,832,5.0,424,1
3,2,0,8.0,0,0,5.0,1,20020,0,0,...,0,0,1650,1,102,777,261,6.0,411,0
4,2,0,6.0,0,0,8.0,0,20020,1,0,...,0,0,1700,1,102,773,1401,7.0,373,1

In [21]:
# 掲載開始日を０，１にエンコード
# trainデータ
day_mapping = {"2019/11/27": 0, "2019/9/25": 1}
a_5["掲載期間　開始日"] = a_5['掲載期間　開始日'].map(day_mapping)

In [22]:
# testデータ
t_x_3 = t_x_3.replace('2019/10/24', 3)
t_x_3.head()

,職場の様子,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,大手企業,交通費別途支給,（派遣先）配属先部署 人数,残業月20時間以上,職種コード,1日7時間以下勤務OK,短時間勤務OK(1日4h以内),...,休日休暇(金曜日),扶養控除内,給与/交通費 給与下限,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし
0,3,0,6.0,0,0,9.0,0,22010,1,0,...,0,0,1600,1,112,608,773,15.0,325,1
1,3,0,5.0,0,0,11.0,0,22030,1,0,...,0,0,1700,1,102,777,205,1.0,373,0
2,3,0,2.0,1,0,33.0,0,20020,1,0,...,0,0,1800,1,101,185,832,5.0,424,1
3,2,0,8.0,0,0,5.0,1,20020,0,0,...,0,0,1650,1,102,777,261,6.0,411,0
4,2,0,6.0,0,0,8.0,0,20020,1,0,...,0,0,1700,1,102,773,1401,7.0,373,1

In [23]:
# trainデータの拠点番号
func = lambda x: int(x[:3])
a_5["拠点番号"] = a_5["拠点番号"].map(func)
a_5.head()

,職場の様子,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,大手企業,交通費別途支給,（派遣先）配属先部署 人数,残業月20時間以上,職種コード,1日7時間以下勤務OK,短時間勤務OK(1日4h以内),...,休日休暇(金曜日),扶養控除内,給与/交通費 給与下限,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし
0,3,0,6.0,0,0,12.0,0,22010,1,0,...,0,0,1550,1,121,477,325,NaN,186,1
1,3,0,2.0,1,0,33.0,0,20020,1,0,...,0,0,1800,1,101,185,832,5.0,424,1
2,3,0,2.0,1,0,33.0,0,20020,1,0,...,0,0,1800,1,101,185,832,5.0,424,1
3,2,0,8.0,0,0,5.0,1,20020,0,0,...,0,0,1650,1,102,777,261,6.0,411,0
4,2,0,8.0,0,0,5.0,1,20020,0,0,...,0,0,1650,1,102,777,261,6.0,411,0

In [24]:
# testデータの拠点番号
# trainデータの拠点番号
func = lambda x: int(x[:3])
t_x_3["拠点番号"] = t_x_3["拠点番号"].map(func)
t_x_3.head()

,職場の様子,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,大手企業,交通費別途支給,（派遣先）配属先部署 人数,残業月20時間以上,職種コード,1日7時間以下勤務OK,短時間勤務OK(1日4h以内),...,休日休暇(金曜日),扶養控除内,給与/交通費 給与下限,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし
0,3,0,6.0,0,0,9.0,0,22010,1,0,...,0,0,1600,1,112,608,773,15.0,325,1
1,3,0,5.0,0,0,11.0,0,22030,1,0,...,0,0,1700,1,102,777,205,1.0,373,0
2,3,0,2.0,1,0,33.0,0,20020,1,0,...,0,0,1800,1,101,185,832,5.0,424,1
3,2,0,8.0,0,0,5.0,1,20020,0,0,...,0,0,1650,1,102,777,261,6.0,411,0
4,2,0,6.0,0,0,8.0,0,20020,1,0,...,0,0,1700,1,102,773,1401,7.0,373,1

In [55]:
# NaNの数を特徴量に追加
t_x_3['number_of_NAN'] = t_x_3.isna().sum(axis=1).astype(np.int8)

In [56]:
# 予測用データ
submit_x = t_x_3

In [72]:
work_number = submit_x["お仕事No."]
submit_x_test = np.array(submit_x.drop(["お仕事No."], axis=1))
submit_x_test.shape

(3391, 75)

In [44]:
pd.options.display.max_columns = None

In [46]:
a_5.head()

,職場の様子,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,大手企業,交通費別途支給,（派遣先）配属先部署 人数,残業月20時間以上,職種コード,1日7時間以下勤務OK,短時間勤務OK(1日4h以内),駅から徒歩5分以内,学校・公的機関（官公庁）,土日祝のみ勤務,掲載期間 開始日,Wordのスキルを活かす,勤務地 最寄駅1（分）,お仕事No.,派遣スタッフ活躍中,大量募集,Accessのスキルを活かす,休日休暇(火曜日),平日休みあり,勤務地 最寄駅2（駅からの交通手段）,休日休暇 備考,フラグオプション選択,期間・時間 勤務期間,派遣形態,週2・3日OK,勤務先公開,Excelのスキルを活かす,16時前退社OK,正社員登用あり,残業月20時間未満,勤務地 備考,英語力不要,拠点番号,休日休暇(日曜日),社員食堂あり,10時以降出社OK,英語以外の語学力を活かす,休日休暇(祝日),外資系企業,服装自由,PowerPointのスキルを活かす,（派遣先）配属先部署 男女比 女,休日休暇(土曜日),休日休暇(木曜日),（派遣先）配属先部署 平均年齢,英語力を活かす,会社概要 業界コード,勤務地 都道府県コード,PCスキル不要,車通勤OK,制服あり,休日休暇(水曜日),仕事の仕方,勤務地 最寄駅1（駅からの交通手段）,紹介予定派遣,シフト勤務,経験者優遇,週4日勤務,未経験OK,派遣会社のうれしい特典,土日祝休み,給与/交通費 交通費,休日休暇(金曜日),扶養控除内,給与/交通費 給与下限,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし
0,3,0,6.0,0,0,12.0,0,22010,1,0,1,1,0,0,1,3.0,2203566799,1,0,0,0,0,NaN,138,1,5,0,0,0,1,0,0,0,453,1,206,1,1,0,0,1,0,1,0,4.0,1,0,45.0,0,30000,13,0,0,0,0,2,1.0,0,0,1,0,1,0,1,3,0,0,1550,1,121,477,325,NaN,186,1
1,3,0,2.0,1,0,33.0,0,20020,1,0,1,0,0,0,1,1.0,2203546900,1,0,0,0,0,1.0,134,3,5,1,0,0,1,0,1,0,416,1,206,1,1,0,0,1,0,1,0,8.0,1,0,45.0,0,28000,13,0,0,0,0,1,1.0,1,0,1,0,0,0,1,3,0,0,1800,1,101,185,832,5.0,424,1
2,3,0,2.0,1,0,33.0,0,20020,1,0,1,0,0,0,1,1.0,2203546900,1,0,0,0,0,1.0,134,3,5,1,0,0,1,0,1,0,416,1,206,1,1,0,0,1,0,1,0,8.0,1,0,45.0,0,28000,13,0,0,0,0,1,1.0,1,0,1,0,0,0,1,3,0,0,1800,1,101,185,832,5.0,424,1
3,2,0,8.0,0,0,5.0,1,20020,0,0,0,1,0,0,1,6.0,2203545344,0,0,0,0,0,1.0,134,3,5,1,0,0,1,0,1,0,412,1,206,1,0,0,0,1,0,1,0,2.0,1,0,42.0,0,30000,13,0,0,0,0,1,1.0,1,0,1,0,1,0,1,3,0,0,1650,1,102,777,261,6.0,411,0
4,2,0,8.0,0,0,5.0,1,20020,0,0,0,1,0,0,1,6.0,2203545344,0,0,0,0,0,1.0,134,3,5,1,0,0,1,0,1,0,412,1,206,1,0,0,0,1,0,1,0,2.0,1,0,42.0,0,30000,13,0,0,0,0,1,1.0,1,0,1,0,1,0,1,3,0,0,1650,1,102,777,261,6.0,411,0

In [45]:
a_5.describe()

,職場の様子,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,大手企業,交通費別途支給,（派遣先）配属先部署 人数,残業月20時間以上,職種コード,1日7時間以下勤務OK,短時間勤務OK(1日4h以内),駅から徒歩5分以内,学校・公的機関（官公庁）,土日祝のみ勤務,掲載期間 開始日,Wordのスキルを活かす,勤務地 最寄駅1（分）,お仕事No.,派遣スタッフ活躍中,大量募集,Accessのスキルを活かす,休日休暇(火曜日),平日休みあり,勤務地 最寄駅2（駅からの交通手段）,休日休暇 備考,フラグオプション選択,期間・時間 勤務期間,派遣形態,週2・3日OK,勤務先公開,Excelのスキルを活かす,16時前退社OK,正社員登用あり,残業月20時間未満,勤務地 備考,英語力不要,拠点番号,休日休暇(日曜日),社員食堂あり,10時以降出社OK,英語以外の語学力を活かす,休日休暇(祝日),外資系企業,服装自由,PowerPointのスキルを活かす,（派遣先）配属先部署 男女比 女,休日休暇(土曜日),休日休暇(木曜日),（派遣先）配属先部署 平均年齢,英語力を活かす,会社概要 業界コード,勤務地 都道府県コード,PCスキル不要,車通勤OK,制服あり,休日休暇(水曜日),仕事の仕方,勤務地 最寄駅1（駅からの交通手段）,紹介予定派遣,シフト勤務,経験者優遇,週4日勤務,未経験OK,派遣会社のうれしい特典,土日祝休み,給与/交通費 交通費,休日休暇(金曜日),扶養控除内,給与/交通費 給与下限,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし
count,15853.000000,15853.000000,13801.000000,15853.000000,15853.000000,13814.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,14929.000000,1.585300e+04,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,7359.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,13801.000000,15853.000000,15853.000000,11133.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,14929.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,15853.000000,7359.000000,15853.000000,15853.000000
mean,2.946319,0.006813,4.997464,0.237242,0.218129,14.174461,0.064972,20637.698227,0.277802,0.010219,0.553018,0.093989,0.000252,0.503690,0.956980,6.568022,3.129635e+09,0.543872,0.002397,0.036965,0.043903,0.063016,1.126512,177.439097,1.098278,4.914464,0.172964,0.036965,0.043777,0.989907,0.070523,0.114868,0.205450,390.989213,0.923989,273.277550,0.954015,0.186715,0.132530,0.002019,0.936100,0.038037,0.787485,0.161294,5.002536,0.940074,0.035009,39.388215,0.074434,25923.500788,17.095187,0.009777,0.181732,0.173469,0.046553,2.650855,1.195793,0.172964,0.053302,0.990412,0.029458,0.877184,0.500221,0.936984,2.781871,0.009903,0.011670,1469.690279,0.991674,137.071848,434.118211,848.275027,7.621008,243.595282,0.729578
std,0.306926,0.082259,2.796697,0.425405,0.412989,23.165115,0.246484,2598.874377,0.447930,0.100574,0.497197,0.291822,0.015883,0.500002,0.202909,4.495272,1.486560e+09,0.498087,0.048902,0.188681,0.204887,0.243000,0.433263,144.796381,1.036030,0.404680,0.378228,0.188681,0.204605,0.099957,0.256034,0.318872,0.404043,156.520767,0.265024,133.752132,0.209459,0.389695,0.339077,0.044884,0.244582,0.191292,0.409100,0.367814,2.796697,0.237356,0.183809,5.629523,0.262484,3163.694945,8.647378,0.098399,0.385636,0.378664,0.210685,1.600303,0.568269,0.378228,0.224643,0.097451,0.169092,0.328236,2.772577,0.243000,0.412989,0.099025,0.107398,244.447800,0.090872,55.513015,234.841303,494.809165,4.577798,176.965509,0.444192
min,2.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,20020.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.103518e+09,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,101.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,21000.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,800.000000,0.000000,101.000000,0.000000,0.000000,1.000000,0.000000,0.000000
25%,3.000000,0.000000,3.000000,0.000000,0.000000,5.000000,0.000000,20020.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,3.000000,2.203538e+09,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,134.000000,0.000000,5.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,359.000000,1.000000,206.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,3.000000,1.000000,0.000000,35.000000,0.000000,22000.000000,13.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,3.000000,0.000000,0.000000,1300.000000,1.000000,103.000000,232.000000,430.000000,5.000000,72.000000,0.000000
50%,3.000000,0.000000,5.000000,0.000000,0.000000,8.000000,0.000000,20030.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,1.000000,5.000000,2.203569e+09,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,134.000000,1.000000,5.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,422.000000,1.000000,206.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,5.000000,1.000000,0.000000,40.000000,0.000000,27000.000000,13.000000,0.000000,0.000000,0.000000,0.000000,2.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,3.000000,0.000000,0.000000,1500.000000,1.000000,109.000000,404.000000,882.000000,7.000000,269.000000,1.000000
75%,3.000000,0.000000,7.000000,0.000000,0.000000,15.000000,0.000000,20710.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000,1.000000,9.000000,3.703541e+09,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,138.000000,1.000000,5.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,441.000000,1.000000,308.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,7.000000,1.000000,0.000000,43.000000,0.000000,29000.000000,22.000000,0.000000,0.000000,0.000000,0.000000,4.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,3.000000,0.000000,0.000000,1650.000000,1.000000,201.000000,665.000000,1228.000000,10.000000,409.000000,1.000000
max,4.000000,1.000000,10.000000,1.000000,1.000000,574.000000,1.000000,80310.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,40.000000,8.403569e+09,1.000000,1.000000,1.000000,1.000000,1.000000,3.000000,817.000000,5.000000,5.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,735.000000,1.000000,709.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,10.000000,1.000000,1.000000,73.000000,1.000000,30000.000000,47.000000,1.000000,1.000000,1.000000,1.000000,5.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,26.000000,1.000000,3.000000,1.000000,1.000000,2850.000000,1.000000,631.000000,936.000000,1748.000000,46.000000,575.000000,1.000000

In [52]:
df_info_a_5 = pd.DataFrame({"unique count": list(a_5.nunique(dropna=False))}, index=list(a_5.columns.values))
df_info_a_5.T

,職場の様子,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,大手企業,交通費別途支給,（派遣先）配属先部署 人数,残業月20時間以上,職種コード,1日7時間以下勤務OK,短時間勤務OK(1日4h以内),駅から徒歩5分以内,学校・公的機関（官公庁）,土日祝のみ勤務,掲載期間 開始日,Wordのスキルを活かす,勤務地 最寄駅1（分）,お仕事No.,派遣スタッフ活躍中,大量募集,Accessのスキルを活かす,休日休暇(火曜日),平日休みあり,勤務地 最寄駅2（駅からの交通手段）,休日休暇 備考,フラグオプション選択,期間・時間 勤務期間,派遣形態,週2・3日OK,勤務先公開,Excelのスキルを活かす,16時前退社OK,正社員登用あり,残業月20時間未満,勤務地 備考,英語力不要,拠点番号,休日休暇(日曜日),社員食堂あり,10時以降出社OK,英語以外の語学力を活かす,休日休暇(祝日),外資系企業,服装自由,PowerPointのスキルを活かす,（派遣先）配属先部署 男女比 女,休日休暇(土曜日),休日休暇(木曜日),（派遣先）配属先部署 平均年齢,英語力を活かす,会社概要 業界コード,勤務地 都道府県コード,PCスキル不要,車通勤OK,制服あり,休日休暇(水曜日),仕事の仕方,勤務地 最寄駅1（駅からの交通手段）,紹介予定派遣,シフト勤務,経験者優遇,週4日勤務,未経験OK,派遣会社のうれしい特典,土日祝休み,給与/交通費 交通費,休日休暇(金曜日),扶養控除内,給与/交通費 給与下限,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし
unique count,3,2,12,2,2,112,2,14,2,2,2,2,2,2,2,31,9671,2,2,2,2,2,4,752,5,2,2,2,2,2,2,2,2,736,2,51,2,2,2,2,2,2,2,2,12,2,2,51,2,13,47,2,2,2,2,5,4,2,2,2,2,2,27,2,2,2,2,136,2,151,866,1729,33,556,2

In [53]:
# NaNの数を特徴量に追加
a_5['number_of_NAN'] = a_5.isna().sum(axis=1).astype(np.int8)

In [54]:
# 前処理後データ
application_after = a_5
application_after.head()

,職場の様子,休日休暇(月曜日),（派遣先）配属先部署 男女比 男,大手企業,交通費別途支給,（派遣先）配属先部署 人数,残業月20時間以上,職種コード,1日7時間以下勤務OK,短時間勤務OK(1日4h以内),駅から徒歩5分以内,学校・公的機関（官公庁）,土日祝のみ勤務,掲載期間 開始日,Wordのスキルを活かす,勤務地 最寄駅1（分）,お仕事No.,派遣スタッフ活躍中,大量募集,Accessのスキルを活かす,休日休暇(火曜日),平日休みあり,勤務地 最寄駅2（駅からの交通手段）,休日休暇 備考,フラグオプション選択,期間・時間 勤務期間,派遣形態,週2・3日OK,勤務先公開,Excelのスキルを活かす,16時前退社OK,正社員登用あり,残業月20時間未満,勤務地 備考,英語力不要,拠点番号,休日休暇(日曜日),社員食堂あり,10時以降出社OK,英語以外の語学力を活かす,休日休暇(祝日),外資系企業,服装自由,PowerPointのスキルを活かす,（派遣先）配属先部署 男女比 女,休日休暇(土曜日),休日休暇(木曜日),（派遣先）配属先部署 平均年齢,英語力を活かす,会社概要 業界コード,勤務地 都道府県コード,PCスキル不要,車通勤OK,制服あり,休日休暇(水曜日),仕事の仕方,勤務地 最寄駅1（駅からの交通手段）,紹介予定派遣,シフト勤務,経験者優遇,週4日勤務,未経験OK,派遣会社のうれしい特典,土日祝休み,給与/交通費 交通費,休日休暇(金曜日),扶養控除内,給与/交通費 給与下限,オフィスが禁煙・分煙,勤務地 市区町村コード,（派遣先）職場の雰囲気,勤務地 最寄駅1（駅名）,勤務地 最寄駅2（分）,給与/交通費 備考,残業なし,number_of_NAN
0,3,0,6.0,0,0,12.0,0,22010,1,0,1,1,0,0,1,3.0,2203566799,1,0,0,0,0,NaN,138,1,5,0,0,0,1,0,0,0,453,1,206,1,1,0,0,1,0,1,0,4.0,1,0,45.0,0,30000,13,0,0,0,0,2,1.0,0,0,1,0,1,0,1,3,0,0,1550,1,121,477,325,NaN,186,1,2
1,3,0,2.0,1,0,33.0,0,20020,1,0,1,0,0,0,1,1.0,2203546900,1,0,0,0,0,1.0,134,3,5,1,0,0,1,0,1,0,416,1,206,1,1,0,0,1,0,1,0,8.0,1,0,45.0,0,28000,13,0,0,0,0,1,1.0,1,0,1,0,0,0,1,3,0,0,1800,1,101,185,832,5.0,424,1,0
2,3,0,2.0,1,0,33.0,0,20020,1,0,1,0,0,0,1,1.0,2203546900,1,0,0,0,0,1.0,134,3,5,1,0,0,1,0,1,0,416,1,206,1,1,0,0,1,0,1,0,8.0,1,0,45.0,0,28000,13,0,0,0,0,1,1.0,1,0,1,0,0,0,1,3,0,0,1800,1,101,185,832,5.0,424,1,0
3,2,0,8.0,0,0,5.0,1,20020,0,0,0,1,0,0,1,6.0,2203545344,0,0,0,0,0,1.0,134,3,5,1,0,0,1,0,1,0,412,1,206,1,0,0,0,1,0,1,0,2.0,1,0,42.0,0,30000,13,0,0,0,0,1,1.0,1,0,1,0,1,0,1,3,0,0,1650,1,102,777,261,6.0,411,0,0
4,2,0,8.0,0,0,5.0,1,20020,0,0,0,1,0,0,1,6.0,2203545344,0,0,0,0,0,1.0,134,3,5,1,0,0,1,0,1,0,412,1,206,1,0,0,0,1,0,1,0,2.0,1,0,42.0,0,30000,13,0,0,0,0,1,1.0,1,0,1,0,1,0,1,3,0,0,1650,1,102,777,261,6.0,411,0,0

### yの読み込み

In [29]:
df_y = pd.read_csv("train_y.csv")
df_y.head()

       お仕事No.    応募数 合計
0  2203566799  1.945910
1  2203546900  3.951244
2  2203546900  3.295837
3  2203545344  3.970292
4  2203545344  3.784190

In [30]:
len(df_y)

15853

# 回帰問題

In [57]:
y = df_y["応募数 合計"]
X = application_after.drop(["お仕事No."], axis=1)

In [58]:
y_array = np.array(y)
X_array = np.array(X)

In [59]:
print("y_array: ", y_array.shape)
print("X_array: ", X_array.shape)

y_array:  (15853,)
X_array:  (15853, 75)

In [60]:
# train/testに分割する
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_array, y_array, test_size=0.4, random_state=0)

In [61]:
print("X_train: ", X_train.shape)
print("y_train: ", y_train.shape)
print("X_test: ", X_test.shape)
print("y_test: ", y_test.shape)

X_train:  (9511, 75)
y_train:  (9511,)
X_test:  (6342, 75)
y_test:  (6342,)

# GBDT

In [62]:
import xgboost as xgb
from sklearn.metrics import log_loss

In [73]:
# 特徴量と目的変数をxboostのデータ構造に変換する
dtrain = xgb.DMatrix(X_train, label=y_train)
dvalid = xgb.DMatrix(X_test, label=y_test)
dtest = xgb.DMatrix(submit_x_test)

In [67]:
# ハイパーパラメータの設定
param = {"object": "reg:squarederror", "silent": 1, "random_state": 71}
num_round = 51

In [68]:
# 学習の実行
# バリデーションデータもモデルに渡し、学習の進行とともにスコアがどう変わるかモニタリングする
# watchlistには学習データおよびバリデーションデータをセットする
watchlist = [(dtrain, "train"), (dvalid, "eval")]
model = xgb.train(param, dtrain, num_round, evals=watchlist)

[0]	train-rmse:0.739083	eval-rmse:0.71943
[1]	train-rmse:0.699185	eval-rmse:0.688175
[2]	train-rmse:0.676982	eval-rmse:0.669978
[3]	train-rmse:0.657128	eval-rmse:0.660784
[4]	train-rmse:0.642909	eval-rmse:0.65173
[5]	train-rmse:0.632524	eval-rmse:0.647041
[6]	train-rmse:0.620659	eval-rmse:0.641656
[7]	train-rmse:0.611249	eval-rmse:0.638474
[8]	train-rmse:0.602394	eval-rmse:0.635508
[9]	train-rmse:0.594737	eval-rmse:0.632102
[10]	train-rmse:0.586571	eval-rmse:0.629014
[11]	train-rmse:0.577916	eval-rmse:0.627047
[12]	train-rmse:0.56803	eval-rmse:0.623116
[13]	train-rmse:0.565953	eval-rmse:0.622417
[14]	train-rmse:0.56298	eval-rmse:0.622159
[15]	train-rmse:0.558736	eval-rmse:0.620979
[16]	train-rmse:0.555203	eval-rmse:0.620321
[17]	train-rmse:0.548821	eval-rmse:0.619416
[18]	train-rmse:0.544716	eval-rmse:0.618262
[19]	train-rmse:0.541315	eval-rmse:0.617711
[20]	train-rmse:0.535207	eval-rmse:0.61635
[21]	train-rmse:0.532687	eval-rmse:0.615431
[22]	train-rmse:0.530235	eval-rmse:0.614825
[23]	train-rmse:0.524913	eval-rmse:0.614412
[24]	train-rmse:0.519957	eval-rmse:0.613186
[25]	train-rmse:0.517887	eval-rmse:0.613197
[26]	train-rmse:0.513721	eval-rmse:0.612721
[27]	train-rmse:0.510391	eval-rmse:0.612245
[28]	train-rmse:0.505521	eval-rmse:0.610498
[29]	train-rmse:0.50138	eval-rmse:0.609804
[30]	train-rmse:0.497609	eval-rmse:0.608948
[31]	train-rmse:0.495227	eval-rmse:0.608019
[32]	train-rmse:0.492888	eval-rmse:0.607881
[33]	train-rmse:0.488422	eval-rmse:0.60722
[34]	train-rmse:0.485176	eval-rmse:0.606721
[35]	train-rmse:0.482876	eval-rmse:0.606632
[36]	train-rmse:0.480807	eval-rmse:0.606166
[37]	train-rmse:0.479052	eval-rmse:0.605918
[38]	train-rmse:0.476634	eval-rmse:0.606185
[39]	train-rmse:0.474393	eval-rmse:0.605608
[40]	train-rmse:0.47039	eval-rmse:0.605968
[41]	train-rmse:0.465872	eval-rmse:0.605992
[42]	train-rmse:0.461477	eval-rmse:0.605589
[43]	train-rmse:0.45929	eval-rmse:0.605859
[44]	train-rmse:0.457061	eval-rmse:0.606066
[45]	train-rmse:0.455156	eval-rmse:0.605817
[46]	train-rmse:0.45167	eval-rmse:0.605134
[47]	train-rmse:0.448188	eval-rmse:0.605537
[48]	train-rmse:0.447506	eval-rmse:0.605656
[49]	train-rmse:0.44427	eval-rmse:0.604701
[50]	train-rmse:0.441308	eval-rmse:0.604603

In [69]:
# バリデーションデータでのスコアの確認
va_pred = model.predict(dvalid)
# 負の値は0へ
va_pred_0 = [0 if i <= 0 else i for i in va_pred]
va_pred_0

[0.3562083,
 0.7757953,
 0.47077385,
 0.09816818,
 0.3638075,
 0.40578422,
 0.60647345,
 0.29097033,
 0.51852226,
 0.08602828,
 1.3219119,
 0.09638584,
 0.528755,
 0.44250327,
 1.2806823,
 1.1490268,
 1.158282,
 0.46737003,
 0.27569172,
 0,
 1.2129413,
 0.8161825,
 0.0855547,
 0.3354572,
 1.8483729,
 0.20828508,
 0.56730324,
 0.1740154,
 0.7574352,
 0.032116957,
 0.12887275,
 1.4582876,
 0.0107897045,
 0.7708615,
 0.30754858,
 0.35192868,
 1.015743,
 0.55762404,
 0,
 0.4947982,
 0.09222745,
 0.29070318,
 0.2743491,
 0.8052529,
 1.1129929,
 0.19001818,
 0.0077952496,
 0.2527407,
 0.44898155,
 0.25479904,
 0.40857393,
 0.18063653,
 0.55645025,
 0.73695505,
 1.0772085,
 0.5895771,
 0.65775925,
 0.19459036,
 0.123938054,
 0.92033297,
 1.0638902,
 0.2285227,
 0.104386166,
 0.060164932,
 0.6293992,
 0.8718587,
 0.8236673,
 0,
 0.3711197,
 0.66732126,
 0.781468,
 0,
 0.21222985,
 0.28613755,
 0.66718715,
 0.7742589,
 0,
 0.47807997,
 0.18679434,
 0.19092552,
 0.5784065,
 0.11092854,
 0.1921198,
 1.2909817,
 0.12329251,
 1.1385057,
 0.15794146,
 0.53341734,
 0.5507718,
 0.24709426,
 0.080104664,
 0.26483327,
 0.510593,
 1.4524152,
 0.42316744,
 0.079665355,
 0.15247105,
 1.5093907,
 0.21229294,
 0.0724869,
 0.20705059,
 0.09665071,
 0.12014098,
 0.79549366,
 2.266045,
 0.99856734,
 0.6566206,
 0.15717717,
 1.7206612,
 0.7103371,
 0.25438085,
 0.3799596,
 0.5163936,
 0.85015917,
 1.9857142,
 0.33600983,
 1.4375974,
 0.4128774,
 0.48153746,
 0.58173484,
 0.5982452,
 1.3336375,
 0,
 0.52464163,
 0.61581343,
 1.653936,
 0.0040737255,
 1.7414799,
 2.5748196,
 0.66414654,
 0.02526544,
 0,
 0.65321785,
 1.1696094,
 0.3064956,
 0.33059797,
 0.4180067,
 1.2256454,
 1.4655159,
 0.6609337,
 0,
 0.4722378,
 0.7972781,
 0.8284573,
 0.26488167,
 0.3080953,
 0.40780655,
 0.29977566,
 0.30538142,
 0.15157571,
 0.46178946,
 0.37742016,
 2.7596326,
 0.10884269,
 0.5321157,
 1.8976119,
 0.50193703,
 0.29400715,
 1.1275012,
 0.22155622,
 0.3300455,
 0.5574874,
 0.45832726,
 1.9653716,
 0.3311793,
 0.41970065,
 0.102997616,
 0.9516123,
 0.31523108,
 0.17338943,
 0.40591845,
 0.18507786,
 0.54573405,
 0.25688705,
 0.19208482,
 0,
 2.781972,
 0.046789594,
 0.415863,
 0.4052791,
 2.5259655,
 0.4543758,
 0.4418938,
 0.053879514,
 0.050168138,
 0.59528625,
 0.13461839,
 0.21838784,
 0.45774826,
 0.42996624,
 0.27583474,
 0,
 0.6413355,
 0.38126546,
 0.24850067,
 0.510593,
 0.081075035,
 0.10231825,
 0.11677961,
 1.3710876,
 0.07822578,
 0.3691596,
 2.6926603,
 0.7811631,
 0.68081325,
 0.24819635,
 0.67701936,
 1.8623524,
 0.21624334,
 0.23310609,
 0.1579334,
 0,
 0.26071993,
 0.10957489,
 0.10577751,
 0.6777896,
 0.25457135,
 1.6236284,
 0.79661536,
 0.8655864,
 1.4104456,
 0.10370414,
 0.5847069,
 2.300496,
 0.019556936,
 1.0824425,
 0.66614944,
 0.32726142,
 0.44095686,
 0.25247175,
 0.22146542,
 0.13638136,
 0.38619968,
 0.041813534,
 1.5468246,
 0.3257197,
 0.83821905,
 0.83170307,
 0.35491714,
 0.99579036,
 0,
 0.50426596,
 0.7979897,
 0,
 1.048247,
 0.89255023,
 0.7061349,
 0.461915,
 0.018542165,
 2.405583,
 0.5749188,
 0.36093318,
 0.7362948,
 0.3393944,
 1.1669484,
 0.12959781,
 0.9391292,
 0.58178025,
 1.5528741,
 0.8672886,
 0,
 0.8923231,
 0.24959758,
 0.033037916,
 1.0103151,
 0.5228086,
 0.00860211,
 0.67165154,
 0.044979654,
 1.3637499,
 0.9354423,
 0.16858584,
 1.2242861,
 0.3195598,
 1.0488172,
 0.033733066,
 0.22583354,
 0.7680503,
 0.32698482,
 1.4297348,
 0.6111368,
 0.38082814,
 0.8622422,
 0.4240704,
 0,
 0.0660233,
 2.0836196,
 0.4113513,
 0.93882495,
 0.24387053,
 0.03775966,
 0.051863663,
 2.4749348,
 0.30196866,
 0.26083788,
 0.6160271,
 0.40102437,
 0.3303147,
 1.6322525,
 0.112503946,
 0.44621903,
 0,
 0,
 0.62348735,
 0.019859465,
 0,
 1.9309475,
 0.3344104,
 0.49386588,
 0.2757785,
 0.30884862,
 0,
 0,
 0.35953444,
 0.25887114,
 0.6095135,
 0.32299286,
 0.46288028,
 0.4698054,
 0.91948116,
 1.0257791,
 0,
 0.26535517,
 0.6463761,
 0.2364129,
 1.4319595,
 0.12061059,
 0.582678,
 2.313346,
 2.1098785,
 0.45710894,
 0.23695253,
 0.37271547,
 0.33382112,
 0.21677788,
 1.8623524,
 0.042686656,
 0.09395857,
 0.5237654,
 0.15126778,
 0.057883617,
 0.22991294,
 0.3719535,
 0.72062004,
 0.18830928,
 0.42652768,
 0.32809013,
 0.34505475,
 0.8866945,
 0.16044363,
 0,
 0.8284795,
 0.24554253,
 1.3365263,
 1.7946203,
 1.0789669,
 0,
 0.098501466,
 0,
 0.70375514,
 0,
 1.3534099,
 0.50818074,
 0.24280685,
 0.13857445,
 0.2746244,
 0.6045506,
 0.96795565,
 0.020348363,
 1.3979082,
 0.06301216,
 0.1490624,
 1.0015098,
 0.07963816,
 0.39535275,
 1.3260946,
 0.16613655,
 0.3582976,
 0.6313337,
 0.1558844,
 0.7410921,
 0.65154535,
 0.52748877,
 0.37614542,
 0.13433382,
 2.1593227,
 0.5591757,
 0.24848717,
 0.002883988,
 0,
 0.5071324,
 0.3546357,
 0.31556052,
 0.7306075,
 0.25171655,
 0.12800767,
 0.60536367,
 0.22001979,
 1.4947606,
 1.0862552,
 1.0555112,
 0.79471815,
 0.79947084,
 0.65666646,
 0.28213674,
 0.865945,
 0.27699465,
 0.3689481,
 0.007754964,
 0.33900636,
 1.2270985,
 0.4570693,
 0.2159755,
 0.1328748,
 0.6973881,
 0.546295,
 0.60447264,
 1.0057268,
 0.10416398,
 0.89924884,
 0.46589723,
 0.029465508,
 0.98333275,
 0.115773976,
 0.18252859,
 1.9549224,
 0.49803248,
 2.2426562,
 0.5265455,
 0.33705986,
 0.5155534,
 0,
 0.25741398,
 0.7455649,
 0.14475484,
 0.8384742,
 1.8663821,
 0.3832842,
 0.117875956,
 0,
 0.25730434,
 0,
 0.86981314,
 0.30921867,
 0.6996985,
 0.44089636,
 0.27068487,
 0.69499135,
 1.1874245,
 0.25400397,
 0.5031271,
 1.4415883,
 0.1515388,
 0.78407,
 0.9797408,
 0.12705374,
 0.5861941,
 0.5482096,
 0.32236633,
 0.14880794,
 0.15937087,
 2.018521,
 0.20648381,
 0.4357842,
 0.44792706,
 0.23222929,
 0.7550625,
 0.5341355,
 0.7568446,
 1.4119712,
 0.21727797,
 0.020700164,
 0.12065042,
 0.580952,
 0.34509587,
 0.016130105,
 0.25479904,
 0.47436154,
 0.54353344,
 0.27874073,
 0.2800814,
 0.57618845,
 0.6042459,
 0.33623847,
 0.78019786,
 1.1784183,
 0.7107803,
 1.7034498,
 0.4418938,
 0.2507639,
 0.5561641,
 0.6329129,
 0.36295947,
 0.12620065,
 0.5146433,
 0.3049183,
 0.66118073,
 0.999713,
 0.6359193,
 1.1121066,
 0.30013397,
 0.32738438,
 0.23685661,
 0.303176,
 0.24622554,
 0.12403358,
 0.2502555,
 1.3805817,
 0.6078707,
 0.7862599,
 0.09537894,
 0.5037867,
 0.41560632,
 0.0790893,
 0.49674287,
 0.14574845,
 0,
 0.31250647,
 0.495867,
 0.059935875,
 0.6401018,
 0.8627265,
 1.67095,
 0.20718125,
 0.22277775,
 0.26277244,
 0.019762931,
 0.44458404,
 0.9007693,
 0.48915944,
 0.34146264,
 1.3744292,
 0.90280133,
 0.44378895,
 0.99707407,
 0.45988238,
 0.3496686,
 0,
 0,
 0.07693464,
 0.6401018,
 0.5629887,
 0.42899784,
 1.2815201,
 0.11932671,
 0.32644445,
 0.8277799,
 0.2363009,
 0.30827406,
 0.5621191,
 0,
 0.17148547,
 0.0953681,
 0.07967237,
 0.98882514,
 0.5934209,
 0.32123792,
 0.15744966,
 0.26076946,
 0.2876907,
 0.8280368,
 0.21520959,
 2.4542646,
 1.0204997,
 0,
 0.7665856,
 0.12716106,
 0.60272217,
 0.9975458,
 0.029453902,
 0.25095475,
 0.12470339,
 2.085149,
 1.3844507,
 0.03875014,
 0.16229174,
 1.3308487,
 1.1482652,
 0.14640121,
 0.3823373,
 0.31291342,
 0,
 0,
 0.61302245,
 0.23324233,
 0.5834094,
 0.45613655,
 1.8752058,
 2.5220025,
 0.14920045,
 0.255239,
 0.048106387,
 0.99141234,
 0.32900283,
 0.1783356,
 0.85458094,
 0.1959032,
 0.2748163,
 0,
 0.58969426,
 0.7622735,
 0.23044054,
 0.4677946,
 0.61499536,
 0.51052743,
 0.3428805,
 0.7796873,
 0.6444502,
 0.22178562,
 1.448107,
 0.45375383,
 0.57674086,
 0.27799,
 0.049881995,
 0.64661825,
 0,
 1.2813033,
 0.2806851,
 0.491491,
 0.44521868,
 0.3992852,
 0,
 0.35396186,
 0.3919668,
 2.1684394,
 0.4013503,
 0.28436106,
 1.1961921,
 0.59455866,
 0.46736526,
 0.7210303,
 2.31172,
 0.79415816,
 0,
 1.0194197,
 0.018125074,
 0.16197997,
 0.18715344,
 1.2431852,
 1.7255441,
 0.18657358,
 0.14534874,
 0.07166022,
 0.033250734,
 0.55154365,
 1.963214,
 0.71967643,
 0.44715774,
 0.4079894,
 1.0816774,
 0.094625905,
 0.47977194,
 1.0781417,
 0.0077665336,
 0.56748873,
 0.43497223,
 0.8120596,
 0.28722537,
 0.19059919,
 0.13917163,
 0.79496324,
 0.04571452,
 0,
 0.18970941,
 0.39355785,
 0.100077674,
 0.14583531,
 0.37318134,
 1.0606233,
 0.48582834,
 0.6211323,
 0.63797545,
 0.71632385,
 0.7548521,
 0.1490624,
 0.46575245,
 0.12843983,
 0.43606034,
 0.3186436,
 0.167083,
 0,
 0.45596254,
 0.29646397,
 0.018143564,
 0.17025921,
 0.23975179,
 0.068954855,
 0,
 0,
 0.22114561,
 0.15338245,
 0.17254308,
 0.06383941,
 0.22459662,
 0.29073697,
 0.5902044,
 0.33836845,
 0.30800727,
 0.6803814,
 2.191792,
 2.6735897,
 0,
 3.501736,
 0.45223418,
 0.11544548,
 0.5507528,
 0.4333233,
 0.3114235,
 1.5320637,
 0.46629947,
 0.34301263,
 2.356311,
 0.31252798,
 0.92907655,
 0.0155122895,
 0.27563554,
 1.710095,
 1.1389011,
 0.48296773,
 0.22821069,
 0.34615228,
 0.15018341,
 0.11763307,
 0.7145245,
 0.042483054,
 0.27166823,
 0.44806117,
 0.07707976,
 0.80420184,
 0.36921605,
 0.27239764,
 0.16093096,
 0.5058489,
 1.9689143,
 0.7610992,
 0,
 0.26890275,
 0,
 0.6113209,
 0.84791857,
 0.3722875,
 0.09816957,
 0.015603652,
 1.5657005,
 0.19907577,
 0.32836977,
 0.63902104,
 0.3138133,
 0.29847458,
 0.14790861,
 0.58700603,
 0.13708983,
 0.6733266,
 0.22121741,
 0.10347729,
 0.31178558,
 0.97077626,
 0.15038183,
 0.47082385,
 0.4071015,
 0.70766085,
 0.5336306,
 1.7322043,
 0.25071886,
 0.2862354,
 0.8063865,
 0.3452651,
 0.024103979,
 0.48720682,
 0.245125,
 0.36195394,
 0.22445059,
 0.8020848,
 0.18036953,
 0.15792374,
 1.2203108,
 0.4923735,
 0.08356376,
 0.68009067,
 0.36156493,
 0.7796873,
 0.43330434,
 0.3363127,
 0.13832128,
 0.31442055,
 0.5155534,
 0.3721011,
 0.7748203,
 0.34841907,
 0.2057302,
 0.6701216,
 0.23157327,
 0.8355413,
 0.038379405,
 0.25850108,
 0.26024732,
 0.37685746,
 0.26686385,
 0.02954836,
 0.23578489,
 0.09291895,
 0.09125577,
 1.7473624,
 0.94151217,
 0.30914643,
 0.11566709,
 0.14389321,
 0.24384494,
 0.70199984,
 0.051463835,
 0.18978313,
 0.13306738,
 0.09554724,
 0.24407744,
 1.9459296,
 0.26084736,
 0.19813561,
 0.6657619,
 0.09351195,
 0.31764284,
 0,
 0,
 1.3009943,
 0.08735696,
 0,
 0.6893444,
 0.20340143,
 0.21583492,
 0.31465682,
 0.22554903,
 0,
 0.30086723,
 1.0626456,
 0.211934,
 0.3673304,
 0.07629183,
 0.30102155,
 0.7324485,
 1.0698088,
 1.4508832,
 1.1033199,
 1.4073809,
 1.0082291,
 0.67343545,
 0.93772066,
 0.1654314,
 0.528852,
 0.5182939,
 0.48009777,
 0.5298358,
 0.5230952,
 0.11866124,
 0.489936,
 0.6777896,
 0.14892195,
 0.27563554,
 0.60901695,
 0,
 1.3970981,
 0.7878847,
 0.6081596,
 0.32703805,
 0.75231117,
 1.1264448,
 1.1027832,
 0.48009777,
 0.8992907,
 1.7998283,
 0.43497223,
 0.79362893,
 0.03567584,
 0,
 2.5751307,
 0.2733632,
 1.0172616,
 0.37691557,
 0.90123606,
 0.12129998,
 0.8680457,
 0.15226239,
 0.71734256,
 0.05422003,
 0.8354997,
 0.45252818,
 0.1952513,
 0.058268648,
 0.3490646,
 0.66194236,
 0.78019786,
 0.577462,
 0.298998,
 0.49910787,
 0.46245354,
 0.20493215,
 0.046206158,
 0.053497232,
 0.18624756,
 0.5068195,
 0.6768305,
 0.70766085,
 0.15702692,
 0.33739525,
 0.42578328,
 0.9679531,
 0.8034961,
 0.3426789,
 1.3513526,
 0.7546237,
 0.4877804,
 0.84254473,
 0.8016236,
 0.52447414,
 0.74222606,
 0.21108076,
 0.016617557,
 0,
 0.16307099,
 0.23696588,
 1.2520537,
 0.0478545,
 0.39631975,
 0.18708727,
 0.6076238,
 0.33830005,
 0.0174112,
 0.19220015,
 0.634956,
 0.2949719,
 0.27212825,
 0.46543068,
 0.35603887,
 0,
 0.21497564,
 0.6669245,
 0.23046038,
 0.1091984,
 0.40691897,
 0.12933317,
 0.64762735,
 0.16650821,
 0.32698482,
 0.7833441,
 0.40681964,
 0.810151,
 0.5385905,
 0.42152825,
 0.22317296,
 1.1180425,
 0.4748366,
 0.062760755,
 0.22778238,
 0.08791632,
 0.7957094,
 0.46004203,
 0.3344048,
 0.3097379,
 0.8510918,
 0.41977075,
 0.4234094,
 0.22997391,
 0.4128412,
 0.70500827,
 0.11137038,
 1.6096729,
 0.05139228,
 0.41112995,
 0.1374504,
 0.8362859,
 1.0968409,
 0.5814089,
 1.1389011,
 0,
 0.42996624,
 0.35647404,
 1.0361496,
 0.38624895,
 0.17202519,
 0.051863663,
 0.17523976,
 0.70482033,
 0.054710537,
 0.14055614,
 0.46494192,
 0.25021413,
 1.4166836,
 0.5343035,
 0.6972826,
 0.22656074,
 0,
 0.029321132,
 0.25007507,
 0.842804,
 0.18300319,
 0.29325202,
 1.4641163,
 0.09578038,
 0.19909437,
 0.663477,
 0.03572519,
 0.11811204,
 ...]

In [70]:
from sklearn.metrics import mean_squared_error
score = np.sqrt(mean_squared_error(va_pred_0, y_test))
print(score)

0.6034448592873829

In [74]:
# 予測
pred = model.predict(dtest)
pred_0 = [0 if i <= 0 else i for i in pred]

### GDBT(NaNのまま，encoding多め): 0.6044626823948162

### GDBT(NaNのまま): 0.6042383633971182

### GBDT(NaNを-99に変換): 0.610822959180329

### ランダムフォレスト: 0.6326244864434752

# テストデータで予測

In [75]:
pred_df = pd.DataFrame(pred_0, columns=['応募数 合計'])
pred_df.head()

     応募数 合計
0  2.585091
1  3.112152
2  2.960930
3  3.639328
4  2.566336

In [76]:
submit = pd.concat([work_number, pred_df], axis=1)
submit.head()

       お仕事No.    応募数 合計
0  2203556553  2.585091
1  2203515280  3.112152
2  2203546900  2.960930
3  2203545344  3.639328
4  2203557987  2.566336

In [77]:
submit.to_csv("submit_GBDT_NaN_encoding_2_0_NaNinfo.csv", index=False, encoding='utf_8_sig')